-- Generated by tools.seeder. Do not hand-edit.
-- Requires sqlcmd variable SeedRoot, e.g. -v SeedRoot="C:\path\to\seed" (or /path/to/seed).

IF OBJECT_ID(N'ref.LaborGrade', N'U') IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM [ref].[LaborGrade])
BEGIN
    DECLARE @sql nvarchar(max) =
        N'BULK INSERT [ref].[LaborGrade]
    FROM ''$(SeedRoot)/ref/LaborGrade.csv''
    WITH (FORMAT = ''CSV'', FIRSTROW = 2, FIELDQUOTE = ''"'', ROWTERMINATOR = ''0x0a'', DATAFILETYPE = ''char'''
        + CASE WHEN SERVERPROPERTY('HostPlatform') = N'Windows'
               THEN N', CODEPAGE = ''65001''' ELSE N'' END
        + N', KEEPIDENTITY, TABLOCK);';
    BEGIN TRY
    SET IDENTITY_INSERT [ref].[LaborGrade] ON;
        EXEC sys.sp_executesql @sql;
    SET IDENTITY_INSERT [ref].[LaborGrade] OFF;
    END TRY
    BEGIN CATCH
    SET IDENTITY_INSERT [ref].[LaborGrade] OFF;
        THROW;
    END CATCH
END
GO
