-- Generated by tools.seeder. Do not hand-edit.
-- Requires sqlcmd variable SeedRoot, e.g. -v SeedRoot="C:\path\to\seed" (or /path/to/seed).

IF OBJECT_ID(N'fact.SafetyAuditFinding', N'U') IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM [fact].[SafetyAuditFinding])
BEGIN
    DECLARE @sql nvarchar(max) =
        N'BULK INSERT [fact].[SafetyAuditFinding]
    FROM ''$(SeedRoot)/fact/SafetyAuditFinding.csv''
    WITH (FORMAT = ''CSV'', FIRSTROW = 2, FIELDQUOTE = ''"'', ROWTERMINATOR = ''0x0a'', DATAFILETYPE = ''char'''
        + CASE WHEN SERVERPROPERTY('HostPlatform') = N'Windows'
               THEN N', CODEPAGE = ''65001''' ELSE N'' END
        + N', TABLOCK);';
    BEGIN TRY
        EXEC sys.sp_executesql @sql;
    END TRY
    BEGIN CATCH
        THROW;
    END CATCH
END
GO
