-- Generated by tools.generator. Do not hand-edit.

-- Subject area: energy_utilities

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyMeterAsset_EnergyMeterPointKeyAssetKey' AND object_id = OBJECT_ID(N'bridge.EnergyMeterAsset'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyMeterAsset_EnergyMeterPointKeyAssetKey] ON [bridge].[EnergyMeterAsset] ([EnergyMeterPointKey], [AssetKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyMeterWorkCenter_EnergyMeterPointKeyWorkCenterKey' AND object_id = OBJECT_ID(N'bridge.EnergyMeterWorkCenter'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyMeterWorkCenter_EnergyMeterPointKeyWorkCenterKey] ON [bridge].[EnergyMeterWorkCenter] ([EnergyMeterPointKey], [WorkCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyProjectMeterPoint_EnergyEfficiencyProjectKeyEnergyMeterPointKey' AND object_id = OBJECT_ID(N'bridge.EnergyProjectMeterPoint'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyProjectMeterPoint_EnergyEfficiencyProjectKeyEnergyMeterPointKey] ON [bridge].[EnergyProjectMeterPoint] ([EnergyEfficiencyProjectKey], [EnergyMeterPointKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyCarrier_EnergyCarrierCode' AND object_id = OBJECT_ID(N'dim.EnergyCarrier'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyCarrier_EnergyCarrierCode] ON [dim].[EnergyCarrier] ([EnergyCarrierCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyDemandContract_DemandContractNumber' AND object_id = OBJECT_ID(N'dim.EnergyDemandContract'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyDemandContract_DemandContractNumber] ON [dim].[EnergyDemandContract] ([DemandContractNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyEfficiencyMeasure_EnergyEfficiencyMeasureCode' AND object_id = OBJECT_ID(N'dim.EnergyEfficiencyMeasure'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyEfficiencyMeasure_EnergyEfficiencyMeasureCode] ON [dim].[EnergyEfficiencyMeasure] ([EnergyEfficiencyMeasureCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyEfficiencyProject_EfficiencyProjectNumber' AND object_id = OBJECT_ID(N'dim.EnergyEfficiencyProject'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyEfficiencyProject_EfficiencyProjectNumber] ON [dim].[EnergyEfficiencyProject] ([EfficiencyProjectNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyEmissionFactor_EmissionFactorCode' AND object_id = OBJECT_ID(N'dim.EnergyEmissionFactor'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyEmissionFactor_EmissionFactorCode] ON [dim].[EnergyEmissionFactor] ([EmissionFactorCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyMeterPoint_MeterPointNumber' AND object_id = OBJECT_ID(N'dim.EnergyMeterPoint'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyMeterPoint_MeterPointNumber] ON [dim].[EnergyMeterPoint] ([MeterPointNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyMeterPointClass_EnergyMeterPointClassCode' AND object_id = OBJECT_ID(N'dim.EnergyMeterPointClass'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyMeterPointClass_EnergyMeterPointClassCode] ON [dim].[EnergyMeterPointClass] ([EnergyMeterPointClassCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyMeterType_EnergyMeterTypeCode' AND object_id = OBJECT_ID(N'dim.EnergyMeterType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyMeterType_EnergyMeterTypeCode] ON [dim].[EnergyMeterType] ([EnergyMeterTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyProjectPortfolio_EnergyProjectPortfolioCode' AND object_id = OBJECT_ID(N'dim.EnergyProjectPortfolio'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyProjectPortfolio_EnergyProjectPortfolioCode] ON [dim].[EnergyProjectPortfolio] ([EnergyProjectPortfolioCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyProjectProgram_EnergyProjectProgramCode' AND object_id = OBJECT_ID(N'dim.EnergyProjectProgram'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyProjectProgram_EnergyProjectProgramCode] ON [dim].[EnergyProjectProgram] ([EnergyProjectProgramCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyProjectType_EnergyProjectTypeCode' AND object_id = OBJECT_ID(N'dim.EnergyProjectType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyProjectType_EnergyProjectTypeCode] ON [dim].[EnergyProjectType] ([EnergyProjectTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyRateSchedule_EnergyRateScheduleCode' AND object_id = OBJECT_ID(N'dim.EnergyRateSchedule'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyRateSchedule_EnergyRateScheduleCode] ON [dim].[EnergyRateSchedule] ([EnergyRateScheduleCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyRateTier_EnergyRateTierCode' AND object_id = OBJECT_ID(N'dim.EnergyRateTier'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyRateTier_EnergyRateTierCode] ON [dim].[EnergyRateTier] ([EnergyRateTierCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergySourceCategory_EnergySourceCategoryCode' AND object_id = OBJECT_ID(N'dim.EnergySourceCategory'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergySourceCategory_EnergySourceCategoryCode] ON [dim].[EnergySourceCategory] ([EnergySourceCategoryCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergySubmeterZone_EnergySubmeterZoneCode' AND object_id = OBJECT_ID(N'dim.EnergySubmeterZone'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergySubmeterZone_EnergySubmeterZoneCode] ON [dim].[EnergySubmeterZone] ([EnergySubmeterZoneCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyTariff_TariffCode' AND object_id = OBJECT_ID(N'dim.EnergyTariff'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyTariff_TariffCode] ON [dim].[EnergyTariff] ([TariffCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyTariffMarket_EnergyTariffMarketCode' AND object_id = OBJECT_ID(N'dim.EnergyTariffMarket'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyTariffMarket_EnergyTariffMarketCode] ON [dim].[EnergyTariffMarket] ([EnergyTariffMarketCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyTariffProvider_EnergyTariffProviderCode' AND object_id = OBJECT_ID(N'dim.EnergyTariffProvider'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyTariffProvider_EnergyTariffProviderCode] ON [dim].[EnergyTariffProvider] ([EnergyTariffProviderCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyUtilityAccount_UtilityAccountNumber' AND object_id = OBJECT_ID(N'dim.EnergyUtilityAccount'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyUtilityAccount_UtilityAccountNumber] ON [dim].[EnergyUtilityAccount] ([UtilityAccountNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyUtilityCategory_EnergyUtilityCategoryCode' AND object_id = OBJECT_ID(N'dim.EnergyUtilityCategory'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyUtilityCategory_EnergyUtilityCategoryCode] ON [dim].[EnergyUtilityCategory] ([EnergyUtilityCategoryCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyUtilityCircuit_EnergyUtilityCircuitCode' AND object_id = OBJECT_ID(N'dim.EnergyUtilityCircuit'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyUtilityCircuit_EnergyUtilityCircuitCode] ON [dim].[EnergyUtilityCircuit] ([EnergyUtilityCircuitCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyUtilitySystem_EnergyUtilitySystemCode' AND object_id = OBJECT_ID(N'dim.EnergyUtilitySystem'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyUtilitySystem_EnergyUtilitySystemCode] ON [dim].[EnergyUtilitySystem] ([EnergyUtilitySystemCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyDemandPeak_EnergyDemandContractKey' AND object_id = OBJECT_ID(N'fact.EnergyDemandPeak'))
    CREATE NONCLUSTERED INDEX [IX_EnergyDemandPeak_EnergyDemandContractKey] ON [fact].[EnergyDemandPeak] ([EnergyDemandContractKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyDemandPeak_EnergyMeterPointKey' AND object_id = OBJECT_ID(N'fact.EnergyDemandPeak'))
    CREATE NONCLUSTERED INDEX [IX_EnergyDemandPeak_EnergyMeterPointKey] ON [fact].[EnergyDemandPeak] ([EnergyMeterPointKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyDemandPeak_PeakDateKey' AND object_id = OBJECT_ID(N'fact.EnergyDemandPeak'))
    CREATE NONCLUSTERED INDEX [IX_EnergyDemandPeak_PeakDateKey] ON [fact].[EnergyDemandPeak] ([PeakDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyDemandPeak_PeakTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.EnergyDemandPeak'))
    CREATE NONCLUSTERED INDEX [IX_EnergyDemandPeak_PeakTimeOfDayKey] ON [fact].[EnergyDemandPeak] ([PeakTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyDemandPeak_PlantKey' AND object_id = OBJECT_ID(N'fact.EnergyDemandPeak'))
    CREATE NONCLUSTERED INDEX [IX_EnergyDemandPeak_PlantKey] ON [fact].[EnergyDemandPeak] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyDemandPeak_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.EnergyDemandPeak'))
    CREATE NONCLUSTERED INDEX [IX_EnergyDemandPeak_UnitOfMeasureKey] ON [fact].[EnergyDemandPeak] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyGreenhouseGasSnapshot_BusinessUnitKey' AND object_id = OBJECT_ID(N'fact.EnergyGreenhouseGasSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_EnergyGreenhouseGasSnapshot_BusinessUnitKey] ON [fact].[EnergyGreenhouseGasSnapshot] ([BusinessUnitKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyGreenhouseGasSnapshot_EnergyCarrierKey' AND object_id = OBJECT_ID(N'fact.EnergyGreenhouseGasSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_EnergyGreenhouseGasSnapshot_EnergyCarrierKey] ON [fact].[EnergyGreenhouseGasSnapshot] ([EnergyCarrierKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyGreenhouseGasSnapshot_EnergyEmissionFactorKey' AND object_id = OBJECT_ID(N'fact.EnergyGreenhouseGasSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_EnergyGreenhouseGasSnapshot_EnergyEmissionFactorKey] ON [fact].[EnergyGreenhouseGasSnapshot] ([EnergyEmissionFactorKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyGreenhouseGasSnapshot_EnergyEmissionScopeKey' AND object_id = OBJECT_ID(N'fact.EnergyGreenhouseGasSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_EnergyGreenhouseGasSnapshot_EnergyEmissionScopeKey] ON [fact].[EnergyGreenhouseGasSnapshot] ([EnergyEmissionScopeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyGreenhouseGasSnapshot_PlantKey' AND object_id = OBJECT_ID(N'fact.EnergyGreenhouseGasSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_EnergyGreenhouseGasSnapshot_PlantKey] ON [fact].[EnergyGreenhouseGasSnapshot] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyGreenhouseGasSnapshot_SnapshotDateKey' AND object_id = OBJECT_ID(N'fact.EnergyGreenhouseGasSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_EnergyGreenhouseGasSnapshot_SnapshotDateKey] ON [fact].[EnergyGreenhouseGasSnapshot] ([SnapshotDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyGreenhouseGasSnapshot_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.EnergyGreenhouseGasSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_EnergyGreenhouseGasSnapshot_UnitOfMeasureKey] ON [fact].[EnergyGreenhouseGasSnapshot] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyGreenhouseGasSnapshot_Columnstore' AND object_id = OBJECT_ID(N'fact.EnergyGreenhouseGasSnapshot'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_EnergyGreenhouseGasSnapshot_Columnstore] ON [fact].[EnergyGreenhouseGasSnapshot];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyMeterReading_AssetKey' AND object_id = OBJECT_ID(N'fact.EnergyMeterReading'))
    CREATE NONCLUSTERED INDEX [IX_EnergyMeterReading_AssetKey] ON [fact].[EnergyMeterReading] ([AssetKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyMeterReading_EnergyMeterPointKey' AND object_id = OBJECT_ID(N'fact.EnergyMeterReading'))
    CREATE NONCLUSTERED INDEX [IX_EnergyMeterReading_EnergyMeterPointKey] ON [fact].[EnergyMeterReading] ([EnergyMeterPointKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyMeterReading_EnergyReadingQualityKey' AND object_id = OBJECT_ID(N'fact.EnergyMeterReading'))
    CREATE NONCLUSTERED INDEX [IX_EnergyMeterReading_EnergyReadingQualityKey] ON [fact].[EnergyMeterReading] ([EnergyReadingQualityKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyMeterReading_PlantKey' AND object_id = OBJECT_ID(N'fact.EnergyMeterReading'))
    CREATE NONCLUSTERED INDEX [IX_EnergyMeterReading_PlantKey] ON [fact].[EnergyMeterReading] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyMeterReading_ReadingDateKey' AND object_id = OBJECT_ID(N'fact.EnergyMeterReading'))
    CREATE NONCLUSTERED INDEX [IX_EnergyMeterReading_ReadingDateKey] ON [fact].[EnergyMeterReading] ([ReadingDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyMeterReading_ReadingTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.EnergyMeterReading'))
    CREATE NONCLUSTERED INDEX [IX_EnergyMeterReading_ReadingTimeOfDayKey] ON [fact].[EnergyMeterReading] ([ReadingTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyMeterReading_SiteKey' AND object_id = OBJECT_ID(N'fact.EnergyMeterReading'))
    CREATE NONCLUSTERED INDEX [IX_EnergyMeterReading_SiteKey] ON [fact].[EnergyMeterReading] ([SiteKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyMeterReading_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.EnergyMeterReading'))
    CREATE NONCLUSTERED INDEX [IX_EnergyMeterReading_UnitOfMeasureKey] ON [fact].[EnergyMeterReading] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyMeterReading_WorkCenterKey' AND object_id = OBJECT_ID(N'fact.EnergyMeterReading'))
    CREATE NONCLUSTERED INDEX [IX_EnergyMeterReading_WorkCenterKey] ON [fact].[EnergyMeterReading] ([WorkCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyMeterReading_Columnstore' AND object_id = OBJECT_ID(N'fact.EnergyMeterReading'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_EnergyMeterReading_Columnstore] ON [fact].[EnergyMeterReading];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_CostCenterKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_CostCenterKey] ON [fact].[EnergyUtilityCost] ([CostCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_CurrencyKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_CurrencyKey] ON [fact].[EnergyUtilityCost] ([CurrencyKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_EnergyMeterPointKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_EnergyMeterPointKey] ON [fact].[EnergyUtilityCost] ([EnergyMeterPointKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_EnergyTariffChargeTypeKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_EnergyTariffChargeTypeKey] ON [fact].[EnergyUtilityCost] ([EnergyTariffChargeTypeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_EnergyTariffKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_EnergyTariffKey] ON [fact].[EnergyUtilityCost] ([EnergyTariffKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_EnergyUtilityAccountKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_EnergyUtilityAccountKey] ON [fact].[EnergyUtilityCost] ([EnergyUtilityAccountKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_GlAccountKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_GlAccountKey] ON [fact].[EnergyUtilityCost] ([GlAccountKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_InvoiceDateKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_InvoiceDateKey] ON [fact].[EnergyUtilityCost] ([InvoiceDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_PlantKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_PlantKey] ON [fact].[EnergyUtilityCost] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_ServiceEndDateKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_ServiceEndDateKey] ON [fact].[EnergyUtilityCost] ([ServiceEndDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_ServiceStartDateKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_ServiceStartDateKey] ON [fact].[EnergyUtilityCost] ([ServiceStartDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_EnergyUtilityCost_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.EnergyUtilityCost'))
    CREATE NONCLUSTERED INDEX [IX_EnergyUtilityCost_UnitOfMeasureKey] ON [fact].[EnergyUtilityCost] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyEfficiencyProjectStatus_EfficiencyProjectStatusCode' AND object_id = OBJECT_ID(N'ref.EnergyEfficiencyProjectStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyEfficiencyProjectStatus_EfficiencyProjectStatusCode] ON [ref].[EnergyEfficiencyProjectStatus] ([EfficiencyProjectStatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyEmissionScope_EmissionScopeCode' AND object_id = OBJECT_ID(N'ref.EnergyEmissionScope'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyEmissionScope_EmissionScopeCode] ON [ref].[EnergyEmissionScope] ([EmissionScopeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyReadingQuality_ReadingQualityCode' AND object_id = OBJECT_ID(N'ref.EnergyReadingQuality'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyReadingQuality_ReadingQualityCode] ON [ref].[EnergyReadingQuality] ([ReadingQualityCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyTariffChargeType_TariffChargeTypeCode' AND object_id = OBJECT_ID(N'ref.EnergyTariffChargeType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyTariffChargeType_TariffChargeTypeCode] ON [ref].[EnergyTariffChargeType] ([TariffChargeTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergyUtilityAccountStatus_UtilityAccountStatusCode' AND object_id = OBJECT_ID(N'ref.EnergyUtilityAccountStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergyUtilityAccountStatus_UtilityAccountStatusCode] ON [ref].[EnergyUtilityAccountStatus] ([UtilityAccountStatusCode]);
GO
