-- Generated by tools.generator. Do not hand-edit.

-- Subject area: maintenance

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceAssetFailureMode_AssetKeyMaintenanceFailureModeKey' AND object_id = OBJECT_ID(N'bridge.MaintenanceAssetFailureMode'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceAssetFailureMode_AssetKeyMaintenanceFailureModeKey] ON [bridge].[MaintenanceAssetFailureMode] ([AssetKey], [MaintenanceFailureModeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceCrewEmployee_MaintenanceCrewKeyEmployeeKeyMaintenanceCrewRoleKey' AND object_id = OBJECT_ID(N'bridge.MaintenanceCrewEmployee'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceCrewEmployee_MaintenanceCrewKeyEmployeeKeyMaintenanceCrewRoleKey] ON [bridge].[MaintenanceCrewEmployee] ([MaintenanceCrewKey], [EmployeeKey], [MaintenanceCrewRoleKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceOrderSparePart_MaintenanceWorkOrderKeyMaintenanceSparePartKey' AND object_id = OBJECT_ID(N'bridge.MaintenanceOrderSparePart'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceOrderSparePart_MaintenanceWorkOrderKeyMaintenanceSparePartKey] ON [bridge].[MaintenanceOrderSparePart] ([MaintenanceWorkOrderKey], [MaintenanceSparePartKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceAssetClass_MaintenanceAssetClassCode' AND object_id = OBJECT_ID(N'dim.MaintenanceAssetClass'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceAssetClass_MaintenanceAssetClassCode] ON [dim].[MaintenanceAssetClass] ([MaintenanceAssetClassCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceAssetComponentType_MaintenanceAssetComponentTypeCode' AND object_id = OBJECT_ID(N'dim.MaintenanceAssetComponentType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceAssetComponentType_MaintenanceAssetComponentTypeCode] ON [dim].[MaintenanceAssetComponentType] ([MaintenanceAssetComponentTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceAssetSubClass_MaintenanceAssetSubClassCode' AND object_id = OBJECT_ID(N'dim.MaintenanceAssetSubClass'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceAssetSubClass_MaintenanceAssetSubClassCode] ON [dim].[MaintenanceAssetSubClass] ([MaintenanceAssetSubClassCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceAssetSystem_MaintenanceAssetSystemCode' AND object_id = OBJECT_ID(N'dim.MaintenanceAssetSystem'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceAssetSystem_MaintenanceAssetSystemCode] ON [dim].[MaintenanceAssetSystem] ([MaintenanceAssetSystemCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceConditionPoint_ConditionPointNumber' AND object_id = OBJECT_ID(N'dim.MaintenanceConditionPoint'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceConditionPoint_ConditionPointNumber] ON [dim].[MaintenanceConditionPoint] ([ConditionPointNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceCrew_MaintenanceCrewCode' AND object_id = OBJECT_ID(N'dim.MaintenanceCrew'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceCrew_MaintenanceCrewCode] ON [dim].[MaintenanceCrew] ([MaintenanceCrewCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceCrewRole_MaintenanceCrewRoleCode' AND object_id = OBJECT_ID(N'dim.MaintenanceCrewRole'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceCrewRole_MaintenanceCrewRoleCode] ON [dim].[MaintenanceCrewRole] ([MaintenanceCrewRoleCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceFailureCause_MaintenanceFailureCauseCode' AND object_id = OBJECT_ID(N'dim.MaintenanceFailureCause'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceFailureCause_MaintenanceFailureCauseCode] ON [dim].[MaintenanceFailureCause] ([MaintenanceFailureCauseCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceFailureDomain_MaintenanceFailureDomainCode' AND object_id = OBJECT_ID(N'dim.MaintenanceFailureDomain'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceFailureDomain_MaintenanceFailureDomainCode] ON [dim].[MaintenanceFailureDomain] ([MaintenanceFailureDomainCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceFailureMode_MaintenanceFailureModeCode' AND object_id = OBJECT_ID(N'dim.MaintenanceFailureMode'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceFailureMode_MaintenanceFailureModeCode] ON [dim].[MaintenanceFailureMode] ([MaintenanceFailureModeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceFailureRemedy_MaintenanceFailureRemedyCode' AND object_id = OBJECT_ID(N'dim.MaintenanceFailureRemedy'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceFailureRemedy_MaintenanceFailureRemedyCode] ON [dim].[MaintenanceFailureRemedy] ([MaintenanceFailureRemedyCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenancePlanClass_MaintenancePlanClassCode' AND object_id = OBJECT_ID(N'dim.MaintenancePlanClass'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenancePlanClass_MaintenancePlanClassCode] ON [dim].[MaintenancePlanClass] ([MaintenancePlanClassCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenancePlanFamily_MaintenancePlanFamilyCode' AND object_id = OBJECT_ID(N'dim.MaintenancePlanFamily'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenancePlanFamily_MaintenancePlanFamilyCode] ON [dim].[MaintenancePlanFamily] ([MaintenancePlanFamilyCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenancePmPlan_PmPlanNumber' AND object_id = OBJECT_ID(N'dim.MaintenancePmPlan'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenancePmPlan_PmPlanNumber] ON [dim].[MaintenancePmPlan] ([PmPlanNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceRegion_MaintenanceRegionCode' AND object_id = OBJECT_ID(N'dim.MaintenanceRegion'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceRegion_MaintenanceRegionCode] ON [dim].[MaintenanceRegion] ([MaintenanceRegionCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceSkillGroup_MaintenanceSkillGroupCode' AND object_id = OBJECT_ID(N'dim.MaintenanceSkillGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceSkillGroup_MaintenanceSkillGroupCode] ON [dim].[MaintenanceSkillGroup] ([MaintenanceSkillGroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceSparePart_SparePartNumber' AND object_id = OBJECT_ID(N'dim.MaintenanceSparePart'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceSparePart_SparePartNumber] ON [dim].[MaintenanceSparePart] ([SparePartNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceTaskGroup_MaintenanceTaskGroupCode' AND object_id = OBJECT_ID(N'dim.MaintenanceTaskGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceTaskGroup_MaintenanceTaskGroupCode] ON [dim].[MaintenanceTaskGroup] ([MaintenanceTaskGroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceTaskType_MaintenanceTaskTypeCode' AND object_id = OBJECT_ID(N'dim.MaintenanceTaskType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceTaskType_MaintenanceTaskTypeCode] ON [dim].[MaintenanceTaskType] ([MaintenanceTaskTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceTrade_MaintenanceTradeCode' AND object_id = OBJECT_ID(N'dim.MaintenanceTrade'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceTrade_MaintenanceTradeCode] ON [dim].[MaintenanceTrade] ([MaintenanceTradeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceWorkOrder_MaintenanceWorkOrderNumber' AND object_id = OBJECT_ID(N'dim.MaintenanceWorkOrder'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceWorkOrder_MaintenanceWorkOrderNumber] ON [dim].[MaintenanceWorkOrder] ([MaintenanceWorkOrderNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceWorkRequest_WorkRequestNumber' AND object_id = OBJECT_ID(N'dim.MaintenanceWorkRequest'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceWorkRequest_WorkRequestNumber] ON [dim].[MaintenanceWorkRequest] ([WorkRequestNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceConditionReading_AssetKey' AND object_id = OBJECT_ID(N'fact.MaintenanceConditionReading'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceConditionReading_AssetKey] ON [fact].[MaintenanceConditionReading] ([AssetKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceConditionReading_MaintenanceConditionPointKey' AND object_id = OBJECT_ID(N'fact.MaintenanceConditionReading'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceConditionReading_MaintenanceConditionPointKey] ON [fact].[MaintenanceConditionReading] ([MaintenanceConditionPointKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceConditionReading_MaintenanceConditionTypeKey' AND object_id = OBJECT_ID(N'fact.MaintenanceConditionReading'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceConditionReading_MaintenanceConditionTypeKey] ON [fact].[MaintenanceConditionReading] ([MaintenanceConditionTypeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceConditionReading_PlantKey' AND object_id = OBJECT_ID(N'fact.MaintenanceConditionReading'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceConditionReading_PlantKey] ON [fact].[MaintenanceConditionReading] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceConditionReading_ReadingDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceConditionReading'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceConditionReading_ReadingDateKey] ON [fact].[MaintenanceConditionReading] ([ReadingDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceConditionReading_ReadingTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.MaintenanceConditionReading'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceConditionReading_ReadingTimeOfDayKey] ON [fact].[MaintenanceConditionReading] ([ReadingTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceConditionReading_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.MaintenanceConditionReading'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceConditionReading_UnitOfMeasureKey] ON [fact].[MaintenanceConditionReading] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceConditionReading_WorkCenterKey' AND object_id = OBJECT_ID(N'fact.MaintenanceConditionReading'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceConditionReading_WorkCenterKey] ON [fact].[MaintenanceConditionReading] ([WorkCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceConditionReading_Columnstore' AND object_id = OBJECT_ID(N'fact.MaintenanceConditionReading'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_MaintenanceConditionReading_Columnstore] ON [fact].[MaintenanceConditionReading];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_AssetKey' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceDowntimeAttribution_AssetKey] ON [fact].[MaintenanceDowntimeAttribution] ([AssetKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_EndDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceDowntimeAttribution_EndDateKey] ON [fact].[MaintenanceDowntimeAttribution] ([EndDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_EndTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceDowntimeAttribution_EndTimeOfDayKey] ON [fact].[MaintenanceDowntimeAttribution] ([EndTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_MaintenanceDowntimeReasonKey' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceDowntimeAttribution_MaintenanceDowntimeReasonKey] ON [fact].[MaintenanceDowntimeAttribution] ([MaintenanceDowntimeReasonKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_MaintenanceFailureSeverityKey' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceDowntimeAttribution_MaintenanceFailureSeverityKey] ON [fact].[MaintenanceDowntimeAttribution] ([MaintenanceFailureSeverityKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_MaintenanceWorkOrderKey' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceDowntimeAttribution_MaintenanceWorkOrderKey] ON [fact].[MaintenanceDowntimeAttribution] ([MaintenanceWorkOrderKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_PlantKey' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceDowntimeAttribution_PlantKey] ON [fact].[MaintenanceDowntimeAttribution] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_StartDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceDowntimeAttribution_StartDateKey] ON [fact].[MaintenanceDowntimeAttribution] ([StartDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_StartTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceDowntimeAttribution_StartTimeOfDayKey] ON [fact].[MaintenanceDowntimeAttribution] ([StartTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_WorkCenterKey' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceDowntimeAttribution_WorkCenterKey] ON [fact].[MaintenanceDowntimeAttribution] ([WorkCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceDowntimeAttribution_Columnstore' AND object_id = OBJECT_ID(N'fact.MaintenanceDowntimeAttribution'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_MaintenanceDowntimeAttribution_Columnstore] ON [fact].[MaintenanceDowntimeAttribution];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceLaborConfirmation_AssetKey' AND object_id = OBJECT_ID(N'fact.MaintenanceLaborConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceLaborConfirmation_AssetKey] ON [fact].[MaintenanceLaborConfirmation] ([AssetKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceLaborConfirmation_ConfirmationDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceLaborConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceLaborConfirmation_ConfirmationDateKey] ON [fact].[MaintenanceLaborConfirmation] ([ConfirmationDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceLaborConfirmation_ConfirmationTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.MaintenanceLaborConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceLaborConfirmation_ConfirmationTimeOfDayKey] ON [fact].[MaintenanceLaborConfirmation] ([ConfirmationTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceLaborConfirmation_CostCenterKey' AND object_id = OBJECT_ID(N'fact.MaintenanceLaborConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceLaborConfirmation_CostCenterKey] ON [fact].[MaintenanceLaborConfirmation] ([CostCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceLaborConfirmation_MaintenanceCrewKey' AND object_id = OBJECT_ID(N'fact.MaintenanceLaborConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceLaborConfirmation_MaintenanceCrewKey] ON [fact].[MaintenanceLaborConfirmation] ([MaintenanceCrewKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceLaborConfirmation_MaintenanceWorkOrderKey' AND object_id = OBJECT_ID(N'fact.MaintenanceLaborConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceLaborConfirmation_MaintenanceWorkOrderKey] ON [fact].[MaintenanceLaborConfirmation] ([MaintenanceWorkOrderKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceLaborConfirmation_MaintenanceWorkTypeKey' AND object_id = OBJECT_ID(N'fact.MaintenanceLaborConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceLaborConfirmation_MaintenanceWorkTypeKey] ON [fact].[MaintenanceLaborConfirmation] ([MaintenanceWorkTypeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceLaborConfirmation_TechnicianEmployeeKey' AND object_id = OBJECT_ID(N'fact.MaintenanceLaborConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceLaborConfirmation_TechnicianEmployeeKey] ON [fact].[MaintenanceLaborConfirmation] ([TechnicianEmployeeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceLaborConfirmation_Columnstore' AND object_id = OBJECT_ID(N'fact.MaintenanceLaborConfirmation'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_MaintenanceLaborConfirmation_Columnstore] ON [fact].[MaintenanceLaborConfirmation];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceSparePartUsage_AssetKey' AND object_id = OBJECT_ID(N'fact.MaintenanceSparePartUsage'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceSparePartUsage_AssetKey] ON [fact].[MaintenanceSparePartUsage] ([AssetKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceSparePartUsage_CostCenterKey' AND object_id = OBJECT_ID(N'fact.MaintenanceSparePartUsage'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceSparePartUsage_CostCenterKey] ON [fact].[MaintenanceSparePartUsage] ([CostCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceSparePartUsage_MaintenanceSparePartKey' AND object_id = OBJECT_ID(N'fact.MaintenanceSparePartUsage'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceSparePartUsage_MaintenanceSparePartKey] ON [fact].[MaintenanceSparePartUsage] ([MaintenanceSparePartKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceSparePartUsage_MaintenanceWorkOrderKey' AND object_id = OBJECT_ID(N'fact.MaintenanceSparePartUsage'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceSparePartUsage_MaintenanceWorkOrderKey] ON [fact].[MaintenanceSparePartUsage] ([MaintenanceWorkOrderKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceSparePartUsage_MovementDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceSparePartUsage'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceSparePartUsage_MovementDateKey] ON [fact].[MaintenanceSparePartUsage] ([MovementDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceSparePartUsage_MovementTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.MaintenanceSparePartUsage'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceSparePartUsage_MovementTimeOfDayKey] ON [fact].[MaintenanceSparePartUsage] ([MovementTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceSparePartUsage_PlantKey' AND object_id = OBJECT_ID(N'fact.MaintenanceSparePartUsage'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceSparePartUsage_PlantKey] ON [fact].[MaintenanceSparePartUsage] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceSparePartUsage_TransactionTypeKey' AND object_id = OBJECT_ID(N'fact.MaintenanceSparePartUsage'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceSparePartUsage_TransactionTypeKey] ON [fact].[MaintenanceSparePartUsage] ([TransactionTypeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceSparePartUsage_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.MaintenanceSparePartUsage'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceSparePartUsage_UnitOfMeasureKey] ON [fact].[MaintenanceSparePartUsage] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceSparePartUsage_Columnstore' AND object_id = OBJECT_ID(N'fact.MaintenanceSparePartUsage'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_MaintenanceSparePartUsage_Columnstore] ON [fact].[MaintenanceSparePartUsage];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_ApprovedDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_ApprovedDateKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([ApprovedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_AssetKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_AssetKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([AssetKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_ClosedDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_ClosedDateKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([ClosedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_CompletedDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_CompletedDateKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([CompletedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_MaintenanceCrewKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_MaintenanceCrewKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([MaintenanceCrewKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_MaintenanceOrderStatusKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_MaintenanceOrderStatusKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([MaintenanceOrderStatusKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_MaintenanceWorkOrderKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_MaintenanceWorkOrderKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([MaintenanceWorkOrderKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_MaintenanceWorkRequestKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_MaintenanceWorkRequestKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([MaintenanceWorkRequestKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_MaintenanceWorkTypeKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_MaintenanceWorkTypeKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([MaintenanceWorkTypeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_PlantKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_PlantKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_RequestedDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_RequestedDateKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([RequestedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_ScheduledDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_ScheduledDateKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([ScheduledDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_MaintenanceWorkOrderLifecycle_StartedDateKey' AND object_id = OBJECT_ID(N'fact.MaintenanceWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_MaintenanceWorkOrderLifecycle_StartedDateKey] ON [fact].[MaintenanceWorkOrderLifecycle] ([StartedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceConditionType_ConditionTypeCode' AND object_id = OBJECT_ID(N'ref.MaintenanceConditionType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceConditionType_ConditionTypeCode] ON [ref].[MaintenanceConditionType] ([ConditionTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceDowntimeReason_DowntimeReasonCode' AND object_id = OBJECT_ID(N'ref.MaintenanceDowntimeReason'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceDowntimeReason_DowntimeReasonCode] ON [ref].[MaintenanceDowntimeReason] ([DowntimeReasonCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceFailureSeverity_FailureSeverityCode' AND object_id = OBJECT_ID(N'ref.MaintenanceFailureSeverity'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceFailureSeverity_FailureSeverityCode] ON [ref].[MaintenanceFailureSeverity] ([FailureSeverityCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceOrderStatus_OrderStatusCode' AND object_id = OBJECT_ID(N'ref.MaintenanceOrderStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceOrderStatus_OrderStatusCode] ON [ref].[MaintenanceOrderStatus] ([OrderStatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceWorkType_WorkTypeCode' AND object_id = OBJECT_ID(N'ref.MaintenanceWorkType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceWorkType_WorkTypeCode] ON [ref].[MaintenanceWorkType] ([WorkTypeCode]);
GO
