-- Generated by tools.generator. Do not hand-edit.

-- Subject area: production_execution

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionLotGenealogy_ParentProductionLotKeyChildProductionLotKey' AND object_id = OBJECT_ID(N'bridge.ProductionLotGenealogy'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionLotGenealogy_ParentProductionLotKeyChildProductionLotKey] ON [bridge].[ProductionLotGenealogy] ([ParentProductionLotKey], [ChildProductionLotKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionOperationWorkCenter_ProductionOperationKeyWorkCenterKey' AND object_id = OBJECT_ID(N'bridge.ProductionOperationWorkCenter'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionOperationWorkCenter_ProductionOperationKeyWorkCenterKey] ON [bridge].[ProductionOperationWorkCenter] ([ProductionOperationKey], [WorkCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionRunCrewAssignment_ProductionRunKeyProductionCrewKeyProductionShiftKey' AND object_id = OBJECT_ID(N'bridge.ProductionRunCrewAssignment'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionRunCrewAssignment_ProductionRunKeyProductionCrewKeyProductionShiftKey] ON [bridge].[ProductionRunCrewAssignment] ([ProductionRunKey], [ProductionCrewKey], [ProductionShiftKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionWorkOrderEmployee_ProductionWorkOrderKeyEmployeeKeyProductionCrewRoleKey' AND object_id = OBJECT_ID(N'bridge.ProductionWorkOrderEmployee'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionWorkOrderEmployee_ProductionWorkOrderKeyEmployeeKeyProductionCrewRoleKey] ON [bridge].[ProductionWorkOrderEmployee] ([ProductionWorkOrderKey], [EmployeeKey], [ProductionCrewRoleKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionCrew_ProductionCrewCode' AND object_id = OBJECT_ID(N'dim.ProductionCrew'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionCrew_ProductionCrewCode] ON [dim].[ProductionCrew] ([ProductionCrewCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionCrewRole_ProductionCrewRoleCode' AND object_id = OBJECT_ID(N'dim.ProductionCrewRole'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionCrewRole_ProductionCrewRoleCode] ON [dim].[ProductionCrewRole] ([ProductionCrewRoleCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionCrewType_ProductionCrewTypeCode' AND object_id = OBJECT_ID(N'dim.ProductionCrewType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionCrewType_ProductionCrewTypeCode] ON [dim].[ProductionCrewType] ([ProductionCrewTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionLaborPool_ProductionLaborPoolCode' AND object_id = OBJECT_ID(N'dim.ProductionLaborPool'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionLaborPool_ProductionLaborPoolCode] ON [dim].[ProductionLaborPool] ([ProductionLaborPoolCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionLaborRegion_ProductionLaborRegionCode' AND object_id = OBJECT_ID(N'dim.ProductionLaborRegion'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionLaborRegion_ProductionLaborRegionCode] ON [dim].[ProductionLaborRegion] ([ProductionLaborRegionCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionLot_ProductionLotNumber' AND object_id = OBJECT_ID(N'dim.ProductionLot'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionLot_ProductionLotNumber] ON [dim].[ProductionLot] ([ProductionLotNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionLotClass_ProductionLotClassCode' AND object_id = OBJECT_ID(N'dim.ProductionLotClass'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionLotClass_ProductionLotClassCode] ON [dim].[ProductionLotClass] ([ProductionLotClassCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionLotDispositionGroup_ProductionLotDispositionGroupCode' AND object_id = OBJECT_ID(N'dim.ProductionLotDispositionGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionLotDispositionGroup_ProductionLotDispositionGroupCode] ON [dim].[ProductionLotDispositionGroup] ([ProductionLotDispositionGroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionLotFamily_ProductionLotFamilyCode' AND object_id = OBJECT_ID(N'dim.ProductionLotFamily'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionLotFamily_ProductionLotFamilyCode] ON [dim].[ProductionLotFamily] ([ProductionLotFamilyCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionLotGrade_ProductionLotGradeCode' AND object_id = OBJECT_ID(N'dim.ProductionLotGrade'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionLotGrade_ProductionLotGradeCode] ON [dim].[ProductionLotGrade] ([ProductionLotGradeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionOperation_ProductionOperationNumber' AND object_id = OBJECT_ID(N'dim.ProductionOperation'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionOperation_ProductionOperationNumber] ON [dim].[ProductionOperation] ([ProductionOperationNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionProcessArea_ProductionProcessAreaCode' AND object_id = OBJECT_ID(N'dim.ProductionProcessArea'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionProcessArea_ProductionProcessAreaCode] ON [dim].[ProductionProcessArea] ([ProductionProcessAreaCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionProcessCell_ProductionProcessCellCode' AND object_id = OBJECT_ID(N'dim.ProductionProcessCell'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionProcessCell_ProductionProcessCellCode] ON [dim].[ProductionProcessCell] ([ProductionProcessCellCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionProcessLine_ProductionProcessLineCode' AND object_id = OBJECT_ID(N'dim.ProductionProcessLine'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionProcessLine_ProductionProcessLineCode] ON [dim].[ProductionProcessLine] ([ProductionProcessLineCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionProcessStep_ProductionProcessStepCode' AND object_id = OBJECT_ID(N'dim.ProductionProcessStep'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionProcessStep_ProductionProcessStepCode] ON [dim].[ProductionProcessStep] ([ProductionProcessStepCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionRun_ProductionRunNumber' AND object_id = OBJECT_ID(N'dim.ProductionRun'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionRun_ProductionRunNumber] ON [dim].[ProductionRun] ([ProductionRunNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionScheduleBucket_ProductionScheduleBucketCode' AND object_id = OBJECT_ID(N'dim.ProductionScheduleBucket'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionScheduleBucket_ProductionScheduleBucketCode] ON [dim].[ProductionScheduleBucket] ([ProductionScheduleBucketCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionScheduleFamily_ProductionScheduleFamilyCode' AND object_id = OBJECT_ID(N'dim.ProductionScheduleFamily'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionScheduleFamily_ProductionScheduleFamilyCode] ON [dim].[ProductionScheduleFamily] ([ProductionScheduleFamilyCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionScheduleHorizon_ProductionScheduleHorizonCode' AND object_id = OBJECT_ID(N'dim.ProductionScheduleHorizon'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionScheduleHorizon_ProductionScheduleHorizonCode] ON [dim].[ProductionScheduleHorizon] ([ProductionScheduleHorizonCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionScheduleSegment_ProductionScheduleSegmentCode' AND object_id = OBJECT_ID(N'dim.ProductionScheduleSegment'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionScheduleSegment_ProductionScheduleSegmentCode] ON [dim].[ProductionScheduleSegment] ([ProductionScheduleSegmentCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionShift_ProductionShiftCode' AND object_id = OBJECT_ID(N'dim.ProductionShift'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionShift_ProductionShiftCode] ON [dim].[ProductionShift] ([ProductionShiftCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionWorkOrder_WorkOrderNumber' AND object_id = OBJECT_ID(N'dim.ProductionWorkOrder'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionWorkOrder_WorkOrderNumber] ON [dim].[ProductionWorkOrder] ([WorkOrderNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_EndDateKey' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionDowntimeEvent_EndDateKey] ON [fact].[ProductionDowntimeEvent] ([EndDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_EndTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionDowntimeEvent_EndTimeOfDayKey] ON [fact].[ProductionDowntimeEvent] ([EndTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_PlantKey' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionDowntimeEvent_PlantKey] ON [fact].[ProductionDowntimeEvent] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_ProductionDowntimeReasonKey' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionDowntimeEvent_ProductionDowntimeReasonKey] ON [fact].[ProductionDowntimeEvent] ([ProductionDowntimeReasonKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_ProductionRunKey' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionDowntimeEvent_ProductionRunKey] ON [fact].[ProductionDowntimeEvent] ([ProductionRunKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_ProductionShiftKey' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionDowntimeEvent_ProductionShiftKey] ON [fact].[ProductionDowntimeEvent] ([ProductionShiftKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_SeverityKey' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionDowntimeEvent_SeverityKey] ON [fact].[ProductionDowntimeEvent] ([SeverityKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_StartDateKey' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionDowntimeEvent_StartDateKey] ON [fact].[ProductionDowntimeEvent] ([StartDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_StartTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionDowntimeEvent_StartTimeOfDayKey] ON [fact].[ProductionDowntimeEvent] ([StartTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_WorkCenterKey' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionDowntimeEvent_WorkCenterKey] ON [fact].[ProductionDowntimeEvent] ([WorkCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionDowntimeEvent_Columnstore' AND object_id = OBJECT_ID(N'fact.ProductionDowntimeEvent'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_ProductionDowntimeEvent_Columnstore] ON [fact].[ProductionDowntimeEvent];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_ConfirmationDateKey' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_ProductionOperationConfirmation_ConfirmationDateKey] ON [fact].[ProductionOperationConfirmation] ([ConfirmationDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_ConfirmationTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_ProductionOperationConfirmation_ConfirmationTimeOfDayKey] ON [fact].[ProductionOperationConfirmation] ([ConfirmationTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_OperatorEmployeeKey' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_ProductionOperationConfirmation_OperatorEmployeeKey] ON [fact].[ProductionOperationConfirmation] ([OperatorEmployeeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_ProductKey' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_ProductionOperationConfirmation_ProductKey] ON [fact].[ProductionOperationConfirmation] ([ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_ProductionOperationKey' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_ProductionOperationConfirmation_ProductionOperationKey] ON [fact].[ProductionOperationConfirmation] ([ProductionOperationKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_ProductionOrderStatusKey' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_ProductionOperationConfirmation_ProductionOrderStatusKey] ON [fact].[ProductionOperationConfirmation] ([ProductionOrderStatusKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_ProductionShiftKey' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_ProductionOperationConfirmation_ProductionShiftKey] ON [fact].[ProductionOperationConfirmation] ([ProductionShiftKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_ProductionWorkOrderKey' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_ProductionOperationConfirmation_ProductionWorkOrderKey] ON [fact].[ProductionOperationConfirmation] ([ProductionWorkOrderKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_ProductionOperationConfirmation_UnitOfMeasureKey] ON [fact].[ProductionOperationConfirmation] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_WorkCenterKey' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE NONCLUSTERED INDEX [IX_ProductionOperationConfirmation_WorkCenterKey] ON [fact].[ProductionOperationConfirmation] ([WorkCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionOperationConfirmation_Columnstore' AND object_id = OBJECT_ID(N'fact.ProductionOperationConfirmation'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_ProductionOperationConfirmation_Columnstore] ON [fact].[ProductionOperationConfirmation];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_FinishDateKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_FinishDateKey] ON [fact].[ProductionRunYield] ([FinishDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_FinishTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_FinishTimeOfDayKey] ON [fact].[ProductionRunYield] ([FinishTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_PlantKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_PlantKey] ON [fact].[ProductionRunYield] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_ProductKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_ProductKey] ON [fact].[ProductionRunYield] ([ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_ProductionLotKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_ProductionLotKey] ON [fact].[ProductionRunYield] ([ProductionLotKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_ProductionRunKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_ProductionRunKey] ON [fact].[ProductionRunYield] ([ProductionRunKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_ProductionRunTypeKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_ProductionRunTypeKey] ON [fact].[ProductionRunYield] ([ProductionRunTypeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_StartDateKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_StartDateKey] ON [fact].[ProductionRunYield] ([StartDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_StartTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_StartTimeOfDayKey] ON [fact].[ProductionRunYield] ([StartTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_UnitOfMeasureKey] ON [fact].[ProductionRunYield] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_WorkCenterKey' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE NONCLUSTERED INDEX [IX_ProductionRunYield_WorkCenterKey] ON [fact].[ProductionRunYield] ([WorkCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionRunYield_Columnstore' AND object_id = OBJECT_ID(N'fact.ProductionRunYield'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_ProductionRunYield_Columnstore] ON [fact].[ProductionRunYield];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_EventDateKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_EventDateKey] ON [fact].[ProductionScrapReworkEvent] ([EventDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_EventTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_EventTimeOfDayKey] ON [fact].[ProductionScrapReworkEvent] ([EventTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_ProductKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_ProductKey] ON [fact].[ProductionScrapReworkEvent] ([ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_ProductionLotKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_ProductionLotKey] ON [fact].[ProductionScrapReworkEvent] ([ProductionLotKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_ProductionOperationKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_ProductionOperationKey] ON [fact].[ProductionScrapReworkEvent] ([ProductionOperationKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_ProductionReworkReasonKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_ProductionReworkReasonKey] ON [fact].[ProductionScrapReworkEvent] ([ProductionReworkReasonKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_ProductionScrapReasonKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_ProductionScrapReasonKey] ON [fact].[ProductionScrapReworkEvent] ([ProductionScrapReasonKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_ProductionWorkOrderKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_ProductionWorkOrderKey] ON [fact].[ProductionScrapReworkEvent] ([ProductionWorkOrderKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_RecorderEmployeeKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_RecorderEmployeeKey] ON [fact].[ProductionScrapReworkEvent] ([RecorderEmployeeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_SeverityKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_SeverityKey] ON [fact].[ProductionScrapReworkEvent] ([SeverityKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_UnitOfMeasureKey] ON [fact].[ProductionScrapReworkEvent] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_WorkCenterKey' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE NONCLUSTERED INDEX [IX_ProductionScrapReworkEvent_WorkCenterKey] ON [fact].[ProductionScrapReworkEvent] ([WorkCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionScrapReworkEvent_Columnstore' AND object_id = OBJECT_ID(N'fact.ProductionScrapReworkEvent'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_ProductionScrapReworkEvent_Columnstore] ON [fact].[ProductionScrapReworkEvent];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionShiftOutputSnapshot_PlantKey' AND object_id = OBJECT_ID(N'fact.ProductionShiftOutputSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_ProductionShiftOutputSnapshot_PlantKey] ON [fact].[ProductionShiftOutputSnapshot] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionShiftOutputSnapshot_ProductKey' AND object_id = OBJECT_ID(N'fact.ProductionShiftOutputSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_ProductionShiftOutputSnapshot_ProductKey] ON [fact].[ProductionShiftOutputSnapshot] ([ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionShiftOutputSnapshot_ProductionCrewKey' AND object_id = OBJECT_ID(N'fact.ProductionShiftOutputSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_ProductionShiftOutputSnapshot_ProductionCrewKey] ON [fact].[ProductionShiftOutputSnapshot] ([ProductionCrewKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionShiftOutputSnapshot_ProductionShiftKey' AND object_id = OBJECT_ID(N'fact.ProductionShiftOutputSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_ProductionShiftOutputSnapshot_ProductionShiftKey] ON [fact].[ProductionShiftOutputSnapshot] ([ProductionShiftKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionShiftOutputSnapshot_SnapshotDateKey' AND object_id = OBJECT_ID(N'fact.ProductionShiftOutputSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_ProductionShiftOutputSnapshot_SnapshotDateKey] ON [fact].[ProductionShiftOutputSnapshot] ([SnapshotDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionShiftOutputSnapshot_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.ProductionShiftOutputSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_ProductionShiftOutputSnapshot_UnitOfMeasureKey] ON [fact].[ProductionShiftOutputSnapshot] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionShiftOutputSnapshot_WorkCenterKey' AND object_id = OBJECT_ID(N'fact.ProductionShiftOutputSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_ProductionShiftOutputSnapshot_WorkCenterKey] ON [fact].[ProductionShiftOutputSnapshot] ([WorkCenterKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionShiftOutputSnapshot_Columnstore' AND object_id = OBJECT_ID(N'fact.ProductionShiftOutputSnapshot'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_ProductionShiftOutputSnapshot_Columnstore] ON [fact].[ProductionShiftOutputSnapshot];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionWorkOrderLifecycle_ClosedDateKey' AND object_id = OBJECT_ID(N'fact.ProductionWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_ProductionWorkOrderLifecycle_ClosedDateKey] ON [fact].[ProductionWorkOrderLifecycle] ([ClosedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionWorkOrderLifecycle_CompletedDateKey' AND object_id = OBJECT_ID(N'fact.ProductionWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_ProductionWorkOrderLifecycle_CompletedDateKey] ON [fact].[ProductionWorkOrderLifecycle] ([CompletedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionWorkOrderLifecycle_CreatedDateKey' AND object_id = OBJECT_ID(N'fact.ProductionWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_ProductionWorkOrderLifecycle_CreatedDateKey] ON [fact].[ProductionWorkOrderLifecycle] ([CreatedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionWorkOrderLifecycle_PlantKey' AND object_id = OBJECT_ID(N'fact.ProductionWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_ProductionWorkOrderLifecycle_PlantKey] ON [fact].[ProductionWorkOrderLifecycle] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionWorkOrderLifecycle_ProductKey' AND object_id = OBJECT_ID(N'fact.ProductionWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_ProductionWorkOrderLifecycle_ProductKey] ON [fact].[ProductionWorkOrderLifecycle] ([ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionWorkOrderLifecycle_ProductionOrderStatusKey' AND object_id = OBJECT_ID(N'fact.ProductionWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_ProductionWorkOrderLifecycle_ProductionOrderStatusKey] ON [fact].[ProductionWorkOrderLifecycle] ([ProductionOrderStatusKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionWorkOrderLifecycle_ProductionWorkOrderKey' AND object_id = OBJECT_ID(N'fact.ProductionWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_ProductionWorkOrderLifecycle_ProductionWorkOrderKey] ON [fact].[ProductionWorkOrderLifecycle] ([ProductionWorkOrderKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionWorkOrderLifecycle_ReleasedDateKey' AND object_id = OBJECT_ID(N'fact.ProductionWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_ProductionWorkOrderLifecycle_ReleasedDateKey] ON [fact].[ProductionWorkOrderLifecycle] ([ReleasedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionWorkOrderLifecycle_StartedDateKey' AND object_id = OBJECT_ID(N'fact.ProductionWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_ProductionWorkOrderLifecycle_StartedDateKey] ON [fact].[ProductionWorkOrderLifecycle] ([StartedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_ProductionWorkOrderLifecycle_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.ProductionWorkOrderLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_ProductionWorkOrderLifecycle_UnitOfMeasureKey] ON [fact].[ProductionWorkOrderLifecycle] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionDowntimeReason_DowntimeReasonCode' AND object_id = OBJECT_ID(N'ref.ProductionDowntimeReason'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionDowntimeReason_DowntimeReasonCode] ON [ref].[ProductionDowntimeReason] ([DowntimeReasonCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionOrderStatus_OrderStatusCode' AND object_id = OBJECT_ID(N'ref.ProductionOrderStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionOrderStatus_OrderStatusCode] ON [ref].[ProductionOrderStatus] ([OrderStatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionReworkReason_ReworkReasonCode' AND object_id = OBJECT_ID(N'ref.ProductionReworkReason'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionReworkReason_ReworkReasonCode] ON [ref].[ProductionReworkReason] ([ReworkReasonCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionRunType_RunTypeCode' AND object_id = OBJECT_ID(N'ref.ProductionRunType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionRunType_RunTypeCode] ON [ref].[ProductionRunType] ([RunTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionScrapReason_ScrapReasonCode' AND object_id = OBJECT_ID(N'ref.ProductionScrapReason'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionScrapReason_ScrapReasonCode] ON [ref].[ProductionScrapReason] ([ScrapReasonCode]);
GO
