-- Generated by tools.generator. Do not hand-edit.

-- Subject area: reference

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_AdjustmentReason_ReasonCode' AND object_id = OBJECT_ID(N'ref.AdjustmentReason'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_AdjustmentReason_ReasonCode] ON [ref].[AdjustmentReason] ([ReasonCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ApprovalStatus_ApprovalStatusCode' AND object_id = OBJECT_ID(N'ref.ApprovalStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ApprovalStatus_ApprovalStatusCode] ON [ref].[ApprovalStatus] ([ApprovalStatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_AssetStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.AssetStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_AssetStatus_StatusCode] ON [ref].[AssetStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_AssetStatusGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.AssetStatusGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_AssetStatusGroup_GroupCode] ON [ref].[AssetStatusGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_BudgetStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.BudgetStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_BudgetStatus_StatusCode] ON [ref].[BudgetStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_CarrierServiceLevel_ServiceLevelCode' AND object_id = OBJECT_ID(N'ref.CarrierServiceLevel'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_CarrierServiceLevel_ServiceLevelCode] ON [ref].[CarrierServiceLevel] ([ServiceLevelCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ClaimStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.ClaimStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ClaimStatus_StatusCode] ON [ref].[ClaimStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ComplianceStandard_StandardCode' AND object_id = OBJECT_ID(N'ref.ComplianceStandard'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ComplianceStandard_StandardCode] ON [ref].[ComplianceStandard] ([StandardCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_Continent_ContinentCode' AND object_id = OBJECT_ID(N'ref.Continent'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_Continent_ContinentCode] ON [ref].[Continent] ([ContinentCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ContractStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.ContractStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ContractStatus_StatusCode] ON [ref].[ContractStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_CostElementType_CostElementTypeCode' AND object_id = OBJECT_ID(N'ref.CostElementType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_CostElementType_CostElementTypeCode] ON [ref].[CostElementType] ([CostElementTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_Country_CountryCode' AND object_id = OBJECT_ID(N'ref.Country'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_Country_CountryCode] ON [ref].[Country] ([CountryCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_Currency_CurrencyCode' AND object_id = OBJECT_ID(N'ref.Currency'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_Currency_CurrencyCode] ON [ref].[Currency] ([CurrencyCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_CurrencyRegion_RegionCode' AND object_id = OBJECT_ID(N'ref.CurrencyRegion'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_CurrencyRegion_RegionCode] ON [ref].[CurrencyRegion] ([RegionCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_CustomerStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.CustomerStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_CustomerStatus_StatusCode] ON [ref].[CustomerStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_CustomsStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.CustomsStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_CustomsStatus_StatusCode] ON [ref].[CustomsStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_CycleCountStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.CycleCountStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_CycleCountStatus_StatusCode] ON [ref].[CycleCountStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_DefectCategory_CategoryCode' AND object_id = OBJECT_ID(N'ref.DefectCategory'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_DefectCategory_CategoryCode] ON [ref].[DefectCategory] ([CategoryCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_DefectSeverity_DefectSeverityCode' AND object_id = OBJECT_ID(N'ref.DefectSeverity'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_DefectSeverity_DefectSeverityCode] ON [ref].[DefectSeverity] ([DefectSeverityCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_DefectType_DefectTypeCode' AND object_id = OBJECT_ID(N'ref.DefectType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_DefectType_DefectTypeCode] ON [ref].[DefectType] ([DefectTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EmissionScope_EmissionScopeCode' AND object_id = OBJECT_ID(N'ref.EmissionScope'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EmissionScope_EmissionScopeCode] ON [ref].[EmissionScope] ([EmissionScopeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EmploymentType_EmploymentTypeCode' AND object_id = OBJECT_ID(N'ref.EmploymentType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EmploymentType_EmploymentTypeCode] ON [ref].[EmploymentType] ([EmploymentTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_EnergySource_EnergySourceCode' AND object_id = OBJECT_ID(N'ref.EnergySource'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_EnergySource_EnergySourceCode] ON [ref].[EnergySource] ([EnergySourceCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_FailureCause_CauseCode' AND object_id = OBJECT_ID(N'ref.FailureCause'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_FailureCause_CauseCode] ON [ref].[FailureCause] ([CauseCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_FailureCauseGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.FailureCauseGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_FailureCauseGroup_GroupCode] ON [ref].[FailureCauseGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_FailureMode_FailureModeCode' AND object_id = OBJECT_ID(N'ref.FailureMode'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_FailureMode_FailureModeCode] ON [ref].[FailureMode] ([FailureModeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_FailureModeGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.FailureModeGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_FailureModeGroup_GroupCode] ON [ref].[FailureModeGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_FreightClass_FreightClassCode' AND object_id = OBJECT_ID(N'ref.FreightClass'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_FreightClass_FreightClassCode] ON [ref].[FreightClass] ([FreightClassCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_HazardClass_HazardClassCode' AND object_id = OBJECT_ID(N'ref.HazardClass'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_HazardClass_HazardClassCode] ON [ref].[HazardClass] ([HazardClassCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_IncidentCategory_CategoryCode' AND object_id = OBJECT_ID(N'ref.IncidentCategory'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_IncidentCategory_CategoryCode] ON [ref].[IncidentCategory] ([CategoryCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_IncidentSeverityGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.IncidentSeverityGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_IncidentSeverityGroup_GroupCode] ON [ref].[IncidentSeverityGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_IncidentStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.IncidentStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_IncidentStatus_StatusCode] ON [ref].[IncidentStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_IncotermCode_IncotermCode' AND object_id = OBJECT_ID(N'ref.IncotermCode'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_IncotermCode_IncotermCode] ON [ref].[IncotermCode] ([IncotermCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_InspectionMethod_MethodCode' AND object_id = OBJECT_ID(N'ref.InspectionMethod'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_InspectionMethod_MethodCode] ON [ref].[InspectionMethod] ([MethodCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_InspectionResult_ResultCode' AND object_id = OBJECT_ID(N'ref.InspectionResult'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_InspectionResult_ResultCode] ON [ref].[InspectionResult] ([ResultCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_InventoryValuationMethod_MethodCode' AND object_id = OBJECT_ID(N'ref.InventoryValuationMethod'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_InventoryValuationMethod_MethodCode] ON [ref].[InventoryValuationMethod] ([MethodCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_InvoiceStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.InvoiceStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_InvoiceStatus_StatusCode] ON [ref].[InvoiceStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_LaborGrade_LaborGradeCode' AND object_id = OBJECT_ID(N'ref.LaborGrade'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_LaborGrade_LaborGradeCode] ON [ref].[LaborGrade] ([LaborGradeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_Language_LanguageCode' AND object_id = OBJECT_ID(N'ref.Language'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_Language_LanguageCode] ON [ref].[Language] ([LanguageCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_LotStatus_LotStatusCode' AND object_id = OBJECT_ID(N'ref.LotStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_LotStatus_LotStatusCode] ON [ref].[LotStatus] ([LotStatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceStrategy_StrategyCode' AND object_id = OBJECT_ID(N'ref.MaintenanceStrategy'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceStrategy_StrategyCode] ON [ref].[MaintenanceStrategy] ([StrategyCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MaintenanceType_TypeCode' AND object_id = OBJECT_ID(N'ref.MaintenanceType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MaintenanceType_TypeCode] ON [ref].[MaintenanceType] ([TypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MeasurementSystem_MeasurementSystemCode' AND object_id = OBJECT_ID(N'ref.MeasurementSystem'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MeasurementSystem_MeasurementSystemCode] ON [ref].[MeasurementSystem] ([MeasurementSystemCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MeterReadingType_ReadingTypeCode' AND object_id = OBJECT_ID(N'ref.MeterReadingType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MeterReadingType_ReadingTypeCode] ON [ref].[MeterReadingType] ([ReadingTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MovementType_MovementTypeCode' AND object_id = OBJECT_ID(N'ref.MovementType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MovementType_MovementTypeCode] ON [ref].[MovementType] ([MovementTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_MovementTypeGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.MovementTypeGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_MovementTypeGroup_GroupCode] ON [ref].[MovementTypeGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_NonconformanceStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.NonconformanceStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_NonconformanceStatus_StatusCode] ON [ref].[NonconformanceStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_OperationStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.OperationStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_OperationStatus_StatusCode] ON [ref].[OperationStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_OperationStatusGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.OperationStatusGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_OperationStatusGroup_GroupCode] ON [ref].[OperationStatusGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_PackagingType_PackagingTypeCode' AND object_id = OBJECT_ID(N'ref.PackagingType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_PackagingType_PackagingTypeCode] ON [ref].[PackagingType] ([PackagingTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_PaymentStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.PaymentStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_PaymentStatus_StatusCode] ON [ref].[PaymentStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_PaymentTerm_PaymentTermCode' AND object_id = OBJECT_ID(N'ref.PaymentTerm'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_PaymentTerm_PaymentTermCode] ON [ref].[PaymentTerm] ([PaymentTermCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_PermitType_PermitTypeCode' AND object_id = OBJECT_ID(N'ref.PermitType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_PermitType_PermitTypeCode] ON [ref].[PermitType] ([PermitTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_PostingType_PostingTypeCode' AND object_id = OBJECT_ID(N'ref.PostingType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_PostingType_PostingTypeCode] ON [ref].[PostingType] ([PostingTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_PriceListType_TypeCode' AND object_id = OBJECT_ID(N'ref.PriceListType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_PriceListType_TypeCode] ON [ref].[PriceListType] ([TypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_Priority_PriorityCode' AND object_id = OBJECT_ID(N'ref.Priority'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_Priority_PriorityCode] ON [ref].[Priority] ([PriorityCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ProductionMethod_MethodCode' AND object_id = OBJECT_ID(N'ref.ProductionMethod'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ProductionMethod_MethodCode] ON [ref].[ProductionMethod] ([MethodCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_PurchaseOrderStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.PurchaseOrderStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_PurchaseOrderStatus_StatusCode] ON [ref].[PurchaseOrderStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_PurchaseOrderStatusGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.PurchaseOrderStatusGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_PurchaseOrderStatusGroup_GroupCode] ON [ref].[PurchaseOrderStatusGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_RecordStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.RecordStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_RecordStatus_StatusCode] ON [ref].[RecordStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_Region_RegionCode' AND object_id = OBJECT_ID(N'ref.Region'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_Region_RegionCode] ON [ref].[Region] ([RegionCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ReturnReason_ReasonCode' AND object_id = OBJECT_ID(N'ref.ReturnReason'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ReturnReason_ReasonCode] ON [ref].[ReturnReason] ([ReasonCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ReturnReasonGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.ReturnReasonGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ReturnReasonGroup_GroupCode] ON [ref].[ReturnReasonGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_RoutingType_RoutingTypeCode' AND object_id = OBJECT_ID(N'ref.RoutingType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_RoutingType_RoutingTypeCode] ON [ref].[RoutingType] ([RoutingTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_SalesOrderStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.SalesOrderStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_SalesOrderStatus_StatusCode] ON [ref].[SalesOrderStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_SalesOrderStatusGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.SalesOrderStatusGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_SalesOrderStatusGroup_GroupCode] ON [ref].[SalesOrderStatusGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_SampleDisposition_DispositionCode' AND object_id = OBJECT_ID(N'ref.SampleDisposition'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_SampleDisposition_DispositionCode] ON [ref].[SampleDisposition] ([DispositionCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ScheduleStatus_ScheduleStatusCode' AND object_id = OBJECT_ID(N'ref.ScheduleStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ScheduleStatus_ScheduleStatusCode] ON [ref].[ScheduleStatus] ([ScheduleStatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ScrapReason_ReasonCode' AND object_id = OBJECT_ID(N'ref.ScrapReason'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ScrapReason_ReasonCode] ON [ref].[ScrapReason] ([ReasonCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ScrapReasonGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.ScrapReasonGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ScrapReasonGroup_GroupCode] ON [ref].[ScrapReasonGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_Severity_SeverityCode' AND object_id = OBJECT_ID(N'ref.Severity'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_Severity_SeverityCode] ON [ref].[Severity] ([SeverityCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ShiftCode_ShiftCode' AND object_id = OBJECT_ID(N'ref.ShiftCode'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ShiftCode_ShiftCode] ON [ref].[ShiftCode] ([ShiftCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ShipmentStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.ShipmentStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ShipmentStatus_StatusCode] ON [ref].[ShipmentStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ShipmentStatusGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.ShipmentStatusGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ShipmentStatusGroup_GroupCode] ON [ref].[ShipmentStatusGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_SourceSystem_SourceSystemCode' AND object_id = OBJECT_ID(N'ref.SourceSystem'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_SourceSystem_SourceSystemCode] ON [ref].[SourceSystem] ([SourceSystemCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_SourcingStrategy_StrategyCode' AND object_id = OBJECT_ID(N'ref.SourcingStrategy'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_SourcingStrategy_StrategyCode] ON [ref].[SourcingStrategy] ([StrategyCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_StockStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.StockStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_StockStatus_StatusCode] ON [ref].[StockStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_StockStatusGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.StockStatusGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_StockStatusGroup_GroupCode] ON [ref].[StockStatusGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_SupplierQualificationStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.SupplierQualificationStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_SupplierQualificationStatus_StatusCode] ON [ref].[SupplierQualificationStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_TaxCode_TaxCode' AND object_id = OBJECT_ID(N'ref.TaxCode'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_TaxCode_TaxCode] ON [ref].[TaxCode] ([TaxCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_TimeZone_TimeZoneCode' AND object_id = OBJECT_ID(N'ref.TimeZone'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_TimeZone_TimeZoneCode] ON [ref].[TimeZone] ([TimeZoneCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_TrainingStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.TrainingStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_TrainingStatus_StatusCode] ON [ref].[TrainingStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_TransactionType_TransactionTypeCode' AND object_id = OBJECT_ID(N'ref.TransactionType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_TransactionType_TransactionTypeCode] ON [ref].[TransactionType] ([TransactionTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_TransportMode_TransportModeCode' AND object_id = OBJECT_ID(N'ref.TransportMode'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_TransportMode_TransportModeCode] ON [ref].[TransportMode] ([TransportModeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_UnitOfMeasure_UomCode' AND object_id = OBJECT_ID(N'ref.UnitOfMeasure'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_UnitOfMeasure_UomCode] ON [ref].[UnitOfMeasure] ([UomCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_UnitOfMeasureClass_ClassCode' AND object_id = OBJECT_ID(N'ref.UnitOfMeasureClass'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_UnitOfMeasureClass_ClassCode] ON [ref].[UnitOfMeasureClass] ([ClassCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarehouseZoneType_ZoneTypeCode' AND object_id = OBJECT_ID(N'ref.WarehouseZoneType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarehouseZoneType_ZoneTypeCode] ON [ref].[WarehouseZoneType] ([ZoneTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyDisposition_DispositionCode' AND object_id = OBJECT_ID(N'ref.WarrantyDisposition'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyDisposition_DispositionCode] ON [ref].[WarrantyDisposition] ([DispositionCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WasteType_WasteTypeCode' AND object_id = OBJECT_ID(N'ref.WasteType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WasteType_WasteTypeCode] ON [ref].[WasteType] ([WasteTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WorkOrderStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.WorkOrderStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WorkOrderStatus_StatusCode] ON [ref].[WorkOrderStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WorkOrderStatusGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.WorkOrderStatusGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WorkOrderStatusGroup_GroupCode] ON [ref].[WorkOrderStatusGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WorkOrderType_TypeCode' AND object_id = OBJECT_ID(N'ref.WorkOrderType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WorkOrderType_TypeCode] ON [ref].[WorkOrderType] ([TypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WorkOrderTypeGroup_GroupCode' AND object_id = OBJECT_ID(N'ref.WorkOrderTypeGroup'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WorkOrderTypeGroup_GroupCode] ON [ref].[WorkOrderTypeGroup] ([GroupCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WorkRequestStatus_StatusCode' AND object_id = OBJECT_ID(N'ref.WorkRequestStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WorkRequestStatus_StatusCode] ON [ref].[WorkRequestStatus] ([StatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_YesNoFlag_FlagCode' AND object_id = OBJECT_ID(N'ref.YesNoFlag'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_YesNoFlag_FlagCode] ON [ref].[YesNoFlag] ([FlagCode]);
GO
