-- Generated by tools.generator. Do not hand-edit.

-- Subject area: warranty_service

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceContractProduct_ServiceContractKeyProductKey' AND object_id = OBJECT_ID(N'bridge.ServiceContractProduct'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceContractProduct_ServiceContractKeyProductKey] ON [bridge].[ServiceContractProduct] ([ServiceContractKey], [ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceOrderPart_ServiceRepairCodeKeyProductKey' AND object_id = OBJECT_ID(N'bridge.ServiceOrderPart'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceOrderPart_ServiceRepairCodeKeyProductKey] ON [bridge].[ServiceOrderPart] ([ServiceRepairCodeKey], [ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyClaimRepairCode_WarrantyFailureModeKeyServiceRepairCodeKey' AND object_id = OBJECT_ID(N'bridge.WarrantyClaimRepairCode'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyClaimRepairCode_WarrantyFailureModeKeyServiceRepairCodeKey] ON [bridge].[WarrantyClaimRepairCode] ([WarrantyFailureModeKey], [ServiceRepairCodeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceCampaign_ServiceCampaignCode' AND object_id = OBJECT_ID(N'dim.ServiceCampaign'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceCampaign_ServiceCampaignCode] ON [dim].[ServiceCampaign] ([ServiceCampaignCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceCampaignPortfolio_ServiceCampaignPortfolioCode' AND object_id = OBJECT_ID(N'dim.ServiceCampaignPortfolio'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceCampaignPortfolio_ServiceCampaignPortfolioCode] ON [dim].[ServiceCampaignPortfolio] ([ServiceCampaignPortfolioCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceCampaignProgram_ServiceCampaignProgramCode' AND object_id = OBJECT_ID(N'dim.ServiceCampaignProgram'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceCampaignProgram_ServiceCampaignProgramCode] ON [dim].[ServiceCampaignProgram] ([ServiceCampaignProgramCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceContract_ServiceContractNumber' AND object_id = OBJECT_ID(N'dim.ServiceContract'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceContract_ServiceContractNumber] ON [dim].[ServiceContract] ([ServiceContractNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceGeoBranch_ServiceGeoBranchCode' AND object_id = OBJECT_ID(N'dim.ServiceGeoBranch'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceGeoBranch_ServiceGeoBranchCode] ON [dim].[ServiceGeoBranch] ([ServiceGeoBranchCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceGeoDistrict_ServiceGeoDistrictCode' AND object_id = OBJECT_ID(N'dim.ServiceGeoDistrict'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceGeoDistrict_ServiceGeoDistrictCode] ON [dim].[ServiceGeoDistrict] ([ServiceGeoDistrictCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceGeoRegion_ServiceGeoRegionCode' AND object_id = OBJECT_ID(N'dim.ServiceGeoRegion'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceGeoRegion_ServiceGeoRegionCode] ON [dim].[ServiceGeoRegion] ([ServiceGeoRegionCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServicePartDisposition_ServicePartDispositionCode' AND object_id = OBJECT_ID(N'dim.ServicePartDisposition'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServicePartDisposition_ServicePartDispositionCode] ON [dim].[ServicePartDisposition] ([ServicePartDispositionCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceRecallActivity_ServiceRecallActivityCode' AND object_id = OBJECT_ID(N'dim.ServiceRecallActivity'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceRecallActivity_ServiceRecallActivityCode] ON [dim].[ServiceRecallActivity] ([ServiceRecallActivityCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceRepairAction_ServiceRepairActionCode' AND object_id = OBJECT_ID(N'dim.ServiceRepairAction'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceRepairAction_ServiceRepairActionCode] ON [dim].[ServiceRepairAction] ([ServiceRepairActionCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceRepairCategory_ServiceRepairCategoryCode' AND object_id = OBJECT_ID(N'dim.ServiceRepairCategory'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceRepairCategory_ServiceRepairCategoryCode] ON [dim].[ServiceRepairCategory] ([ServiceRepairCategoryCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceRepairCode_ServiceRepairCodeCode' AND object_id = OBJECT_ID(N'dim.ServiceRepairCode'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceRepairCode_ServiceRepairCodeCode] ON [dim].[ServiceRepairCode] ([ServiceRepairCodeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceRepairSubcategory_ServiceRepairSubcategoryCode' AND object_id = OBJECT_ID(N'dim.ServiceRepairSubcategory'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceRepairSubcategory_ServiceRepairSubcategoryCode] ON [dim].[ServiceRepairSubcategory] ([ServiceRepairSubcategoryCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceTechnicianProfile_TechnicianProfileNumber' AND object_id = OBJECT_ID(N'dim.ServiceTechnicianProfile'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceTechnicianProfile_TechnicianProfileNumber] ON [dim].[ServiceTechnicianProfile] ([TechnicianProfileNumber]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceTerritory_ServiceTerritoryCode' AND object_id = OBJECT_ID(N'dim.ServiceTerritory'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceTerritory_ServiceTerritoryCode] ON [dim].[ServiceTerritory] ([ServiceTerritoryCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyClaimChannel_ClaimChannelCode' AND object_id = OBJECT_ID(N'dim.WarrantyClaimChannel'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyClaimChannel_ClaimChannelCode] ON [dim].[WarrantyClaimChannel] ([ClaimChannelCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyComplaintType_ComplaintTypeCode' AND object_id = OBJECT_ID(N'dim.WarrantyComplaintType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyComplaintType_ComplaintTypeCode] ON [dim].[WarrantyComplaintType] ([ComplaintTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyCoverageFamily_WarrantyCoverageFamilyCode' AND object_id = OBJECT_ID(N'dim.WarrantyCoverageFamily'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyCoverageFamily_WarrantyCoverageFamilyCode] ON [dim].[WarrantyCoverageFamily] ([WarrantyCoverageFamilyCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyCoverageProgram_WarrantyCoverageProgramCode' AND object_id = OBJECT_ID(N'dim.WarrantyCoverageProgram'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyCoverageProgram_WarrantyCoverageProgramCode] ON [dim].[WarrantyCoverageProgram] ([WarrantyCoverageProgramCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyFailureMode_FailureModeCode' AND object_id = OBJECT_ID(N'dim.WarrantyFailureMode'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyFailureMode_FailureModeCode] ON [dim].[WarrantyFailureMode] ([FailureModeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyPolicy_WarrantyPolicyCode' AND object_id = OBJECT_ID(N'dim.WarrantyPolicy'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyPolicy_WarrantyPolicyCode] ON [dim].[WarrantyPolicy] ([WarrantyPolicyCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyTerm_WarrantyTermCode' AND object_id = OBJECT_ID(N'dim.WarrantyTerm'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyTerm_WarrantyTermCode] ON [dim].[WarrantyTerm] ([WarrantyTermCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_ClosedDateKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_ClosedDateKey] ON [fact].[FieldServiceOrderTransaction] ([ClosedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_CompletedDateKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_CompletedDateKey] ON [fact].[FieldServiceOrderTransaction] ([CompletedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_CompletedTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_CompletedTimeOfDayKey] ON [fact].[FieldServiceOrderTransaction] ([CompletedTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_CurrencyKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_CurrencyKey] ON [fact].[FieldServiceOrderTransaction] ([CurrencyKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_CustomerKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_CustomerKey] ON [fact].[FieldServiceOrderTransaction] ([CustomerKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_DispatchedDateKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_DispatchedDateKey] ON [fact].[FieldServiceOrderTransaction] ([DispatchedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_DispatchedTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_DispatchedTimeOfDayKey] ON [fact].[FieldServiceOrderTransaction] ([DispatchedTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_OpenedDateKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_OpenedDateKey] ON [fact].[FieldServiceOrderTransaction] ([OpenedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_PriorityKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_PriorityKey] ON [fact].[FieldServiceOrderTransaction] ([PriorityKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_ProductKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_ProductKey] ON [fact].[FieldServiceOrderTransaction] ([ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_ScheduledDateKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_ScheduledDateKey] ON [fact].[FieldServiceOrderTransaction] ([ScheduledDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_ScheduledTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_ScheduledTimeOfDayKey] ON [fact].[FieldServiceOrderTransaction] ([ScheduledTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_ServiceContractKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_ServiceContractKey] ON [fact].[FieldServiceOrderTransaction] ([ServiceContractKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_ServiceOrderStatusKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_ServiceOrderStatusKey] ON [fact].[FieldServiceOrderTransaction] ([ServiceOrderStatusKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_ServiceRepairCodeKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_ServiceRepairCodeKey] ON [fact].[FieldServiceOrderTransaction] ([ServiceRepairCodeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_ServiceTechnicianProfileKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_ServiceTechnicianProfileKey] ON [fact].[FieldServiceOrderTransaction] ([ServiceTechnicianProfileKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_ServiceTerritoryKey' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE NONCLUSTERED INDEX [IX_FieldServiceOrderTransaction_ServiceTerritoryKey] ON [fact].[FieldServiceOrderTransaction] ([ServiceTerritoryKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_FieldServiceOrderTransaction_Columnstore' AND object_id = OBJECT_ID(N'fact.FieldServiceOrderTransaction'))
    CREATE CLUSTERED COLUMNSTORE INDEX [IX_FieldServiceOrderTransaction_Columnstore] ON [fact].[FieldServiceOrderTransaction];
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_ApprovedDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_ApprovedDateKey] ON [fact].[WarrantyClaimLifecycle] ([ApprovedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_ClaimDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_ClaimDateKey] ON [fact].[WarrantyClaimLifecycle] ([ClaimDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_ClosedDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_ClosedDateKey] ON [fact].[WarrantyClaimLifecycle] ([ClosedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_CurrencyKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_CurrencyKey] ON [fact].[WarrantyClaimLifecycle] ([CurrencyKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_CustomerKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_CustomerKey] ON [fact].[WarrantyClaimLifecycle] ([CustomerKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_FailureDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_FailureDateKey] ON [fact].[WarrantyClaimLifecycle] ([FailureDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_PaidDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_PaidDateKey] ON [fact].[WarrantyClaimLifecycle] ([PaidDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_PlantKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_PlantKey] ON [fact].[WarrantyClaimLifecycle] ([PlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_ProductKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_ProductKey] ON [fact].[WarrantyClaimLifecycle] ([ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_ServiceTerritoryKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_ServiceTerritoryKey] ON [fact].[WarrantyClaimLifecycle] ([ServiceTerritoryKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_SeverityKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_SeverityKey] ON [fact].[WarrantyClaimLifecycle] ([SeverityKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_WarrantyClaimChannelKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_WarrantyClaimChannelKey] ON [fact].[WarrantyClaimLifecycle] ([WarrantyClaimChannelKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_WarrantyClaimStatusKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_WarrantyClaimStatusKey] ON [fact].[WarrantyClaimLifecycle] ([WarrantyClaimStatusKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_WarrantyFailureModeKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_WarrantyFailureModeKey] ON [fact].[WarrantyClaimLifecycle] ([WarrantyFailureModeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyClaimLifecycle_WarrantyTermKey' AND object_id = OBJECT_ID(N'fact.WarrantyClaimLifecycle'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyClaimLifecycle_WarrantyTermKey] ON [fact].[WarrantyClaimLifecycle] ([WarrantyTermKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_ComplaintDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_ComplaintDateKey] ON [fact].[WarrantyCustomerComplaint] ([ComplaintDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_ComplaintTimeOfDayKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_ComplaintTimeOfDayKey] ON [fact].[WarrantyCustomerComplaint] ([ComplaintTimeOfDayKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_CustomerKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_CustomerKey] ON [fact].[WarrantyCustomerComplaint] ([CustomerKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_PriorityKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_PriorityKey] ON [fact].[WarrantyCustomerComplaint] ([PriorityKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_ProductKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_ProductKey] ON [fact].[WarrantyCustomerComplaint] ([ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_ResolvedDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_ResolvedDateKey] ON [fact].[WarrantyCustomerComplaint] ([ResolvedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_ResponseDueDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_ResponseDueDateKey] ON [fact].[WarrantyCustomerComplaint] ([ResponseDueDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_ServiceTerritoryKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_ServiceTerritoryKey] ON [fact].[WarrantyCustomerComplaint] ([ServiceTerritoryKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_SeverityKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_SeverityKey] ON [fact].[WarrantyCustomerComplaint] ([SeverityKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_WarrantyClaimChannelKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_WarrantyClaimChannelKey] ON [fact].[WarrantyCustomerComplaint] ([WarrantyClaimChannelKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyCustomerComplaint_WarrantyComplaintTypeKey' AND object_id = OBJECT_ID(N'fact.WarrantyCustomerComplaint'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyCustomerComplaint_WarrantyComplaintTypeKey] ON [fact].[WarrantyCustomerComplaint] ([WarrantyComplaintTypeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_AuthorizedDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_AuthorizedDateKey] ON [fact].[WarrantyRmaTransaction] ([AuthorizedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_CurrencyKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_CurrencyKey] ON [fact].[WarrantyRmaTransaction] ([CurrencyKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_CustomerKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_CustomerKey] ON [fact].[WarrantyRmaTransaction] ([CustomerKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_DispositionDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_DispositionDateKey] ON [fact].[WarrantyRmaTransaction] ([DispositionDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_ProductKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_ProductKey] ON [fact].[WarrantyRmaTransaction] ([ProductKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_ReceivedDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_ReceivedDateKey] ON [fact].[WarrantyRmaTransaction] ([ReceivedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_ReceivingPlantKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_ReceivingPlantKey] ON [fact].[WarrantyRmaTransaction] ([ReceivingPlantKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_ServicePartDispositionKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_ServicePartDispositionKey] ON [fact].[WarrantyRmaTransaction] ([ServicePartDispositionKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_ShippedDateKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_ShippedDateKey] ON [fact].[WarrantyRmaTransaction] ([ShippedDateKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_UnitOfMeasureKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_UnitOfMeasureKey] ON [fact].[WarrantyRmaTransaction] ([UnitOfMeasureKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_WarrantyFailureModeKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_WarrantyFailureModeKey] ON [fact].[WarrantyRmaTransaction] ([WarrantyFailureModeKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_WarrantyRmaTransaction_WarrantyRmaStatusKey' AND object_id = OBJECT_ID(N'fact.WarrantyRmaTransaction'))
    CREATE NONCLUSTERED INDEX [IX_WarrantyRmaTransaction_WarrantyRmaStatusKey] ON [fact].[WarrantyRmaTransaction] ([WarrantyRmaStatusKey]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceContractStatus_ServiceContractStatusCode' AND object_id = OBJECT_ID(N'ref.ServiceContractStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceContractStatus_ServiceContractStatusCode] ON [ref].[ServiceContractStatus] ([ServiceContractStatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_ServiceOrderStatus_ServiceOrderStatusCode' AND object_id = OBJECT_ID(N'ref.ServiceOrderStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ServiceOrderStatus_ServiceOrderStatusCode] ON [ref].[ServiceOrderStatus] ([ServiceOrderStatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyClaimStatus_WarrantyClaimStatusCode' AND object_id = OBJECT_ID(N'ref.WarrantyClaimStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyClaimStatus_WarrantyClaimStatusCode] ON [ref].[WarrantyClaimStatus] ([WarrantyClaimStatusCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyPolicyType_WarrantyPolicyTypeCode' AND object_id = OBJECT_ID(N'ref.WarrantyPolicyType'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyPolicyType_WarrantyPolicyTypeCode] ON [ref].[WarrantyPolicyType] ([WarrantyPolicyTypeCode]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_WarrantyRmaStatus_WarrantyRmaStatusCode' AND object_id = OBJECT_ID(N'ref.WarrantyRmaStatus'))
    CREATE UNIQUE NONCLUSTERED INDEX [UX_WarrantyRmaStatus_WarrantyRmaStatusCode] ON [ref].[WarrantyRmaStatus] ([WarrantyRmaStatusCode]);
GO
