-- Generated by tools.generator. Do not hand-edit.

-- Subject area: ehs_compliance

IF OBJECT_ID(N'fact.SafetyAuditFinding', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[SafetyAuditFinding] (
    [SafetyAuditFindingKey] BIGINT IDENTITY(1,1) NOT NULL,
    [AuditDateKey] INT NOT NULL DEFAULT -1,
    [FindingDateKey] INT NOT NULL DEFAULT -1,
    [DueDateKey] INT NOT NULL DEFAULT -1,
    [VerifiedDateKey] INT NOT NULL DEFAULT -1,
    [ClosedDateKey] INT NOT NULL DEFAULT -1,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [WorkCenterKey] INT NULL DEFAULT -1,
    [AuditorEmployeeKey] INT NULL DEFAULT -1,
    [SafetyAuditChecklistItemKey] INT NOT NULL DEFAULT -1,
    [SafetyCorrectiveActionTypeKey] INT NOT NULL DEFAULT -1,
    [SafetyObligationKey] INT NULL DEFAULT -1,
    [SafetyAuditFindingStatusKey] INT NOT NULL DEFAULT -1,
    [PriorityKey] INT NOT NULL DEFAULT -1,
    [ComplianceStandardKey] INT NOT NULL DEFAULT -1,
    [AuditNumber] NVARCHAR(40) NOT NULL,
    [FindingNumber] NVARCHAR(40) NOT NULL,
    [FindingCount] INT NOT NULL,
    [CorrectiveActionCostAmount] MONEY NULL,
    [SafetyAuditFindingLagDays] INT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_SafetyAuditFinding] PRIMARY KEY CLUSTERED ([SafetyAuditFindingKey])
);
END
GO

IF OBJECT_ID(N'fact.SafetyIncident', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[SafetyIncident] (
    [SafetyIncidentKey] BIGINT IDENTITY(1,1) NOT NULL,
    [OccurredDateKey] INT NOT NULL DEFAULT -1,
    [ReportedDateKey] INT NOT NULL DEFAULT -1,
    [ClosedDateKey] INT NOT NULL DEFAULT -1,
    [OccurredTimeOfDayKey] INT NOT NULL DEFAULT -1,
    [ReportedTimeOfDayKey] INT NOT NULL DEFAULT -1,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [SiteKey] INT NULL DEFAULT -1,
    [WorkCenterKey] INT NULL DEFAULT -1,
    [InjuredEmployeeKey] INT NULL DEFAULT -1,
    [SupervisorEmployeeKey] INT NULL DEFAULT -1,
    [SafetyIncidentTypeKey] INT NOT NULL DEFAULT -1,
    [SafetyHazardConditionKey] INT NULL DEFAULT -1,
    [SafetyIncidentStatusKey] INT NOT NULL DEFAULT -1,
    [SafetyInjuryClassificationKey] INT NOT NULL DEFAULT -1,
    [SeverityKey] INT NOT NULL DEFAULT -1,
    [SafetyIncidentNumber] NVARCHAR(40) NOT NULL,
    [InjuredPersonCount] INT NOT NULL,
    [LostWorkdayCount] DECIMAL(18,4) NOT NULL,
    [EstimatedCostAmount] MONEY NULL,
    [SafetyIncidentLagDays] INT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_SafetyIncident] PRIMARY KEY CLUSTERED ([SafetyIncidentKey])
);
END
GO

IF OBJECT_ID(N'fact.SafetyNearMiss', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[SafetyNearMiss] (
    [SafetyNearMissKey] BIGINT IDENTITY(1,1) NOT NULL,
    [ObservedDateKey] INT NOT NULL DEFAULT -1,
    [SubmittedDateKey] INT NOT NULL DEFAULT -1,
    [ObservedTimeOfDayKey] INT NOT NULL DEFAULT -1,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [WorkCenterKey] INT NULL DEFAULT -1,
    [ReporterEmployeeKey] INT NULL DEFAULT -1,
    [SafetyIncidentTypeKey] INT NOT NULL DEFAULT -1,
    [SafetyHazardConditionKey] INT NOT NULL DEFAULT -1,
    [SafetyIncidentStatusKey] INT NOT NULL DEFAULT -1,
    [SeverityKey] INT NOT NULL DEFAULT -1,
    [NearMissNumber] NVARCHAR(40) NOT NULL,
    [ObservationCount] INT NOT NULL,
    [PotentialRiskScore] DECIMAL(9,2) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_SafetyNearMiss] PRIMARY KEY CLUSTERED ([SafetyNearMissKey])
);
END
GO

IF OBJECT_ID(N'fact.SafetyWasteShipment', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[SafetyWasteShipment] (
    [SafetyWasteShipmentKey] BIGINT IDENTITY(1,1) NOT NULL,
    [ShipmentDateKey] INT NOT NULL DEFAULT -1,
    [DisposalDateKey] INT NOT NULL DEFAULT -1,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [HaulerSupplierKey] INT NULL DEFAULT -1,
    [DisposalFacilitySupplierKey] INT NULL DEFAULT -1,
    [SafetyWasteStreamKey] INT NOT NULL DEFAULT -1,
    [SafetyWasteDispositionMethodKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [WasteManifestNumber] NVARCHAR(50) NOT NULL,
    [WasteShipmentLineNumber] INT NOT NULL,
    [WasteQuantity] DECIMAL(18,4) NOT NULL,
    [DisposalCostAmount] MONEY NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_SafetyWasteShipment] PRIMARY KEY CLUSTERED ([SafetyWasteShipmentKey])
);
END
GO
