-- Generated by tools.generator. Do not hand-edit.

-- Subject area: quality

IF OBJECT_ID(N'fact.QualityCapaLifecycle', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[QualityCapaLifecycle] (
    [QualityCapaLifecycleKey] BIGINT IDENTITY(1,1) NOT NULL,
    [OpenedDateKey] INT NOT NULL DEFAULT -1,
    [ApprovedDateKey] INT NOT NULL DEFAULT -1,
    [ImplementedDateKey] INT NOT NULL DEFAULT -1,
    [VerifiedDateKey] INT NOT NULL DEFAULT -1,
    [ClosedDateKey] INT NOT NULL DEFAULT -1,
    [QualityNonConformanceKey] INT NULL DEFAULT -1,
    [ProductKey] INT NULL DEFAULT -1,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [OwnerEmployeeKey] INT NULL DEFAULT -1,
    [QualityCapaTypeKey] INT NOT NULL DEFAULT -1,
    [ApprovalStatusKey] INT NOT NULL DEFAULT -1,
    [QualityResultStatusKey] INT NOT NULL DEFAULT -1,
    [CapaNumber] NVARCHAR(40) NOT NULL,
    [EventCount] INT NOT NULL,
    [QuantityAmount] DECIMAL(18,4) NULL,
    [DurationMinutes] DECIMAL(18,4) NULL,
    [CostAmount] MONEY NULL,
    [QualityCapaLifecycleLagDays] INT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_QualityCapaLifecycle] PRIMARY KEY CLUSTERED ([QualityCapaLifecycleKey])
);
END
GO

IF OBJECT_ID(N'fact.QualityGaugeCalibration', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[QualityGaugeCalibration] (
    [QualityGaugeCalibrationKey] BIGINT IDENTITY(1,1) NOT NULL,
    [CalibrationDateKey] INT NOT NULL DEFAULT -1,
    [DueDateKey] INT NOT NULL DEFAULT -1,
    [QualityGaugeKey] INT NOT NULL DEFAULT -1,
    [AssetKey] INT NULL DEFAULT -1,
    [TechnicianEmployeeKey] INT NULL DEFAULT -1,
    [QualityLabCellKey] INT NOT NULL DEFAULT -1,
    [QualityCalibrationStatusKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [CalibrationCertificateNumber] NVARCHAR(50) NOT NULL,
    [EventCount] INT NOT NULL,
    [QuantityAmount] DECIMAL(18,4) NULL,
    [DurationMinutes] DECIMAL(18,4) NULL,
    [CostAmount] MONEY NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_QualityGaugeCalibration] PRIMARY KEY CLUSTERED ([QualityGaugeCalibrationKey])
);
END
GO

IF OBJECT_ID(N'fact.QualityInspectionResult', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[QualityInspectionResult] (
    [QualityInspectionResultKey] BIGINT IDENTITY(1,1) NOT NULL,
    [InspectionDateKey] INT NOT NULL DEFAULT -1,
    [InspectionTimeOfDayKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionLotKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionPlanKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionCharacteristicKey] INT NOT NULL DEFAULT -1,
    [QualityGaugeKey] INT NULL DEFAULT -1,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [SupplierKey] INT NULL DEFAULT -1,
    [InspectorEmployeeKey] INT NULL DEFAULT -1,
    [QualityInspectionTypeKey] INT NOT NULL DEFAULT -1,
    [QualityResultStatusKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [SampleNumber] NVARCHAR(40) NOT NULL,
    [ResultSequenceNumber] INT NOT NULL,
    [EventCount] INT NOT NULL,
    [QuantityAmount] DECIMAL(18,4) NULL,
    [DurationMinutes] DECIMAL(18,4) NULL,
    [CostAmount] MONEY NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_QualityInspectionResult] PRIMARY KEY NONCLUSTERED ([QualityInspectionResultKey])
);
END
GO

IF OBJECT_ID(N'fact.QualityNonConformanceEvent', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[QualityNonConformanceEvent] (
    [QualityNonConformanceEventKey] BIGINT IDENTITY(1,1) NOT NULL,
    [EventDateKey] INT NOT NULL DEFAULT -1,
    [EventTimeOfDayKey] INT NOT NULL DEFAULT -1,
    [QualityNonConformanceKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NULL DEFAULT -1,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [SupplierKey] INT NULL DEFAULT -1,
    [OwnerEmployeeKey] INT NULL DEFAULT -1,
    [QualityDefectSeverityKey] INT NOT NULL DEFAULT -1,
    [QualityResultStatusKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [NonConformanceEventNumber] NVARCHAR(40) NOT NULL,
    [EventCount] INT NOT NULL,
    [QuantityAmount] DECIMAL(18,4) NULL,
    [DurationMinutes] DECIMAL(18,4) NULL,
    [CostAmount] MONEY NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_QualityNonConformanceEvent] PRIMARY KEY NONCLUSTERED ([QualityNonConformanceEventKey])
);
END
GO

IF OBJECT_ID(N'fact.QualitySpcSample', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[QualitySpcSample] (
    [QualitySpcSampleKey] BIGINT IDENTITY(1,1) NOT NULL,
    [SampleDateKey] INT NOT NULL DEFAULT -1,
    [SampleTimeOfDayKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionCharacteristicKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [WorkCenterKey] INT NOT NULL DEFAULT -1,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [QualityResultStatusKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [ControlChartNumber] NVARCHAR(40) NOT NULL,
    [SubgroupNumber] INT NOT NULL,
    [EventCount] INT NOT NULL,
    [QuantityAmount] DECIMAL(18,4) NULL,
    [DurationMinutes] DECIMAL(18,4) NULL,
    [CostAmount] MONEY NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_QualitySpcSample] PRIMARY KEY NONCLUSTERED ([QualitySpcSampleKey])
);
END
GO
