-- Generated by tools.generator. Do not hand-edit.

-- Subject area: sales_fulfillment

IF OBJECT_ID(N'fact.SalesBackorderSnapshot', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[SalesBackorderSnapshot] (
    [SalesBackorderSnapshotKey] BIGINT IDENTITY(1,1) NOT NULL,
    [SnapshotDateKey] INT NOT NULL DEFAULT -1,
    [RequestedDeliveryDateKey] INT NOT NULL DEFAULT -1,
    [SalesOrderLineKey] INT NOT NULL DEFAULT -1,
    [CustomerKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [FulfillmentPlantKey] INT NOT NULL DEFAULT -1,
    [SalesBackorderReasonKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [CurrencyKey] INT NOT NULL DEFAULT -1,
    [BackorderQuantity] DECIMAL(18,4) NOT NULL,
    [BackorderAmount] MONEY NOT NULL,
    [BackorderAgeDays] INT NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_SalesBackorderSnapshot] PRIMARY KEY CLUSTERED ([SalesBackorderSnapshotKey])
);
END
GO

IF OBJECT_ID(N'fact.SalesCreditExposureSnapshot', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[SalesCreditExposureSnapshot] (
    [SalesCreditExposureSnapshotKey] BIGINT IDENTITY(1,1) NOT NULL,
    [SnapshotDateKey] INT NOT NULL DEFAULT -1,
    [CustomerKey] INT NOT NULL DEFAULT -1,
    [BusinessUnitKey] INT NULL DEFAULT -1,
    [SalesCustomerCreditProfileKey] INT NOT NULL DEFAULT -1,
    [SalesCreditStatusKey] INT NOT NULL DEFAULT -1,
    [CurrencyKey] INT NOT NULL DEFAULT -1,
    [CreditLimitAmount] MONEY NOT NULL,
    [OpenOrderAmount] MONEY NOT NULL,
    [ReceivableAmount] MONEY NOT NULL,
    [AvailableCreditAmount] MONEY NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_SalesCreditExposureSnapshot] PRIMARY KEY CLUSTERED ([SalesCreditExposureSnapshotKey])
);
END
GO

IF OBJECT_ID(N'fact.SalesFulfillmentCycle', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[SalesFulfillmentCycle] (
    [SalesFulfillmentCycleKey] BIGINT IDENTITY(1,1) NOT NULL,
    [OrderDateKey] INT NOT NULL DEFAULT -1,
    [AllocationDateKey] INT NOT NULL DEFAULT -1,
    [PickDateKey] INT NOT NULL DEFAULT -1,
    [PackDateKey] INT NOT NULL DEFAULT -1,
    [ShipDateKey] INT NOT NULL DEFAULT -1,
    [DeliveryDateKey] INT NOT NULL DEFAULT -1,
    [InvoiceDateKey] INT NOT NULL DEFAULT -1,
    [SalesOrderHeaderKey] INT NOT NULL DEFAULT -1,
    [SalesOrderLineKey] INT NOT NULL DEFAULT -1,
    [CustomerKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [FulfillmentPlantKey] INT NOT NULL DEFAULT -1,
    [SalesOrderLifecycleStatusKey] INT NOT NULL DEFAULT -1,
    [SalesAllocationStatusKey] INT NOT NULL DEFAULT -1,
    [CurrencyKey] INT NOT NULL DEFAULT -1,
    [OrderedQuantity] DECIMAL(18,4) NOT NULL,
    [ShippedQuantity] DECIMAL(18,4) NOT NULL,
    [InvoicedQuantity] DECIMAL(18,4) NOT NULL,
    [InvoicedAmount] MONEY NOT NULL,
    [SalesFulfillmentCycleLagDays] INT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_SalesFulfillmentCycle] PRIMARY KEY CLUSTERED ([SalesFulfillmentCycleKey])
);
END
GO

IF OBJECT_ID(N'fact.SalesOrderAllocation', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[SalesOrderAllocation] (
    [SalesOrderAllocationKey] BIGINT IDENTITY(1,1) NOT NULL,
    [AllocationDateKey] INT NOT NULL DEFAULT -1,
    [PromiseShipDateKey] INT NOT NULL DEFAULT -1,
    [AllocationTimeOfDayKey] INT NOT NULL DEFAULT -1,
    [SalesOrderLineKey] INT NOT NULL DEFAULT -1,
    [SalesFulfillmentPromiseKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [FulfillmentPlantKey] INT NOT NULL DEFAULT -1,
    [SalesAllocationStatusKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [AllocationDocumentNumber] NVARCHAR(40) NOT NULL,
    [RequestedQuantity] DECIMAL(18,4) NOT NULL,
    [AllocatedQuantity] DECIMAL(18,4) NOT NULL,
    [UnallocatedQuantity] DECIMAL(18,4) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_SalesOrderAllocation] PRIMARY KEY CLUSTERED ([SalesOrderAllocationKey])
);
END
GO

IF OBJECT_ID(N'fact.SalesOrderBooking', N'U') IS NULL
BEGIN
CREATE TABLE [fact].[SalesOrderBooking] (
    [SalesOrderBookingKey] BIGINT IDENTITY(1,1) NOT NULL,
    [OrderDateKey] INT NOT NULL DEFAULT -1,
    [RequestedShipDateKey] INT NOT NULL DEFAULT -1,
    [RequestedDeliveryDateKey] INT NOT NULL DEFAULT -1,
    [OrderTimeOfDayKey] INT NOT NULL DEFAULT -1,
    [SalesOrderHeaderKey] INT NOT NULL DEFAULT -1,
    [SalesOrderLineKey] INT NOT NULL DEFAULT -1,
    [CustomerKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [SellingPlantKey] INT NULL DEFAULT -1,
    [SalesChannelSegmentKey] INT NOT NULL DEFAULT -1,
    [SalesTerritoryPodKey] INT NOT NULL DEFAULT -1,
    [SalesOrderLifecycleStatusKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [CurrencyKey] INT NOT NULL DEFAULT -1,
    [OrderedQuantity] DECIMAL(18,4) NOT NULL,
    [GrossSalesAmount] MONEY NOT NULL,
    [NetSalesAmount] MONEY NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_fact_SalesOrderBooking] PRIMARY KEY NONCLUSTERED ([SalesOrderBookingKey])
);
END
GO
