-- Generated by tools.generator. Do not hand-edit.

-- Subject area: equipment_oee

IF OBJECT_ID(N'ref.MachineLossCategory', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[MachineLossCategory] (
    [MachineLossCategoryKey] INT IDENTITY(1,1) NOT NULL,
    [LossCategoryCode] NVARCHAR(30) NOT NULL,
    [LossCategoryName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_MachineLossCategory] PRIMARY KEY CLUSTERED ([MachineLossCategoryKey])
);
END
GO

IF OBJECT_ID(N'ref.MachineSensorType', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[MachineSensorType] (
    [MachineSensorTypeKey] INT IDENTITY(1,1) NOT NULL,
    [SensorTypeCode] NVARCHAR(30) NOT NULL,
    [SensorTypeName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_MachineSensorType] PRIMARY KEY CLUSTERED ([MachineSensorTypeKey])
);
END
GO

IF OBJECT_ID(N'ref.MachineStateType', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[MachineStateType] (
    [MachineStateTypeKey] INT IDENTITY(1,1) NOT NULL,
    [StateTypeCode] NVARCHAR(30) NOT NULL,
    [StateTypeName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_MachineStateType] PRIMARY KEY CLUSTERED ([MachineStateTypeKey])
);
END
GO

IF OBJECT_ID(N'ref.MachineUtilityType', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[MachineUtilityType] (
    [MachineUtilityTypeKey] INT IDENTITY(1,1) NOT NULL,
    [UtilityTypeCode] NVARCHAR(30) NOT NULL,
    [UtilityTypeName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_MachineUtilityType] PRIMARY KEY CLUSTERED ([MachineUtilityTypeKey])
);
END
GO

IF OBJECT_ID(N'ref.OeeCalculationMethod', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[OeeCalculationMethod] (
    [OeeCalculationMethodKey] INT IDENTITY(1,1) NOT NULL,
    [CalculationMethodCode] NVARCHAR(30) NOT NULL,
    [CalculationMethodName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_OeeCalculationMethod] PRIMARY KEY CLUSTERED ([OeeCalculationMethodKey])
);
END
GO
