-- Generated by tools.generator. Do not hand-edit.

-- Subject area: finance_costing

IF OBJECT_ID(N'ref.FinanceCostingMethod', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[FinanceCostingMethod] (
    [FinanceCostingMethodKey] INT IDENTITY(1,1) NOT NULL,
    [CostingMethodCode] NVARCHAR(20) NOT NULL,
    [CostingMethodName] NVARCHAR(100) NOT NULL,
    [UsesStandardCost] BIT NOT NULL DEFAULT 0,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_FinanceCostingMethod] PRIMARY KEY CLUSTERED ([FinanceCostingMethodKey])
);
END
GO

IF OBJECT_ID(N'ref.FinanceJournalSource', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[FinanceJournalSource] (
    [FinanceJournalSourceKey] INT IDENTITY(1,1) NOT NULL,
    [JournalSourceCode] NVARCHAR(30) NOT NULL,
    [JournalSourceName] NVARCHAR(120) NOT NULL,
    [IsSubledgerSource] BIT NOT NULL DEFAULT 1,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_FinanceJournalSource] PRIMARY KEY CLUSTERED ([FinanceJournalSourceKey])
);
END
GO

IF OBJECT_ID(N'ref.FinancePostingStatus', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[FinancePostingStatus] (
    [FinancePostingStatusKey] INT IDENTITY(1,1) NOT NULL,
    [PostingStatusCode] NVARCHAR(20) NOT NULL,
    [PostingStatusName] NVARCHAR(80) NOT NULL,
    [AllowsReporting] BIT NOT NULL DEFAULT 1,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_FinancePostingStatus] PRIMARY KEY CLUSTERED ([FinancePostingStatusKey])
);
END
GO

IF OBJECT_ID(N'ref.FinanceScenarioType', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[FinanceScenarioType] (
    [FinanceScenarioTypeKey] INT IDENTITY(1,1) NOT NULL,
    [ScenarioTypeCode] NVARCHAR(20) NOT NULL,
    [ScenarioTypeName] NVARCHAR(80) NOT NULL,
    [IsActualScenario] BIT NOT NULL DEFAULT 0,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_FinanceScenarioType] PRIMARY KEY CLUSTERED ([FinanceScenarioTypeKey])
);
END
GO

IF OBJECT_ID(N'ref.FinanceVarianceType', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[FinanceVarianceType] (
    [FinanceVarianceTypeKey] INT IDENTITY(1,1) NOT NULL,
    [VarianceTypeCode] NVARCHAR(30) NOT NULL,
    [VarianceTypeName] NVARCHAR(120) NOT NULL,
    [IsManufacturingVariance] BIT NOT NULL DEFAULT 1,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_FinanceVarianceType] PRIMARY KEY CLUSTERED ([FinanceVarianceTypeKey])
);
END
GO
