-- Generated by tools.generator. Do not hand-edit.

-- Subject area: production_execution

IF OBJECT_ID(N'ref.ProductionDowntimeReason', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[ProductionDowntimeReason] (
    [ProductionDowntimeReasonKey] INT IDENTITY(1,1) NOT NULL,
    [DowntimeReasonCode] NVARCHAR(30) NOT NULL,
    [DowntimeReasonName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_ProductionDowntimeReason] PRIMARY KEY CLUSTERED ([ProductionDowntimeReasonKey])
);
END
GO

IF OBJECT_ID(N'ref.ProductionOrderStatus', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[ProductionOrderStatus] (
    [ProductionOrderStatusKey] INT IDENTITY(1,1) NOT NULL,
    [OrderStatusCode] NVARCHAR(30) NOT NULL,
    [OrderStatusName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_ProductionOrderStatus] PRIMARY KEY CLUSTERED ([ProductionOrderStatusKey])
);
END
GO

IF OBJECT_ID(N'ref.ProductionReworkReason', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[ProductionReworkReason] (
    [ProductionReworkReasonKey] INT IDENTITY(1,1) NOT NULL,
    [ReworkReasonCode] NVARCHAR(30) NOT NULL,
    [ReworkReasonName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_ProductionReworkReason] PRIMARY KEY CLUSTERED ([ProductionReworkReasonKey])
);
END
GO

IF OBJECT_ID(N'ref.ProductionRunType', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[ProductionRunType] (
    [ProductionRunTypeKey] INT IDENTITY(1,1) NOT NULL,
    [RunTypeCode] NVARCHAR(30) NOT NULL,
    [RunTypeName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_ProductionRunType] PRIMARY KEY CLUSTERED ([ProductionRunTypeKey])
);
END
GO

IF OBJECT_ID(N'ref.ProductionScrapReason', N'U') IS NULL
BEGIN
CREATE TABLE [ref].[ProductionScrapReason] (
    [ProductionScrapReasonKey] INT IDENTITY(1,1) NOT NULL,
    [ScrapReasonCode] NVARCHAR(30) NOT NULL,
    [ScrapReasonName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_ref_ProductionScrapReason] PRIMARY KEY CLUSTERED ([ProductionScrapReasonKey])
);
END
GO
