-- Generated by tools.generator. Do not hand-edit.

-- Subject area: finance_costing

CREATE OR ALTER VIEW [dim].[vwDimFinanceCurrencyRateSet] AS
SELECT
    b.[FinanceCurrencyRateSetKey] AS [FinanceCurrencyRateSetKey],
    b.[CurrencyRateSetCode] AS [CurrencyRateSetCode],
    b.[FromCurrencyKey] AS [FromCurrencyKey],
    b.[ToCurrencyKey] AS [ToCurrencyKey],
    b.[SourceSystemRefKey] AS [SourceSystemRefKey],
    b.[RateSetName] AS [RateSetName],
    b.[RatePurposeCode] AS [RatePurposeCode],
    b.[EffectiveDate] AS [EffectiveDate],
    b.[SourceSystemKey] AS [SourceSystemKey],
    b.[BatchId] AS [BatchId],
    b.[LoadedAtUtc] AS [LoadedAtUtc],
    p1.[CurrencyCode] AS [FromCurrency_CurrencyCode],
    p1.[CurrencyName] AS [FromCurrency_CurrencyName],
    p2.[RegionCode] AS [FromCurrency_CurrencyRegion_RegionCode],
    p2.[RegionName] AS [FromCurrency_CurrencyRegion_RegionName],
    p2.[DefaultCurrencyCode] AS [FromCurrency_CurrencyRegion_DefaultCurrencyCode],
    p3.[CurrencyCode] AS [ToCurrency_CurrencyCode],
    p3.[CurrencyName] AS [ToCurrency_CurrencyName],
    p4.[RegionCode] AS [ToCurrency_CurrencyRegion_RegionCode],
    p4.[RegionName] AS [ToCurrency_CurrencyRegion_RegionName],
    p4.[DefaultCurrencyCode] AS [ToCurrency_CurrencyRegion_DefaultCurrencyCode],
    p5.[SourceSystemCode] AS [SourceSystemRef_SourceSystemCode],
    p5.[SourceSystemName] AS [SourceSystemRef_SourceSystemName]
FROM [dim].[FinanceCurrencyRateSet] b
LEFT JOIN [ref].[Currency] p1 ON b.[FromCurrencyKey] = p1.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p2 ON p1.[CurrencyRegionKey] = p2.[CurrencyRegionKey]
LEFT JOIN [ref].[Currency] p3 ON b.[ToCurrencyKey] = p3.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p4 ON p3.[CurrencyRegionKey] = p4.[CurrencyRegionKey]
LEFT JOIN [ref].[SourceSystem] p5 ON b.[SourceSystemRefKey] = p5.[SourceSystemKey]
GO

CREATE OR ALTER VIEW [dim].[vwDimFinanceJournalHeader] AS
SELECT
    b.[FinanceJournalHeaderKey] AS [FinanceJournalHeaderKey],
    b.[JournalEntryNumber] AS [JournalEntryNumber],
    b.[BusinessUnitKey] AS [BusinessUnitKey],
    b.[PreparerEmployeeKey] AS [PreparerEmployeeKey],
    b.[ApproverEmployeeKey] AS [ApproverEmployeeKey],
    b.[FinancePostingStatusKey] AS [FinancePostingStatusKey],
    b.[FinanceJournalSourceKey] AS [FinanceJournalSourceKey],
    b.[CurrencyKey] AS [CurrencyKey],
    b.[JournalEntryName] AS [JournalEntryName],
    b.[FiscalDocumentNumber] AS [FiscalDocumentNumber],
    b.[ReversalJournalEntryNumber] AS [ReversalJournalEntryNumber],
    b.[SourceSystemKey] AS [SourceSystemKey],
    b.[BatchId] AS [BatchId],
    b.[LoadedAtUtc] AS [LoadedAtUtc],
    b.[EffectiveFromUtc] AS [EffectiveFromUtc],
    b.[EffectiveToUtc] AS [EffectiveToUtc],
    b.[IsCurrent] AS [IsCurrent],
    b.[RowHash] AS [RowHash],
    p1.[CurrencyCode] AS [Currency_CurrencyCode],
    p1.[CurrencyName] AS [Currency_CurrencyName],
    p2.[RegionCode] AS [Currency_CurrencyRegion_RegionCode],
    p2.[RegionName] AS [Currency_CurrencyRegion_RegionName],
    p2.[DefaultCurrencyCode] AS [Currency_CurrencyRegion_DefaultCurrencyCode],
    p3.[JournalSourceCode] AS [FinanceJournalSource_JournalSourceCode],
    p3.[JournalSourceName] AS [FinanceJournalSource_JournalSourceName],
    p4.[PostingStatusCode] AS [FinancePostingStatus_PostingStatusCode],
    p4.[PostingStatusName] AS [FinancePostingStatus_PostingStatusName],
    p5.[BusinessUnitCode] AS [BusinessUnit_BusinessUnitCode],
    p5.[BusinessUnitName] AS [BusinessUnit_BusinessUnitName],
    p5.[PresidentName] AS [BusinessUnit_PresidentName],
    p5.[PrimaryPlantCode] AS [BusinessUnit_PrimaryPlantCode],
    p5.[DefaultCurrencyCode] AS [BusinessUnit_DefaultCurrencyCode],
    p5.[ProfitCenterCode] AS [BusinessUnit_ProfitCenterCode],
    p6.[CurrencyCode] AS [BusinessUnit_Currency_CurrencyCode],
    p6.[CurrencyName] AS [BusinessUnit_Currency_CurrencyName],
    p7.[RegionCode] AS [BusinessUnit_Currency_CurrencyRegion_RegionCode],
    p7.[RegionName] AS [BusinessUnit_Currency_CurrencyRegion_RegionName],
    p7.[DefaultCurrencyCode] AS [BusinessUnit_Currency_CurrencyRegion_DefaultCurrencyCode],
    p8.[StatusCode] AS [BusinessUnit_RecordStatus_StatusCode],
    p8.[StatusName] AS [BusinessUnit_RecordStatus_StatusName],
    p9.[PortfolioCode] AS [BusinessUnit_BusinessUnitPortfolio_PortfolioCode],
    p9.[PortfolioName] AS [BusinessUnit_BusinessUnitPortfolio_PortfolioName],
    p9.[OwnerName] AS [BusinessUnit_BusinessUnitPortfolio_OwnerName],
    p10.[StatusCode] AS [BusinessUnit_BusinessUnitPortfolio_RecordStatus_StatusCode],
    p10.[StatusName] AS [BusinessUnit_BusinessUnitPortfolio_RecordStatus_StatusName],
    p11.[OrgBusinessUnitCode] AS [BusinessUnit_OrgBusinessUnit_OrgBusinessUnitCode],
    p11.[OrgBusinessUnitName] AS [BusinessUnit_OrgBusinessUnit_OrgBusinessUnitName],
    p12.[OrgRegionCode] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgRegionCode],
    p12.[OrgRegionName] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgRegionName],
    p13.[OrgDivisionCode] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionCode],
    p13.[OrgDivisionName] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionName],
    p14.[OrgEnterpriseCode] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseCode],
    p14.[OrgEnterpriseName] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseName],
    p15.[EmployeeNumber] AS [ApproverEmployee_EmployeeNumber],
    p15.[EmployeeFullName] AS [ApproverEmployee_EmployeeFullName],
    p15.[PreferredName] AS [ApproverEmployee_PreferredName],
    p15.[HomePlantCode] AS [ApproverEmployee_HomePlantCode],
    p16.[EmploymentTypeCode] AS [ApproverEmployee_EmploymentType_EmploymentTypeCode],
    p16.[EmploymentTypeName] AS [ApproverEmployee_EmploymentType_EmploymentTypeName],
    p17.[LanguageCode] AS [ApproverEmployee_Language_LanguageCode],
    p17.[LanguageName] AS [ApproverEmployee_Language_LanguageName],
    p18.[StatusCode] AS [ApproverEmployee_RecordStatus_StatusCode],
    p18.[StatusName] AS [ApproverEmployee_RecordStatus_StatusName],
    p19.[ShiftCode] AS [ApproverEmployee_ShiftCode_ShiftCode],
    p19.[ShiftCodeName] AS [ApproverEmployee_ShiftCode_ShiftCodeName],
    p20.[JobRoleCode] AS [ApproverEmployee_EmployeeJobRole_JobRoleCode],
    p20.[JobRoleName] AS [ApproverEmployee_EmployeeJobRole_JobRoleName],
    p20.[OwnerName] AS [ApproverEmployee_EmployeeJobRole_OwnerName],
    p21.[LaborGradeCode] AS [ApproverEmployee_EmployeeJobRole_LaborGrade_LaborGradeCode],
    p21.[LaborGradeName] AS [ApproverEmployee_EmployeeJobRole_LaborGrade_LaborGradeName],
    p22.[StatusCode] AS [ApproverEmployee_EmployeeJobRole_RecordStatus_StatusCode],
    p22.[StatusName] AS [ApproverEmployee_EmployeeJobRole_RecordStatus_StatusName],
    p23.[JobFamilyCode] AS [ApproverEmployee_EmployeeJobRole_EmployeeJobFamily_JobFamilyCode],
    p23.[JobFamilyName] AS [ApproverEmployee_EmployeeJobRole_EmployeeJobFamily_JobFamilyName],
    p23.[OwnerName] AS [ApproverEmployee_EmployeeJobRole_EmployeeJobFamily_OwnerName],
    p24.[StatusCode] AS [ApproverEmployee_EmployeeJobRole_EmployeeJobFamily_RecordStatus_StatusCode],
    p24.[StatusName] AS [ApproverEmployee_EmployeeJobRole_EmployeeJobFamily_RecordStatus_StatusName],
    p25.[PayGradeCode] AS [ApproverEmployee_EmployeePayGrade_PayGradeCode],
    p25.[PayGradeName] AS [ApproverEmployee_EmployeePayGrade_PayGradeName],
    p25.[OwnerName] AS [ApproverEmployee_EmployeePayGrade_OwnerName],
    p26.[CurrencyCode] AS [ApproverEmployee_EmployeePayGrade_Currency_CurrencyCode],
    p26.[CurrencyName] AS [ApproverEmployee_EmployeePayGrade_Currency_CurrencyName],
    p27.[RegionCode] AS [ApproverEmployee_EmployeePayGrade_Currency_CurrencyRegion_RegionCode],
    p27.[RegionName] AS [ApproverEmployee_EmployeePayGrade_Currency_CurrencyRegion_RegionName],
    p27.[DefaultCurrencyCode] AS [ApproverEmployee_EmployeePayGrade_Currency_CurrencyRegion_DefaultCurrencyCode],
    p28.[StatusCode] AS [ApproverEmployee_EmployeePayGrade_RecordStatus_StatusCode],
    p28.[StatusName] AS [ApproverEmployee_EmployeePayGrade_RecordStatus_StatusName],
    p29.[UnionCode] AS [ApproverEmployee_EmployeeUnion_UnionCode],
    p29.[UnionName] AS [ApproverEmployee_EmployeeUnion_UnionName],
    p29.[OwnerName] AS [ApproverEmployee_EmployeeUnion_OwnerName],
    p30.[CountryCode] AS [ApproverEmployee_EmployeeUnion_Country_CountryCode],
    p30.[CountryName] AS [ApproverEmployee_EmployeeUnion_Country_CountryName],
    p31.[RegionCode] AS [ApproverEmployee_EmployeeUnion_Country_Region_RegionCode],
    p31.[RegionName] AS [ApproverEmployee_EmployeeUnion_Country_Region_RegionName],
    p32.[ContinentCode] AS [ApproverEmployee_EmployeeUnion_Country_Region_Continent_ContinentCode],
    p32.[ContinentName] AS [ApproverEmployee_EmployeeUnion_Country_Region_Continent_ContinentName],
    p33.[StatusCode] AS [ApproverEmployee_EmployeeUnion_RecordStatus_StatusCode],
    p33.[StatusName] AS [ApproverEmployee_EmployeeUnion_RecordStatus_StatusName],
    p34.[EmployeeNumber] AS [PreparerEmployee_EmployeeNumber],
    p34.[EmployeeFullName] AS [PreparerEmployee_EmployeeFullName],
    p34.[PreferredName] AS [PreparerEmployee_PreferredName],
    p34.[HomePlantCode] AS [PreparerEmployee_HomePlantCode],
    p35.[EmploymentTypeCode] AS [PreparerEmployee_EmploymentType_EmploymentTypeCode],
    p35.[EmploymentTypeName] AS [PreparerEmployee_EmploymentType_EmploymentTypeName],
    p36.[LanguageCode] AS [PreparerEmployee_Language_LanguageCode],
    p36.[LanguageName] AS [PreparerEmployee_Language_LanguageName],
    p37.[StatusCode] AS [PreparerEmployee_RecordStatus_StatusCode],
    p37.[StatusName] AS [PreparerEmployee_RecordStatus_StatusName],
    p38.[ShiftCode] AS [PreparerEmployee_ShiftCode_ShiftCode],
    p38.[ShiftCodeName] AS [PreparerEmployee_ShiftCode_ShiftCodeName],
    p39.[JobRoleCode] AS [PreparerEmployee_EmployeeJobRole_JobRoleCode],
    p39.[JobRoleName] AS [PreparerEmployee_EmployeeJobRole_JobRoleName],
    p39.[OwnerName] AS [PreparerEmployee_EmployeeJobRole_OwnerName],
    p40.[LaborGradeCode] AS [PreparerEmployee_EmployeeJobRole_LaborGrade_LaborGradeCode],
    p40.[LaborGradeName] AS [PreparerEmployee_EmployeeJobRole_LaborGrade_LaborGradeName],
    p41.[StatusCode] AS [PreparerEmployee_EmployeeJobRole_RecordStatus_StatusCode],
    p41.[StatusName] AS [PreparerEmployee_EmployeeJobRole_RecordStatus_StatusName],
    p42.[JobFamilyCode] AS [PreparerEmployee_EmployeeJobRole_EmployeeJobFamily_JobFamilyCode],
    p42.[JobFamilyName] AS [PreparerEmployee_EmployeeJobRole_EmployeeJobFamily_JobFamilyName],
    p42.[OwnerName] AS [PreparerEmployee_EmployeeJobRole_EmployeeJobFamily_OwnerName],
    p43.[StatusCode] AS [PreparerEmployee_EmployeeJobRole_EmployeeJobFamily_RecordStatus_StatusCode],
    p43.[StatusName] AS [PreparerEmployee_EmployeeJobRole_EmployeeJobFamily_RecordStatus_StatusName],
    p44.[PayGradeCode] AS [PreparerEmployee_EmployeePayGrade_PayGradeCode],
    p44.[PayGradeName] AS [PreparerEmployee_EmployeePayGrade_PayGradeName],
    p44.[OwnerName] AS [PreparerEmployee_EmployeePayGrade_OwnerName],
    p45.[CurrencyCode] AS [PreparerEmployee_EmployeePayGrade_Currency_CurrencyCode],
    p45.[CurrencyName] AS [PreparerEmployee_EmployeePayGrade_Currency_CurrencyName],
    p46.[RegionCode] AS [PreparerEmployee_EmployeePayGrade_Currency_CurrencyRegion_RegionCode],
    p46.[RegionName] AS [PreparerEmployee_EmployeePayGrade_Currency_CurrencyRegion_RegionName],
    p46.[DefaultCurrencyCode] AS [PreparerEmployee_EmployeePayGrade_Currency_CurrencyRegion_DefaultCurrencyCode],
    p47.[StatusCode] AS [PreparerEmployee_EmployeePayGrade_RecordStatus_StatusCode],
    p47.[StatusName] AS [PreparerEmployee_EmployeePayGrade_RecordStatus_StatusName],
    p48.[UnionCode] AS [PreparerEmployee_EmployeeUnion_UnionCode],
    p48.[UnionName] AS [PreparerEmployee_EmployeeUnion_UnionName],
    p48.[OwnerName] AS [PreparerEmployee_EmployeeUnion_OwnerName],
    p49.[CountryCode] AS [PreparerEmployee_EmployeeUnion_Country_CountryCode],
    p49.[CountryName] AS [PreparerEmployee_EmployeeUnion_Country_CountryName],
    p50.[RegionCode] AS [PreparerEmployee_EmployeeUnion_Country_Region_RegionCode],
    p50.[RegionName] AS [PreparerEmployee_EmployeeUnion_Country_Region_RegionName],
    p51.[ContinentCode] AS [PreparerEmployee_EmployeeUnion_Country_Region_Continent_ContinentCode],
    p51.[ContinentName] AS [PreparerEmployee_EmployeeUnion_Country_Region_Continent_ContinentName],
    p52.[StatusCode] AS [PreparerEmployee_EmployeeUnion_RecordStatus_StatusCode],
    p52.[StatusName] AS [PreparerEmployee_EmployeeUnion_RecordStatus_StatusName]
FROM [dim].[FinanceJournalHeader] b
LEFT JOIN [ref].[Currency] p1 ON b.[CurrencyKey] = p1.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p2 ON p1.[CurrencyRegionKey] = p2.[CurrencyRegionKey]
LEFT JOIN [ref].[FinanceJournalSource] p3 ON b.[FinanceJournalSourceKey] = p3.[FinanceJournalSourceKey]
LEFT JOIN [ref].[FinancePostingStatus] p4 ON b.[FinancePostingStatusKey] = p4.[FinancePostingStatusKey]
LEFT JOIN [dim].[BusinessUnit] p5 ON b.[BusinessUnitKey] = p5.[BusinessUnitKey]
LEFT JOIN [ref].[Currency] p6 ON p5.[CurrencyKey] = p6.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p7 ON p6.[CurrencyRegionKey] = p7.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p8 ON p5.[RecordStatusKey] = p8.[RecordStatusKey]
LEFT JOIN [dim].[BusinessUnitPortfolio] p9 ON p5.[BusinessUnitPortfolioKey] = p9.[BusinessUnitPortfolioKey]
LEFT JOIN [ref].[RecordStatus] p10 ON p9.[RecordStatusKey] = p10.[RecordStatusKey]
LEFT JOIN [dim].[OrgBusinessUnit] p11 ON p5.[OrgBusinessUnitKey] = p11.[OrgBusinessUnitKey]
LEFT JOIN [dim].[OrgRegion] p12 ON p11.[OrgRegionKey] = p12.[OrgRegionKey]
LEFT JOIN [dim].[OrgDivision] p13 ON p12.[OrgDivisionKey] = p13.[OrgDivisionKey]
LEFT JOIN [dim].[OrgEnterprise] p14 ON p13.[OrgEnterpriseKey] = p14.[OrgEnterpriseKey]
LEFT JOIN [dim].[Employee] p15 ON b.[ApproverEmployeeKey] = p15.[EmployeeKey]
LEFT JOIN [ref].[EmploymentType] p16 ON p15.[EmploymentTypeKey] = p16.[EmploymentTypeKey]
LEFT JOIN [ref].[Language] p17 ON p15.[LanguageKey] = p17.[LanguageKey]
LEFT JOIN [ref].[RecordStatus] p18 ON p15.[RecordStatusKey] = p18.[RecordStatusKey]
LEFT JOIN [ref].[ShiftCode] p19 ON p15.[ShiftCodeKey] = p19.[ShiftCodeKey]
LEFT JOIN [dim].[EmployeeJobRole] p20 ON p15.[EmployeeJobRoleKey] = p20.[EmployeeJobRoleKey]
LEFT JOIN [ref].[LaborGrade] p21 ON p20.[LaborGradeKey] = p21.[LaborGradeKey]
LEFT JOIN [ref].[RecordStatus] p22 ON p20.[RecordStatusKey] = p22.[RecordStatusKey]
LEFT JOIN [dim].[EmployeeJobFamily] p23 ON p20.[EmployeeJobFamilyKey] = p23.[EmployeeJobFamilyKey]
LEFT JOIN [ref].[RecordStatus] p24 ON p23.[RecordStatusKey] = p24.[RecordStatusKey]
LEFT JOIN [dim].[EmployeePayGrade] p25 ON p15.[EmployeePayGradeKey] = p25.[EmployeePayGradeKey]
LEFT JOIN [ref].[Currency] p26 ON p25.[CurrencyKey] = p26.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p27 ON p26.[CurrencyRegionKey] = p27.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p28 ON p25.[RecordStatusKey] = p28.[RecordStatusKey]
LEFT JOIN [dim].[EmployeeUnion] p29 ON p15.[EmployeeUnionKey] = p29.[EmployeeUnionKey]
LEFT JOIN [ref].[Country] p30 ON p29.[CountryKey] = p30.[CountryKey]
LEFT JOIN [ref].[Region] p31 ON p30.[RegionKey] = p31.[RegionKey]
LEFT JOIN [ref].[Continent] p32 ON p31.[ContinentKey] = p32.[ContinentKey]
LEFT JOIN [ref].[RecordStatus] p33 ON p29.[RecordStatusKey] = p33.[RecordStatusKey]
LEFT JOIN [dim].[Employee] p34 ON b.[PreparerEmployeeKey] = p34.[EmployeeKey]
LEFT JOIN [ref].[EmploymentType] p35 ON p34.[EmploymentTypeKey] = p35.[EmploymentTypeKey]
LEFT JOIN [ref].[Language] p36 ON p34.[LanguageKey] = p36.[LanguageKey]
LEFT JOIN [ref].[RecordStatus] p37 ON p34.[RecordStatusKey] = p37.[RecordStatusKey]
LEFT JOIN [ref].[ShiftCode] p38 ON p34.[ShiftCodeKey] = p38.[ShiftCodeKey]
LEFT JOIN [dim].[EmployeeJobRole] p39 ON p34.[EmployeeJobRoleKey] = p39.[EmployeeJobRoleKey]
LEFT JOIN [ref].[LaborGrade] p40 ON p39.[LaborGradeKey] = p40.[LaborGradeKey]
LEFT JOIN [ref].[RecordStatus] p41 ON p39.[RecordStatusKey] = p41.[RecordStatusKey]
LEFT JOIN [dim].[EmployeeJobFamily] p42 ON p39.[EmployeeJobFamilyKey] = p42.[EmployeeJobFamilyKey]
LEFT JOIN [ref].[RecordStatus] p43 ON p42.[RecordStatusKey] = p43.[RecordStatusKey]
LEFT JOIN [dim].[EmployeePayGrade] p44 ON p34.[EmployeePayGradeKey] = p44.[EmployeePayGradeKey]
LEFT JOIN [ref].[Currency] p45 ON p44.[CurrencyKey] = p45.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p46 ON p45.[CurrencyRegionKey] = p46.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p47 ON p44.[RecordStatusKey] = p47.[RecordStatusKey]
LEFT JOIN [dim].[EmployeeUnion] p48 ON p34.[EmployeeUnionKey] = p48.[EmployeeUnionKey]
LEFT JOIN [ref].[Country] p49 ON p48.[CountryKey] = p49.[CountryKey]
LEFT JOIN [ref].[Region] p50 ON p49.[RegionKey] = p50.[RegionKey]
LEFT JOIN [ref].[Continent] p51 ON p50.[ContinentKey] = p51.[ContinentKey]
LEFT JOIN [ref].[RecordStatus] p52 ON p48.[RecordStatusKey] = p52.[RecordStatusKey]
GO

CREATE OR ALTER VIEW [dim].[vwDimFinanceJournalLine] AS
SELECT
    b.[FinanceJournalLineKey] AS [FinanceJournalLineKey],
    b.[JournalLineCode] AS [JournalLineCode],
    b.[FinanceJournalHeaderKey] AS [FinanceJournalHeaderKey],
    b.[GlAccountKey] AS [GlAccountKey],
    b.[CostCenterKey] AS [CostCenterKey],
    b.[FinancePostingBucketKey] AS [FinancePostingBucketKey],
    b.[FinancePostingStatusKey] AS [FinancePostingStatusKey],
    b.[CurrencyKey] AS [CurrencyKey],
    b.[JournalLineSequenceNumber] AS [JournalLineSequenceNumber],
    b.[LineMemo] AS [LineMemo],
    b.[IsReversalLine] AS [IsReversalLine],
    b.[SourceSystemKey] AS [SourceSystemKey],
    b.[BatchId] AS [BatchId],
    b.[LoadedAtUtc] AS [LoadedAtUtc],
    b.[EffectiveFromUtc] AS [EffectiveFromUtc],
    b.[EffectiveToUtc] AS [EffectiveToUtc],
    b.[IsCurrent] AS [IsCurrent],
    b.[RowHash] AS [RowHash],
    p1.[CurrencyCode] AS [Currency_CurrencyCode],
    p1.[CurrencyName] AS [Currency_CurrencyName],
    p2.[RegionCode] AS [Currency_CurrencyRegion_RegionCode],
    p2.[RegionName] AS [Currency_CurrencyRegion_RegionName],
    p2.[DefaultCurrencyCode] AS [Currency_CurrencyRegion_DefaultCurrencyCode],
    p3.[PostingStatusCode] AS [FinancePostingStatus_PostingStatusCode],
    p3.[PostingStatusName] AS [FinancePostingStatus_PostingStatusName],
    p4.[CostCenterCode] AS [CostCenter_CostCenterCode],
    p4.[CostCenterName] AS [CostCenter_CostCenterName],
    p4.[BudgetOwnerName] AS [CostCenter_BudgetOwnerName],
    p5.[StatusCode] AS [CostCenter_BudgetStatus_StatusCode],
    p5.[BudgetStatusName] AS [CostCenter_BudgetStatus_BudgetStatusName],
    p6.[CurrencyCode] AS [CostCenter_Currency_CurrencyCode],
    p6.[CurrencyName] AS [CostCenter_Currency_CurrencyName],
    p7.[RegionCode] AS [CostCenter_Currency_CurrencyRegion_RegionCode],
    p7.[RegionName] AS [CostCenter_Currency_CurrencyRegion_RegionName],
    p7.[DefaultCurrencyCode] AS [CostCenter_Currency_CurrencyRegion_DefaultCurrencyCode],
    p8.[StatusCode] AS [CostCenter_RecordStatus_StatusCode],
    p8.[StatusName] AS [CostCenter_RecordStatus_StatusName],
    p9.[CostCenterTypeCode] AS [CostCenter_CostCenterType_CostCenterTypeCode],
    p9.[CostCenterTypeName] AS [CostCenter_CostCenterType_CostCenterTypeName],
    p9.[OwnerName] AS [CostCenter_CostCenterType_OwnerName],
    p10.[StatusCode] AS [CostCenter_CostCenterType_RecordStatus_StatusCode],
    p10.[StatusName] AS [CostCenter_CostCenterType_RecordStatus_StatusName],
    p11.[OrgBusinessUnitCode] AS [CostCenter_OrgBusinessUnit_OrgBusinessUnitCode],
    p11.[OrgBusinessUnitName] AS [CostCenter_OrgBusinessUnit_OrgBusinessUnitName],
    p12.[OrgRegionCode] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgRegionCode],
    p12.[OrgRegionName] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgRegionName],
    p13.[OrgDivisionCode] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionCode],
    p13.[OrgDivisionName] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionName],
    p14.[OrgEnterpriseCode] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseCode],
    p14.[OrgEnterpriseName] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseName],
    p15.[JournalEntryNumber] AS [FinanceJournalHeader_JournalEntryNumber],
    p15.[JournalEntryName] AS [FinanceJournalHeader_JournalEntryName],
    p16.[CurrencyCode] AS [FinanceJournalHeader_Currency_CurrencyCode],
    p16.[CurrencyName] AS [FinanceJournalHeader_Currency_CurrencyName],
    p17.[RegionCode] AS [FinanceJournalHeader_Currency_CurrencyRegion_RegionCode],
    p17.[RegionName] AS [FinanceJournalHeader_Currency_CurrencyRegion_RegionName],
    p17.[DefaultCurrencyCode] AS [FinanceJournalHeader_Currency_CurrencyRegion_DefaultCurrencyCode],
    p18.[JournalSourceCode] AS [FinanceJournalHeader_FinanceJournalSource_JournalSourceCode],
    p18.[JournalSourceName] AS [FinanceJournalHeader_FinanceJournalSource_JournalSourceName],
    p19.[PostingStatusCode] AS [FinanceJournalHeader_FinancePostingStatus_PostingStatusCode],
    p19.[PostingStatusName] AS [FinanceJournalHeader_FinancePostingStatus_PostingStatusName],
    p20.[BusinessUnitCode] AS [FinanceJournalHeader_BusinessUnit_BusinessUnitCode],
    p20.[BusinessUnitName] AS [FinanceJournalHeader_BusinessUnit_BusinessUnitName],
    p20.[PresidentName] AS [FinanceJournalHeader_BusinessUnit_PresidentName],
    p20.[PrimaryPlantCode] AS [FinanceJournalHeader_BusinessUnit_PrimaryPlantCode],
    p20.[DefaultCurrencyCode] AS [FinanceJournalHeader_BusinessUnit_DefaultCurrencyCode],
    p20.[ProfitCenterCode] AS [FinanceJournalHeader_BusinessUnit_ProfitCenterCode],
    p21.[CurrencyCode] AS [FinanceJournalHeader_BusinessUnit_Currency_CurrencyCode],
    p21.[CurrencyName] AS [FinanceJournalHeader_BusinessUnit_Currency_CurrencyName],
    p22.[RegionCode] AS [FinanceJournalHeader_BusinessUnit_Currency_CurrencyRegion_RegionCode],
    p22.[RegionName] AS [FinanceJournalHeader_BusinessUnit_Currency_CurrencyRegion_RegionName],
    p22.[DefaultCurrencyCode] AS [FinanceJournalHeader_BusinessUnit_Currency_CurrencyRegion_DefaultCurrencyCode],
    p23.[StatusCode] AS [FinanceJournalHeader_BusinessUnit_RecordStatus_StatusCode],
    p23.[StatusName] AS [FinanceJournalHeader_BusinessUnit_RecordStatus_StatusName],
    p24.[PortfolioCode] AS [FinanceJournalHeader_BusinessUnit_BusinessUnitPortfolio_PortfolioCode],
    p24.[PortfolioName] AS [FinanceJournalHeader_BusinessUnit_BusinessUnitPortfolio_PortfolioName],
    p24.[OwnerName] AS [FinanceJournalHeader_BusinessUnit_BusinessUnitPortfolio_OwnerName],
    p25.[StatusCode] AS [FinanceJournalHeader_BusinessUnit_BusinessUnitPortfolio_RecordStatus_StatusCode],
    p25.[StatusName] AS [FinanceJournalHeader_BusinessUnit_BusinessUnitPortfolio_RecordStatus_StatusName],
    p26.[OrgBusinessUnitCode] AS [FinanceJournalHeader_BusinessUnit_OrgBusinessUnit_OrgBusinessUnitCode],
    p26.[OrgBusinessUnitName] AS [FinanceJournalHeader_BusinessUnit_OrgBusinessUnit_OrgBusinessUnitName],
    p27.[OrgRegionCode] AS [FinanceJournalHeader_BusinessUnit_OrgBusinessUnit_OrgRegion_OrgRegionCode],
    p27.[OrgRegionName] AS [FinanceJournalHeader_BusinessUnit_OrgBusinessUnit_OrgRegion_OrgRegionName],
    p28.[OrgDivisionCode] AS [FinanceJournalHeader_BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionCode],
    p28.[OrgDivisionName] AS [FinanceJournalHeader_BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionName],
    p29.[OrgEnterpriseCode] AS [FinanceJournalHeader_BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseCode],
    p29.[OrgEnterpriseName] AS [FinanceJournalHeader_BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseName],
    p30.[EmployeeNumber] AS [FinanceJournalHeader_ApproverEmployee_EmployeeNumber],
    p30.[EmployeeFullName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeFullName],
    p30.[PreferredName] AS [FinanceJournalHeader_ApproverEmployee_PreferredName],
    p30.[HomePlantCode] AS [FinanceJournalHeader_ApproverEmployee_HomePlantCode],
    p31.[EmploymentTypeCode] AS [FinanceJournalHeader_ApproverEmployee_EmploymentType_EmploymentTypeCode],
    p31.[EmploymentTypeName] AS [FinanceJournalHeader_ApproverEmployee_EmploymentType_EmploymentTypeName],
    p32.[LanguageCode] AS [FinanceJournalHeader_ApproverEmployee_Language_LanguageCode],
    p32.[LanguageName] AS [FinanceJournalHeader_ApproverEmployee_Language_LanguageName],
    p33.[StatusCode] AS [FinanceJournalHeader_ApproverEmployee_RecordStatus_StatusCode],
    p33.[StatusName] AS [FinanceJournalHeader_ApproverEmployee_RecordStatus_StatusName],
    p34.[ShiftCode] AS [FinanceJournalHeader_ApproverEmployee_ShiftCode_ShiftCode],
    p34.[ShiftCodeName] AS [FinanceJournalHeader_ApproverEmployee_ShiftCode_ShiftCodeName],
    p35.[JobRoleCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_JobRoleCode],
    p35.[JobRoleName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_JobRoleName],
    p35.[OwnerName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_OwnerName],
    p36.[LaborGradeCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_LaborGrade_LaborGradeCode],
    p36.[LaborGradeName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_LaborGrade_LaborGradeName],
    p37.[StatusCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_RecordStatus_StatusCode],
    p37.[StatusName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_RecordStatus_StatusName],
    p38.[JobFamilyCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_EmployeeJobFamily_JobFamilyCode],
    p38.[JobFamilyName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_EmployeeJobFamily_JobFamilyName],
    p38.[OwnerName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_EmployeeJobFamily_OwnerName],
    p39.[StatusCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_EmployeeJobFamily_RecordStatus_StatusCode],
    p39.[StatusName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeJobRole_EmployeeJobFamily_RecordStatus_StatusName],
    p40.[PayGradeCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeePayGrade_PayGradeCode],
    p40.[PayGradeName] AS [FinanceJournalHeader_ApproverEmployee_EmployeePayGrade_PayGradeName],
    p40.[OwnerName] AS [FinanceJournalHeader_ApproverEmployee_EmployeePayGrade_OwnerName],
    p41.[CurrencyCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeePayGrade_Currency_CurrencyCode],
    p41.[CurrencyName] AS [FinanceJournalHeader_ApproverEmployee_EmployeePayGrade_Currency_CurrencyName],
    p42.[RegionCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeePayGrade_Currency_CurrencyRegion_RegionCode],
    p42.[RegionName] AS [FinanceJournalHeader_ApproverEmployee_EmployeePayGrade_Currency_CurrencyRegion_RegionName],
    p42.[DefaultCurrencyCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeePayGrade_Currency_CurrencyRegion_DefaultCurrencyCode],
    p43.[StatusCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeePayGrade_RecordStatus_StatusCode],
    p43.[StatusName] AS [FinanceJournalHeader_ApproverEmployee_EmployeePayGrade_RecordStatus_StatusName],
    p44.[UnionCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_UnionCode],
    p44.[UnionName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_UnionName],
    p44.[OwnerName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_OwnerName],
    p45.[CountryCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_Country_CountryCode],
    p45.[CountryName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_Country_CountryName],
    p46.[RegionCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_Country_Region_RegionCode],
    p46.[RegionName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_Country_Region_RegionName],
    p47.[ContinentCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_Country_Region_Continent_ContinentCode],
    p47.[ContinentName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_Country_Region_Continent_ContinentName],
    p48.[StatusCode] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_RecordStatus_StatusCode],
    p48.[StatusName] AS [FinanceJournalHeader_ApproverEmployee_EmployeeUnion_RecordStatus_StatusName],
    p49.[EmployeeNumber] AS [FinanceJournalHeader_PreparerEmployee_EmployeeNumber],
    p49.[EmployeeFullName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeFullName],
    p49.[PreferredName] AS [FinanceJournalHeader_PreparerEmployee_PreferredName],
    p49.[HomePlantCode] AS [FinanceJournalHeader_PreparerEmployee_HomePlantCode],
    p50.[EmploymentTypeCode] AS [FinanceJournalHeader_PreparerEmployee_EmploymentType_EmploymentTypeCode],
    p50.[EmploymentTypeName] AS [FinanceJournalHeader_PreparerEmployee_EmploymentType_EmploymentTypeName],
    p51.[LanguageCode] AS [FinanceJournalHeader_PreparerEmployee_Language_LanguageCode],
    p51.[LanguageName] AS [FinanceJournalHeader_PreparerEmployee_Language_LanguageName],
    p52.[StatusCode] AS [FinanceJournalHeader_PreparerEmployee_RecordStatus_StatusCode],
    p52.[StatusName] AS [FinanceJournalHeader_PreparerEmployee_RecordStatus_StatusName],
    p53.[ShiftCode] AS [FinanceJournalHeader_PreparerEmployee_ShiftCode_ShiftCode],
    p53.[ShiftCodeName] AS [FinanceJournalHeader_PreparerEmployee_ShiftCode_ShiftCodeName],
    p54.[JobRoleCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_JobRoleCode],
    p54.[JobRoleName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_JobRoleName],
    p54.[OwnerName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_OwnerName],
    p55.[LaborGradeCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_LaborGrade_LaborGradeCode],
    p55.[LaborGradeName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_LaborGrade_LaborGradeName],
    p56.[StatusCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_RecordStatus_StatusCode],
    p56.[StatusName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_RecordStatus_StatusName],
    p57.[JobFamilyCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_EmployeeJobFamily_JobFamilyCode],
    p57.[JobFamilyName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_EmployeeJobFamily_JobFamilyName],
    p57.[OwnerName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_EmployeeJobFamily_OwnerName],
    p58.[StatusCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_EmployeeJobFamily_RecordStatus_StatusCode],
    p58.[StatusName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeJobRole_EmployeeJobFamily_RecordStatus_StatusName],
    p59.[PayGradeCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeePayGrade_PayGradeCode],
    p59.[PayGradeName] AS [FinanceJournalHeader_PreparerEmployee_EmployeePayGrade_PayGradeName],
    p59.[OwnerName] AS [FinanceJournalHeader_PreparerEmployee_EmployeePayGrade_OwnerName],
    p60.[CurrencyCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeePayGrade_Currency_CurrencyCode],
    p60.[CurrencyName] AS [FinanceJournalHeader_PreparerEmployee_EmployeePayGrade_Currency_CurrencyName],
    p61.[RegionCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeePayGrade_Currency_CurrencyRegion_RegionCode],
    p61.[RegionName] AS [FinanceJournalHeader_PreparerEmployee_EmployeePayGrade_Currency_CurrencyRegion_RegionName],
    p61.[DefaultCurrencyCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeePayGrade_Currency_CurrencyRegion_DefaultCurrencyCode],
    p62.[StatusCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeePayGrade_RecordStatus_StatusCode],
    p62.[StatusName] AS [FinanceJournalHeader_PreparerEmployee_EmployeePayGrade_RecordStatus_StatusName],
    p63.[UnionCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_UnionCode],
    p63.[UnionName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_UnionName],
    p63.[OwnerName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_OwnerName],
    p64.[CountryCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_Country_CountryCode],
    p64.[CountryName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_Country_CountryName],
    p65.[RegionCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_Country_Region_RegionCode],
    p65.[RegionName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_Country_Region_RegionName],
    p66.[ContinentCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_Country_Region_Continent_ContinentCode],
    p66.[ContinentName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_Country_Region_Continent_ContinentName],
    p67.[StatusCode] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_RecordStatus_StatusCode],
    p67.[StatusName] AS [FinanceJournalHeader_PreparerEmployee_EmployeeUnion_RecordStatus_StatusName],
    p68.[FinancePostingBucketCode] AS [FinancePostingBucket_FinancePostingBucketCode],
    p68.[FinancePostingBucketName] AS [FinancePostingBucket_FinancePostingBucketName],
    p69.[FinanceAccountSetCode] AS [FinancePostingBucket_FinanceAccountSet_FinanceAccountSetCode],
    p69.[FinanceAccountSetName] AS [FinancePostingBucket_FinanceAccountSet_FinanceAccountSetName],
    p70.[FinanceReportingLineCode] AS [FinancePostingBucket_FinanceAccountSet_FinanceReportingLine_FinanceReportingLineCode],
    p70.[FinanceReportingLineName] AS [FinancePostingBucket_FinanceAccountSet_FinanceReportingLine_FinanceReportingLineName],
    p71.[FinanceStatementSectionCode] AS [FinancePostingBucket_FinanceAccountSet_FinanceReportingLine_FinanceStatementSection_FinanceStatementSectionCode],
    p71.[FinanceStatementSectionName] AS [FinancePostingBucket_FinanceAccountSet_FinanceReportingLine_FinanceStatementSection_FinanceStatementSectionName],
    p72.[GlAccountNumber] AS [GlAccount_GlAccountNumber],
    p72.[GlAccountName] AS [GlAccount_GlAccountName],
    p72.[NormalBalanceCode] AS [GlAccount_NormalBalanceCode],
    p72.[FinancialStatementName] AS [GlAccount_FinancialStatementName],
    p73.[CostElementTypeCode] AS [GlAccount_CostElementType_CostElementTypeCode],
    p73.[CostElementTypeName] AS [GlAccount_CostElementType_CostElementTypeName],
    p74.[CurrencyCode] AS [GlAccount_Currency_CurrencyCode],
    p74.[CurrencyName] AS [GlAccount_Currency_CurrencyName],
    p75.[RegionCode] AS [GlAccount_Currency_CurrencyRegion_RegionCode],
    p75.[RegionName] AS [GlAccount_Currency_CurrencyRegion_RegionName],
    p75.[DefaultCurrencyCode] AS [GlAccount_Currency_CurrencyRegion_DefaultCurrencyCode],
    p76.[PostingTypeCode] AS [GlAccount_PostingType_PostingTypeCode],
    p76.[PostingTypeName] AS [GlAccount_PostingType_PostingTypeName],
    p77.[StatusCode] AS [GlAccount_RecordStatus_StatusCode],
    p77.[StatusName] AS [GlAccount_RecordStatus_StatusName],
    p78.[ReportingLineCode] AS [GlAccount_AccountReportingLine_ReportingLineCode],
    p78.[ReportingLineName] AS [GlAccount_AccountReportingLine_ReportingLineName],
    p78.[OwnerName] AS [GlAccount_AccountReportingLine_OwnerName],
    p79.[StatusCode] AS [GlAccount_AccountReportingLine_RecordStatus_StatusCode],
    p79.[StatusName] AS [GlAccount_AccountReportingLine_RecordStatus_StatusName],
    p80.[AccountSubGroupCode] AS [GlAccount_AccountSubGroup_AccountSubGroupCode],
    p80.[AccountSubGroupName] AS [GlAccount_AccountSubGroup_AccountSubGroupName],
    p81.[AccountGroupCode] AS [GlAccount_AccountSubGroup_AccountGroup_AccountGroupCode],
    p81.[AccountGroupName] AS [GlAccount_AccountSubGroup_AccountGroup_AccountGroupName],
    p82.[AccountCategoryCode] AS [GlAccount_AccountSubGroup_AccountGroup_AccountCategory_AccountCategoryCode],
    p82.[AccountCategoryName] AS [GlAccount_AccountSubGroup_AccountGroup_AccountCategory_AccountCategoryName]
FROM [dim].[FinanceJournalLine] b
LEFT JOIN [ref].[Currency] p1 ON b.[CurrencyKey] = p1.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p2 ON p1.[CurrencyRegionKey] = p2.[CurrencyRegionKey]
LEFT JOIN [ref].[FinancePostingStatus] p3 ON b.[FinancePostingStatusKey] = p3.[FinancePostingStatusKey]
LEFT JOIN [dim].[CostCenter] p4 ON b.[CostCenterKey] = p4.[CostCenterKey]
LEFT JOIN [ref].[BudgetStatus] p5 ON p4.[BudgetStatusKey] = p5.[BudgetStatusKey]
LEFT JOIN [ref].[Currency] p6 ON p4.[CurrencyKey] = p6.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p7 ON p6.[CurrencyRegionKey] = p7.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p8 ON p4.[RecordStatusKey] = p8.[RecordStatusKey]
LEFT JOIN [dim].[CostCenterType] p9 ON p4.[CostCenterTypeKey] = p9.[CostCenterTypeKey]
LEFT JOIN [ref].[RecordStatus] p10 ON p9.[RecordStatusKey] = p10.[RecordStatusKey]
LEFT JOIN [dim].[OrgBusinessUnit] p11 ON p4.[OrgBusinessUnitKey] = p11.[OrgBusinessUnitKey]
LEFT JOIN [dim].[OrgRegion] p12 ON p11.[OrgRegionKey] = p12.[OrgRegionKey]
LEFT JOIN [dim].[OrgDivision] p13 ON p12.[OrgDivisionKey] = p13.[OrgDivisionKey]
LEFT JOIN [dim].[OrgEnterprise] p14 ON p13.[OrgEnterpriseKey] = p14.[OrgEnterpriseKey]
LEFT JOIN [dim].[FinanceJournalHeader] p15 ON b.[FinanceJournalHeaderKey] = p15.[FinanceJournalHeaderKey]
LEFT JOIN [ref].[Currency] p16 ON p15.[CurrencyKey] = p16.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p17 ON p16.[CurrencyRegionKey] = p17.[CurrencyRegionKey]
LEFT JOIN [ref].[FinanceJournalSource] p18 ON p15.[FinanceJournalSourceKey] = p18.[FinanceJournalSourceKey]
LEFT JOIN [ref].[FinancePostingStatus] p19 ON p15.[FinancePostingStatusKey] = p19.[FinancePostingStatusKey]
LEFT JOIN [dim].[BusinessUnit] p20 ON p15.[BusinessUnitKey] = p20.[BusinessUnitKey]
LEFT JOIN [ref].[Currency] p21 ON p20.[CurrencyKey] = p21.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p22 ON p21.[CurrencyRegionKey] = p22.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p23 ON p20.[RecordStatusKey] = p23.[RecordStatusKey]
LEFT JOIN [dim].[BusinessUnitPortfolio] p24 ON p20.[BusinessUnitPortfolioKey] = p24.[BusinessUnitPortfolioKey]
LEFT JOIN [ref].[RecordStatus] p25 ON p24.[RecordStatusKey] = p25.[RecordStatusKey]
LEFT JOIN [dim].[OrgBusinessUnit] p26 ON p20.[OrgBusinessUnitKey] = p26.[OrgBusinessUnitKey]
LEFT JOIN [dim].[OrgRegion] p27 ON p26.[OrgRegionKey] = p27.[OrgRegionKey]
LEFT JOIN [dim].[OrgDivision] p28 ON p27.[OrgDivisionKey] = p28.[OrgDivisionKey]
LEFT JOIN [dim].[OrgEnterprise] p29 ON p28.[OrgEnterpriseKey] = p29.[OrgEnterpriseKey]
LEFT JOIN [dim].[Employee] p30 ON p15.[ApproverEmployeeKey] = p30.[EmployeeKey]
LEFT JOIN [ref].[EmploymentType] p31 ON p30.[EmploymentTypeKey] = p31.[EmploymentTypeKey]
LEFT JOIN [ref].[Language] p32 ON p30.[LanguageKey] = p32.[LanguageKey]
LEFT JOIN [ref].[RecordStatus] p33 ON p30.[RecordStatusKey] = p33.[RecordStatusKey]
LEFT JOIN [ref].[ShiftCode] p34 ON p30.[ShiftCodeKey] = p34.[ShiftCodeKey]
LEFT JOIN [dim].[EmployeeJobRole] p35 ON p30.[EmployeeJobRoleKey] = p35.[EmployeeJobRoleKey]
LEFT JOIN [ref].[LaborGrade] p36 ON p35.[LaborGradeKey] = p36.[LaborGradeKey]
LEFT JOIN [ref].[RecordStatus] p37 ON p35.[RecordStatusKey] = p37.[RecordStatusKey]
LEFT JOIN [dim].[EmployeeJobFamily] p38 ON p35.[EmployeeJobFamilyKey] = p38.[EmployeeJobFamilyKey]
LEFT JOIN [ref].[RecordStatus] p39 ON p38.[RecordStatusKey] = p39.[RecordStatusKey]
LEFT JOIN [dim].[EmployeePayGrade] p40 ON p30.[EmployeePayGradeKey] = p40.[EmployeePayGradeKey]
LEFT JOIN [ref].[Currency] p41 ON p40.[CurrencyKey] = p41.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p42 ON p41.[CurrencyRegionKey] = p42.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p43 ON p40.[RecordStatusKey] = p43.[RecordStatusKey]
LEFT JOIN [dim].[EmployeeUnion] p44 ON p30.[EmployeeUnionKey] = p44.[EmployeeUnionKey]
LEFT JOIN [ref].[Country] p45 ON p44.[CountryKey] = p45.[CountryKey]
LEFT JOIN [ref].[Region] p46 ON p45.[RegionKey] = p46.[RegionKey]
LEFT JOIN [ref].[Continent] p47 ON p46.[ContinentKey] = p47.[ContinentKey]
LEFT JOIN [ref].[RecordStatus] p48 ON p44.[RecordStatusKey] = p48.[RecordStatusKey]
LEFT JOIN [dim].[Employee] p49 ON p15.[PreparerEmployeeKey] = p49.[EmployeeKey]
LEFT JOIN [ref].[EmploymentType] p50 ON p49.[EmploymentTypeKey] = p50.[EmploymentTypeKey]
LEFT JOIN [ref].[Language] p51 ON p49.[LanguageKey] = p51.[LanguageKey]
LEFT JOIN [ref].[RecordStatus] p52 ON p49.[RecordStatusKey] = p52.[RecordStatusKey]
LEFT JOIN [ref].[ShiftCode] p53 ON p49.[ShiftCodeKey] = p53.[ShiftCodeKey]
LEFT JOIN [dim].[EmployeeJobRole] p54 ON p49.[EmployeeJobRoleKey] = p54.[EmployeeJobRoleKey]
LEFT JOIN [ref].[LaborGrade] p55 ON p54.[LaborGradeKey] = p55.[LaborGradeKey]
LEFT JOIN [ref].[RecordStatus] p56 ON p54.[RecordStatusKey] = p56.[RecordStatusKey]
LEFT JOIN [dim].[EmployeeJobFamily] p57 ON p54.[EmployeeJobFamilyKey] = p57.[EmployeeJobFamilyKey]
LEFT JOIN [ref].[RecordStatus] p58 ON p57.[RecordStatusKey] = p58.[RecordStatusKey]
LEFT JOIN [dim].[EmployeePayGrade] p59 ON p49.[EmployeePayGradeKey] = p59.[EmployeePayGradeKey]
LEFT JOIN [ref].[Currency] p60 ON p59.[CurrencyKey] = p60.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p61 ON p60.[CurrencyRegionKey] = p61.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p62 ON p59.[RecordStatusKey] = p62.[RecordStatusKey]
LEFT JOIN [dim].[EmployeeUnion] p63 ON p49.[EmployeeUnionKey] = p63.[EmployeeUnionKey]
LEFT JOIN [ref].[Country] p64 ON p63.[CountryKey] = p64.[CountryKey]
LEFT JOIN [ref].[Region] p65 ON p64.[RegionKey] = p65.[RegionKey]
LEFT JOIN [ref].[Continent] p66 ON p65.[ContinentKey] = p66.[ContinentKey]
LEFT JOIN [ref].[RecordStatus] p67 ON p63.[RecordStatusKey] = p67.[RecordStatusKey]
LEFT JOIN [dim].[FinancePostingBucket] p68 ON b.[FinancePostingBucketKey] = p68.[FinancePostingBucketKey]
LEFT JOIN [dim].[FinanceAccountSet] p69 ON p68.[FinanceAccountSetKey] = p69.[FinanceAccountSetKey]
LEFT JOIN [dim].[FinanceReportingLine] p70 ON p69.[FinanceReportingLineKey] = p70.[FinanceReportingLineKey]
LEFT JOIN [dim].[FinanceStatementSection] p71 ON p70.[FinanceStatementSectionKey] = p71.[FinanceStatementSectionKey]
LEFT JOIN [dim].[GlAccount] p72 ON b.[GlAccountKey] = p72.[GlAccountKey]
LEFT JOIN [ref].[CostElementType] p73 ON p72.[CostElementTypeKey] = p73.[CostElementTypeKey]
LEFT JOIN [ref].[Currency] p74 ON p72.[CurrencyKey] = p74.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p75 ON p74.[CurrencyRegionKey] = p75.[CurrencyRegionKey]
LEFT JOIN [ref].[PostingType] p76 ON p72.[PostingTypeKey] = p76.[PostingTypeKey]
LEFT JOIN [ref].[RecordStatus] p77 ON p72.[RecordStatusKey] = p77.[RecordStatusKey]
LEFT JOIN [dim].[AccountReportingLine] p78 ON p72.[AccountReportingLineKey] = p78.[AccountReportingLineKey]
LEFT JOIN [ref].[RecordStatus] p79 ON p78.[RecordStatusKey] = p79.[RecordStatusKey]
LEFT JOIN [dim].[AccountSubGroup] p80 ON p72.[AccountSubGroupKey] = p80.[AccountSubGroupKey]
LEFT JOIN [dim].[AccountGroup] p81 ON p80.[AccountGroupKey] = p81.[AccountGroupKey]
LEFT JOIN [dim].[AccountCategory] p82 ON p81.[AccountCategoryKey] = p82.[AccountCategoryKey]
GO

CREATE OR ALTER VIEW [dim].[vwDimFinancePlanningVersion] AS
SELECT
    b.[FinancePlanningVersionKey] AS [FinancePlanningVersionKey],
    b.[PlanningVersionCode] AS [PlanningVersionCode],
    b.[BusinessUnitKey] AS [BusinessUnitKey],
    b.[FinanceScenarioTypeKey] AS [FinanceScenarioTypeKey],
    b.[CurrencyKey] AS [CurrencyKey],
    b.[PlanningVersionName] AS [PlanningVersionName],
    b.[VersionStartDate] AS [VersionStartDate],
    b.[VersionEndDate] AS [VersionEndDate],
    b.[SourceSystemKey] AS [SourceSystemKey],
    b.[BatchId] AS [BatchId],
    b.[LoadedAtUtc] AS [LoadedAtUtc],
    b.[EffectiveFromUtc] AS [EffectiveFromUtc],
    b.[EffectiveToUtc] AS [EffectiveToUtc],
    b.[IsCurrent] AS [IsCurrent],
    b.[RowHash] AS [RowHash],
    p1.[CurrencyCode] AS [Currency_CurrencyCode],
    p1.[CurrencyName] AS [Currency_CurrencyName],
    p2.[RegionCode] AS [Currency_CurrencyRegion_RegionCode],
    p2.[RegionName] AS [Currency_CurrencyRegion_RegionName],
    p2.[DefaultCurrencyCode] AS [Currency_CurrencyRegion_DefaultCurrencyCode],
    p3.[ScenarioTypeCode] AS [FinanceScenarioType_ScenarioTypeCode],
    p3.[ScenarioTypeName] AS [FinanceScenarioType_ScenarioTypeName],
    p4.[BusinessUnitCode] AS [BusinessUnit_BusinessUnitCode],
    p4.[BusinessUnitName] AS [BusinessUnit_BusinessUnitName],
    p4.[PresidentName] AS [BusinessUnit_PresidentName],
    p4.[PrimaryPlantCode] AS [BusinessUnit_PrimaryPlantCode],
    p4.[DefaultCurrencyCode] AS [BusinessUnit_DefaultCurrencyCode],
    p4.[ProfitCenterCode] AS [BusinessUnit_ProfitCenterCode],
    p5.[CurrencyCode] AS [BusinessUnit_Currency_CurrencyCode],
    p5.[CurrencyName] AS [BusinessUnit_Currency_CurrencyName],
    p6.[RegionCode] AS [BusinessUnit_Currency_CurrencyRegion_RegionCode],
    p6.[RegionName] AS [BusinessUnit_Currency_CurrencyRegion_RegionName],
    p6.[DefaultCurrencyCode] AS [BusinessUnit_Currency_CurrencyRegion_DefaultCurrencyCode],
    p7.[StatusCode] AS [BusinessUnit_RecordStatus_StatusCode],
    p7.[StatusName] AS [BusinessUnit_RecordStatus_StatusName],
    p8.[PortfolioCode] AS [BusinessUnit_BusinessUnitPortfolio_PortfolioCode],
    p8.[PortfolioName] AS [BusinessUnit_BusinessUnitPortfolio_PortfolioName],
    p8.[OwnerName] AS [BusinessUnit_BusinessUnitPortfolio_OwnerName],
    p9.[StatusCode] AS [BusinessUnit_BusinessUnitPortfolio_RecordStatus_StatusCode],
    p9.[StatusName] AS [BusinessUnit_BusinessUnitPortfolio_RecordStatus_StatusName],
    p10.[OrgBusinessUnitCode] AS [BusinessUnit_OrgBusinessUnit_OrgBusinessUnitCode],
    p10.[OrgBusinessUnitName] AS [BusinessUnit_OrgBusinessUnit_OrgBusinessUnitName],
    p11.[OrgRegionCode] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgRegionCode],
    p11.[OrgRegionName] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgRegionName],
    p12.[OrgDivisionCode] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionCode],
    p12.[OrgDivisionName] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionName],
    p13.[OrgEnterpriseCode] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseCode],
    p13.[OrgEnterpriseName] AS [BusinessUnit_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseName]
FROM [dim].[FinancePlanningVersion] b
LEFT JOIN [ref].[Currency] p1 ON b.[CurrencyKey] = p1.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p2 ON p1.[CurrencyRegionKey] = p2.[CurrencyRegionKey]
LEFT JOIN [ref].[FinanceScenarioType] p3 ON b.[FinanceScenarioTypeKey] = p3.[FinanceScenarioTypeKey]
LEFT JOIN [dim].[BusinessUnit] p4 ON b.[BusinessUnitKey] = p4.[BusinessUnitKey]
LEFT JOIN [ref].[Currency] p5 ON p4.[CurrencyKey] = p5.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p6 ON p5.[CurrencyRegionKey] = p6.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p7 ON p4.[RecordStatusKey] = p7.[RecordStatusKey]
LEFT JOIN [dim].[BusinessUnitPortfolio] p8 ON p4.[BusinessUnitPortfolioKey] = p8.[BusinessUnitPortfolioKey]
LEFT JOIN [ref].[RecordStatus] p9 ON p8.[RecordStatusKey] = p9.[RecordStatusKey]
LEFT JOIN [dim].[OrgBusinessUnit] p10 ON p4.[OrgBusinessUnitKey] = p10.[OrgBusinessUnitKey]
LEFT JOIN [dim].[OrgRegion] p11 ON p10.[OrgRegionKey] = p11.[OrgRegionKey]
LEFT JOIN [dim].[OrgDivision] p12 ON p11.[OrgDivisionKey] = p12.[OrgDivisionKey]
LEFT JOIN [dim].[OrgEnterprise] p13 ON p12.[OrgEnterpriseKey] = p13.[OrgEnterpriseKey]
GO

CREATE OR ALTER VIEW [dim].[vwDimFinanceProductCostVersion] AS
SELECT
    b.[FinanceProductCostVersionKey] AS [FinanceProductCostVersionKey],
    b.[ProductCostVersionCode] AS [ProductCostVersionCode],
    b.[ProductKey] AS [ProductKey],
    b.[PlantKey] AS [PlantKey],
    b.[FinanceCostComponentDetailKey] AS [FinanceCostComponentDetailKey],
    b.[FinanceCostingMethodKey] AS [FinanceCostingMethodKey],
    b.[CurrencyKey] AS [CurrencyKey],
    b.[CostVersionName] AS [CostVersionName],
    b.[EffectiveDate] AS [EffectiveDate],
    b.[ExpirationDate] AS [ExpirationDate],
    b.[SourceSystemKey] AS [SourceSystemKey],
    b.[BatchId] AS [BatchId],
    b.[LoadedAtUtc] AS [LoadedAtUtc],
    b.[EffectiveFromUtc] AS [EffectiveFromUtc],
    b.[EffectiveToUtc] AS [EffectiveToUtc],
    b.[IsCurrent] AS [IsCurrent],
    b.[RowHash] AS [RowHash],
    p1.[CurrencyCode] AS [Currency_CurrencyCode],
    p1.[CurrencyName] AS [Currency_CurrencyName],
    p2.[RegionCode] AS [Currency_CurrencyRegion_RegionCode],
    p2.[RegionName] AS [Currency_CurrencyRegion_RegionName],
    p2.[DefaultCurrencyCode] AS [Currency_CurrencyRegion_DefaultCurrencyCode],
    p3.[CostingMethodCode] AS [FinanceCostingMethod_CostingMethodCode],
    p3.[CostingMethodName] AS [FinanceCostingMethod_CostingMethodName],
    p4.[FinanceCostComponentDetailCode] AS [FinanceCostComponentDetail_FinanceCostComponentDetailCode],
    p4.[FinanceCostComponentDetailName] AS [FinanceCostComponentDetail_FinanceCostComponentDetailName],
    p5.[FinanceCostComponentCode] AS [FinanceCostComponentDetail_FinanceCostComponent_FinanceCostComponentCode],
    p5.[FinanceCostComponentName] AS [FinanceCostComponentDetail_FinanceCostComponent_FinanceCostComponentName],
    p6.[FinanceCostComponentGroupCode] AS [FinanceCostComponentDetail_FinanceCostComponent_FinanceCostComponentGroup_FinanceCostComponentGroupCode],
    p6.[FinanceCostComponentGroupName] AS [FinanceCostComponentDetail_FinanceCostComponent_FinanceCostComponentGroup_FinanceCostComponentGroupName],
    p7.[FinanceCostComponentClassCode] AS [FinanceCostComponentDetail_FinanceCostComponent_FinanceCostComponentGroup_FinanceCostComponentClass_FinanceCostComponentClassCod],
    p7.[FinanceCostComponentClassName] AS [FinanceCostComponentDetail_FinanceCostComponent_FinanceCostComponentGroup_FinanceCostComponentClass_FinanceCostComponentClassNam],
    p8.[PlantCode] AS [Plant_PlantCode],
    p8.[PlantName] AS [Plant_PlantName],
    p8.[LegalEntityCode] AS [Plant_LegalEntityCode],
    p8.[PlantManagerName] AS [Plant_PlantManagerName],
    p8.[DefaultCurrencyCode] AS [Plant_DefaultCurrencyCode],
    p8.[TimeZoneName] AS [Plant_TimeZoneName],
    p9.[CountryCode] AS [Plant_Country_CountryCode],
    p9.[CountryName] AS [Plant_Country_CountryName],
    p10.[RegionCode] AS [Plant_Country_Region_RegionCode],
    p10.[RegionName] AS [Plant_Country_Region_RegionName],
    p11.[ContinentCode] AS [Plant_Country_Region_Continent_ContinentCode],
    p11.[ContinentName] AS [Plant_Country_Region_Continent_ContinentName],
    p12.[CurrencyCode] AS [Plant_Currency_CurrencyCode],
    p12.[CurrencyName] AS [Plant_Currency_CurrencyName],
    p13.[RegionCode] AS [Plant_Currency_CurrencyRegion_RegionCode],
    p13.[RegionName] AS [Plant_Currency_CurrencyRegion_RegionName],
    p13.[DefaultCurrencyCode] AS [Plant_Currency_CurrencyRegion_DefaultCurrencyCode],
    p14.[StatusCode] AS [Plant_RecordStatus_StatusCode],
    p14.[StatusName] AS [Plant_RecordStatus_StatusName],
    p15.[TimeZoneCode] AS [Plant_TimeZone_TimeZoneCode],
    p15.[TimeZoneName] AS [Plant_TimeZone_TimeZoneName],
    p16.[RegionCode] AS [Plant_TimeZone_Region_RegionCode],
    p16.[RegionName] AS [Plant_TimeZone_Region_RegionName],
    p17.[ContinentCode] AS [Plant_TimeZone_Region_Continent_ContinentCode],
    p17.[ContinentName] AS [Plant_TimeZone_Region_Continent_ContinentName],
    p18.[GeoPostalCodeCode] AS [Plant_GeoPostalCode_GeoPostalCodeCode],
    p18.[GeoPostalCodeName] AS [Plant_GeoPostalCode_GeoPostalCodeName],
    p19.[GeoCityCode] AS [Plant_GeoPostalCode_GeoCity_GeoCityCode],
    p19.[GeoCityName] AS [Plant_GeoPostalCode_GeoCity_GeoCityName],
    p20.[GeoStateProvinceCode] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoStateProvinceCode],
    p20.[GeoStateProvinceName] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoStateProvinceName],
    p21.[GeoCountryCode] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoCountryCode],
    p21.[GeoCountryName] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoCountryName],
    p22.[GeoContinentCode] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentCode],
    p22.[GeoContinentName] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentName],
    p23.[OrgBusinessUnitCode] AS [Plant_OrgBusinessUnit_OrgBusinessUnitCode],
    p23.[OrgBusinessUnitName] AS [Plant_OrgBusinessUnit_OrgBusinessUnitName],
    p24.[OrgRegionCode] AS [Plant_OrgBusinessUnit_OrgRegion_OrgRegionCode],
    p24.[OrgRegionName] AS [Plant_OrgBusinessUnit_OrgRegion_OrgRegionName],
    p25.[OrgDivisionCode] AS [Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionCode],
    p25.[OrgDivisionName] AS [Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionName],
    p26.[OrgEnterpriseCode] AS [Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseCode],
    p26.[OrgEnterpriseName] AS [Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseName],
    p27.[CampusCode] AS [Plant_PlantCampus_CampusCode],
    p27.[CampusName] AS [Plant_PlantCampus_CampusName],
    p27.[OwnerName] AS [Plant_PlantCampus_OwnerName],
    p28.[StatusCode] AS [Plant_PlantCampus_RecordStatus_StatusCode],
    p28.[StatusName] AS [Plant_PlantCampus_RecordStatus_StatusName],
    p29.[GeoCityCode] AS [Plant_PlantCampus_GeoCity_GeoCityCode],
    p29.[GeoCityName] AS [Plant_PlantCampus_GeoCity_GeoCityName],
    p30.[GeoStateProvinceCode] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoStateProvinceCode],
    p30.[GeoStateProvinceName] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoStateProvinceName],
    p31.[GeoCountryCode] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoCountryCode],
    p31.[GeoCountryName] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoCountryName],
    p32.[GeoContinentCode] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentCode],
    p32.[GeoContinentName] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentName],
    p33.[PlantTypeCode] AS [Plant_PlantType_PlantTypeCode],
    p33.[PlantTypeName] AS [Plant_PlantType_PlantTypeName],
    p33.[OwnerName] AS [Plant_PlantType_OwnerName],
    p34.[StatusCode] AS [Plant_PlantType_RecordStatus_StatusCode],
    p34.[StatusName] AS [Plant_PlantType_RecordStatus_StatusName],
    p35.[UomCode] AS [Plant_PlantType_UnitOfMeasure_UomCode],
    p35.[UomName] AS [Plant_PlantType_UnitOfMeasure_UomName],
    p36.[ClassCode] AS [Plant_PlantType_UnitOfMeasure_UnitOfMeasureClass_ClassCode],
    p36.[ClassName] AS [Plant_PlantType_UnitOfMeasure_UnitOfMeasureClass_ClassName],
    p36.[BaseUnitCode] AS [Plant_PlantType_UnitOfMeasure_UnitOfMeasureClass_BaseUnitCode],
    p37.[ProductNumber] AS [Product_ProductNumber],
    p37.[ProductName] AS [Product_ProductName],
    p37.[RevisionCode] AS [Product_RevisionCode],
    p37.[MakeBuyCode] AS [Product_MakeBuyCode],
    p38.[HazardClassCode] AS [Product_HazardClass_HazardClassCode],
    p38.[HazardClassName] AS [Product_HazardClass_HazardClassName],
    p39.[StandardCode] AS [Product_HazardClass_ComplianceStandard_StandardCode],
    p39.[ComplianceStandardName] AS [Product_HazardClass_ComplianceStandard_ComplianceStandardName],
    p40.[MeasurementSystemCode] AS [Product_MeasurementSystem_MeasurementSystemCode],
    p40.[MeasurementSystemName] AS [Product_MeasurementSystem_MeasurementSystemName],
    p40.[DefaultLengthUomCode] AS [Product_MeasurementSystem_DefaultLengthUomCode],
    p40.[DefaultMassUomCode] AS [Product_MeasurementSystem_DefaultMassUomCode],
    p41.[StatusCode] AS [Product_RecordStatus_StatusCode],
    p41.[StatusName] AS [Product_RecordStatus_StatusName],
    p42.[UomCode] AS [Product_UnitOfMeasure_UomCode],
    p42.[UomName] AS [Product_UnitOfMeasure_UomName],
    p43.[ClassCode] AS [Product_UnitOfMeasure_UnitOfMeasureClass_ClassCode],
    p43.[ClassName] AS [Product_UnitOfMeasure_UnitOfMeasureClass_ClassName],
    p43.[BaseUnitCode] AS [Product_UnitOfMeasure_UnitOfMeasureClass_BaseUnitCode],
    p44.[BrandCode] AS [Product_ProductBrand_BrandCode],
    p44.[BrandName] AS [Product_ProductBrand_BrandName],
    p44.[OwnerName] AS [Product_ProductBrand_OwnerName],
    p45.[StatusCode] AS [Product_ProductBrand_RecordStatus_StatusCode],
    p45.[StatusName] AS [Product_ProductBrand_RecordStatus_StatusName],
    p46.[BrandOwnerCode] AS [Product_ProductBrand_BrandOwner_BrandOwnerCode],
    p46.[BrandOwnerName] AS [Product_ProductBrand_BrandOwner_BrandOwnerName],
    p46.[OwnerName] AS [Product_ProductBrand_BrandOwner_OwnerName],
    p47.[CountryCode] AS [Product_ProductBrand_BrandOwner_Country_CountryCode],
    p47.[CountryName] AS [Product_ProductBrand_BrandOwner_Country_CountryName],
    p48.[RegionCode] AS [Product_ProductBrand_BrandOwner_Country_Region_RegionCode],
    p48.[RegionName] AS [Product_ProductBrand_BrandOwner_Country_Region_RegionName],
    p49.[ContinentCode] AS [Product_ProductBrand_BrandOwner_Country_Region_Continent_ContinentCode],
    p49.[ContinentName] AS [Product_ProductBrand_BrandOwner_Country_Region_Continent_ContinentName],
    p50.[StatusCode] AS [Product_ProductBrand_BrandOwner_RecordStatus_StatusCode],
    p50.[StatusName] AS [Product_ProductBrand_BrandOwner_RecordStatus_StatusName],
    p51.[CertificationCode] AS [Product_ProductCertification_CertificationCode],
    p51.[CertificationName] AS [Product_ProductCertification_CertificationName],
    p51.[OwnerName] AS [Product_ProductCertification_OwnerName],
    p52.[StandardCode] AS [Product_ProductCertification_ComplianceStandard_StandardCode],
    p52.[ComplianceStandardName] AS [Product_ProductCertification_ComplianceStandard_ComplianceStandardName],
    p53.[StatusCode] AS [Product_ProductCertification_RecordStatus_StatusCode],
    p53.[StatusName] AS [Product_ProductCertification_RecordStatus_StatusName],
    p54.[LifecyclePhaseCode] AS [Product_ProductLifecyclePhase_LifecyclePhaseCode],
    p54.[LifecyclePhaseName] AS [Product_ProductLifecyclePhase_LifecyclePhaseName],
    p54.[OwnerName] AS [Product_ProductLifecyclePhase_OwnerName],
    p55.[ApprovalStatusCode] AS [Product_ProductLifecyclePhase_ApprovalStatus_ApprovalStatusCode],
    p55.[ApprovalStatusName] AS [Product_ProductLifecyclePhase_ApprovalStatus_ApprovalStatusName],
    p56.[StatusCode] AS [Product_ProductLifecyclePhase_RecordStatus_StatusCode],
    p56.[StatusName] AS [Product_ProductLifecyclePhase_RecordStatus_StatusName],
    p57.[ProductSubfamilyCode] AS [Product_ProductSubfamily_ProductSubfamilyCode],
    p57.[ProductSubfamilyName] AS [Product_ProductSubfamily_ProductSubfamilyName],
    p58.[ProductFamilyCode] AS [Product_ProductSubfamily_ProductFamily_ProductFamilyCode],
    p58.[ProductFamilyName] AS [Product_ProductSubfamily_ProductFamily_ProductFamilyName],
    p59.[ProductLineCode] AS [Product_ProductSubfamily_ProductFamily_ProductLine_ProductLineCode],
    p59.[ProductLineName] AS [Product_ProductSubfamily_ProductFamily_ProductLine_ProductLineName],
    p60.[ProductDivisionCode] AS [Product_ProductSubfamily_ProductFamily_ProductLine_ProductDivision_ProductDivisionCode],
    p60.[ProductDivisionName] AS [Product_ProductSubfamily_ProductFamily_ProductLine_ProductDivision_ProductDivisionName]
FROM [dim].[FinanceProductCostVersion] b
LEFT JOIN [ref].[Currency] p1 ON b.[CurrencyKey] = p1.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p2 ON p1.[CurrencyRegionKey] = p2.[CurrencyRegionKey]
LEFT JOIN [ref].[FinanceCostingMethod] p3 ON b.[FinanceCostingMethodKey] = p3.[FinanceCostingMethodKey]
LEFT JOIN [dim].[FinanceCostComponentDetail] p4 ON b.[FinanceCostComponentDetailKey] = p4.[FinanceCostComponentDetailKey]
LEFT JOIN [dim].[FinanceCostComponent] p5 ON p4.[FinanceCostComponentKey] = p5.[FinanceCostComponentKey]
LEFT JOIN [dim].[FinanceCostComponentGroup] p6 ON p5.[FinanceCostComponentGroupKey] = p6.[FinanceCostComponentGroupKey]
LEFT JOIN [dim].[FinanceCostComponentClass] p7 ON p6.[FinanceCostComponentClassKey] = p7.[FinanceCostComponentClassKey]
LEFT JOIN [dim].[Plant] p8 ON b.[PlantKey] = p8.[PlantKey]
LEFT JOIN [ref].[Country] p9 ON p8.[CountryKey] = p9.[CountryKey]
LEFT JOIN [ref].[Region] p10 ON p9.[RegionKey] = p10.[RegionKey]
LEFT JOIN [ref].[Continent] p11 ON p10.[ContinentKey] = p11.[ContinentKey]
LEFT JOIN [ref].[Currency] p12 ON p8.[CurrencyKey] = p12.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p13 ON p12.[CurrencyRegionKey] = p13.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p14 ON p8.[RecordStatusKey] = p14.[RecordStatusKey]
LEFT JOIN [ref].[TimeZone] p15 ON p8.[TimeZoneKey] = p15.[TimeZoneKey]
LEFT JOIN [ref].[Region] p16 ON p15.[RegionKey] = p16.[RegionKey]
LEFT JOIN [ref].[Continent] p17 ON p16.[ContinentKey] = p17.[ContinentKey]
LEFT JOIN [dim].[GeoPostalCode] p18 ON p8.[GeoPostalCodeKey] = p18.[GeoPostalCodeKey]
LEFT JOIN [dim].[GeoCity] p19 ON p18.[GeoCityKey] = p19.[GeoCityKey]
LEFT JOIN [dim].[GeoStateProvince] p20 ON p19.[GeoStateProvinceKey] = p20.[GeoStateProvinceKey]
LEFT JOIN [dim].[GeoCountry] p21 ON p20.[GeoCountryKey] = p21.[GeoCountryKey]
LEFT JOIN [dim].[GeoContinent] p22 ON p21.[GeoContinentKey] = p22.[GeoContinentKey]
LEFT JOIN [dim].[OrgBusinessUnit] p23 ON p8.[OrgBusinessUnitKey] = p23.[OrgBusinessUnitKey]
LEFT JOIN [dim].[OrgRegion] p24 ON p23.[OrgRegionKey] = p24.[OrgRegionKey]
LEFT JOIN [dim].[OrgDivision] p25 ON p24.[OrgDivisionKey] = p25.[OrgDivisionKey]
LEFT JOIN [dim].[OrgEnterprise] p26 ON p25.[OrgEnterpriseKey] = p26.[OrgEnterpriseKey]
LEFT JOIN [dim].[PlantCampus] p27 ON p8.[PlantCampusKey] = p27.[PlantCampusKey]
LEFT JOIN [ref].[RecordStatus] p28 ON p27.[RecordStatusKey] = p28.[RecordStatusKey]
LEFT JOIN [dim].[GeoCity] p29 ON p27.[GeoCityKey] = p29.[GeoCityKey]
LEFT JOIN [dim].[GeoStateProvince] p30 ON p29.[GeoStateProvinceKey] = p30.[GeoStateProvinceKey]
LEFT JOIN [dim].[GeoCountry] p31 ON p30.[GeoCountryKey] = p31.[GeoCountryKey]
LEFT JOIN [dim].[GeoContinent] p32 ON p31.[GeoContinentKey] = p32.[GeoContinentKey]
LEFT JOIN [dim].[PlantType] p33 ON p8.[PlantTypeKey] = p33.[PlantTypeKey]
LEFT JOIN [ref].[RecordStatus] p34 ON p33.[RecordStatusKey] = p34.[RecordStatusKey]
LEFT JOIN [ref].[UnitOfMeasure] p35 ON p33.[UnitOfMeasureKey] = p35.[UnitOfMeasureKey]
LEFT JOIN [ref].[UnitOfMeasureClass] p36 ON p35.[UnitOfMeasureClassKey] = p36.[UnitOfMeasureClassKey]
LEFT JOIN [dim].[Product] p37 ON b.[ProductKey] = p37.[ProductKey]
LEFT JOIN [ref].[HazardClass] p38 ON p37.[HazardClassKey] = p38.[HazardClassKey]
LEFT JOIN [ref].[ComplianceStandard] p39 ON p38.[ComplianceStandardKey] = p39.[ComplianceStandardKey]
LEFT JOIN [ref].[MeasurementSystem] p40 ON p37.[MeasurementSystemKey] = p40.[MeasurementSystemKey]
LEFT JOIN [ref].[RecordStatus] p41 ON p37.[RecordStatusKey] = p41.[RecordStatusKey]
LEFT JOIN [ref].[UnitOfMeasure] p42 ON p37.[UnitOfMeasureKey] = p42.[UnitOfMeasureKey]
LEFT JOIN [ref].[UnitOfMeasureClass] p43 ON p42.[UnitOfMeasureClassKey] = p43.[UnitOfMeasureClassKey]
LEFT JOIN [dim].[ProductBrand] p44 ON p37.[ProductBrandKey] = p44.[ProductBrandKey]
LEFT JOIN [ref].[RecordStatus] p45 ON p44.[RecordStatusKey] = p45.[RecordStatusKey]
LEFT JOIN [dim].[BrandOwner] p46 ON p44.[BrandOwnerKey] = p46.[BrandOwnerKey]
LEFT JOIN [ref].[Country] p47 ON p46.[CountryKey] = p47.[CountryKey]
LEFT JOIN [ref].[Region] p48 ON p47.[RegionKey] = p48.[RegionKey]
LEFT JOIN [ref].[Continent] p49 ON p48.[ContinentKey] = p49.[ContinentKey]
LEFT JOIN [ref].[RecordStatus] p50 ON p46.[RecordStatusKey] = p50.[RecordStatusKey]
LEFT JOIN [dim].[ProductCertification] p51 ON p37.[ProductCertificationKey] = p51.[ProductCertificationKey]
LEFT JOIN [ref].[ComplianceStandard] p52 ON p51.[ComplianceStandardKey] = p52.[ComplianceStandardKey]
LEFT JOIN [ref].[RecordStatus] p53 ON p51.[RecordStatusKey] = p53.[RecordStatusKey]
LEFT JOIN [dim].[ProductLifecyclePhase] p54 ON p37.[ProductLifecyclePhaseKey] = p54.[ProductLifecyclePhaseKey]
LEFT JOIN [ref].[ApprovalStatus] p55 ON p54.[ApprovalStatusKey] = p55.[ApprovalStatusKey]
LEFT JOIN [ref].[RecordStatus] p56 ON p54.[RecordStatusKey] = p56.[RecordStatusKey]
LEFT JOIN [dim].[ProductSubfamily] p57 ON p37.[ProductSubfamilyKey] = p57.[ProductSubfamilyKey]
LEFT JOIN [dim].[ProductFamily] p58 ON p57.[ProductFamilyKey] = p58.[ProductFamilyKey]
LEFT JOIN [dim].[ProductLine] p59 ON p58.[ProductLineKey] = p59.[ProductLineKey]
LEFT JOIN [dim].[ProductDivision] p60 ON p59.[ProductDivisionKey] = p60.[ProductDivisionKey]
GO

CREATE OR ALTER VIEW [dim].[vwDimFinanceProductionSettlement] AS
SELECT
    b.[FinanceProductionSettlementKey] AS [FinanceProductionSettlementKey],
    b.[ProductionSettlementNumber] AS [ProductionSettlementNumber],
    b.[ProductKey] AS [ProductKey],
    b.[PlantKey] AS [PlantKey],
    b.[WorkCenterKey] AS [WorkCenterKey],
    b.[CostCenterKey] AS [CostCenterKey],
    b.[FinancePostingStatusKey] AS [FinancePostingStatusKey],
    b.[SettlementName] AS [SettlementName],
    b.[SettlementPeriodCode] AS [SettlementPeriodCode],
    b.[IsFinalSettlement] AS [IsFinalSettlement],
    b.[SourceSystemKey] AS [SourceSystemKey],
    b.[BatchId] AS [BatchId],
    b.[LoadedAtUtc] AS [LoadedAtUtc],
    b.[EffectiveFromUtc] AS [EffectiveFromUtc],
    b.[EffectiveToUtc] AS [EffectiveToUtc],
    b.[IsCurrent] AS [IsCurrent],
    b.[RowHash] AS [RowHash],
    p1.[PostingStatusCode] AS [FinancePostingStatus_PostingStatusCode],
    p1.[PostingStatusName] AS [FinancePostingStatus_PostingStatusName],
    p2.[CostCenterCode] AS [CostCenter_CostCenterCode],
    p2.[CostCenterName] AS [CostCenter_CostCenterName],
    p2.[BudgetOwnerName] AS [CostCenter_BudgetOwnerName],
    p3.[StatusCode] AS [CostCenter_BudgetStatus_StatusCode],
    p3.[BudgetStatusName] AS [CostCenter_BudgetStatus_BudgetStatusName],
    p4.[CurrencyCode] AS [CostCenter_Currency_CurrencyCode],
    p4.[CurrencyName] AS [CostCenter_Currency_CurrencyName],
    p5.[RegionCode] AS [CostCenter_Currency_CurrencyRegion_RegionCode],
    p5.[RegionName] AS [CostCenter_Currency_CurrencyRegion_RegionName],
    p5.[DefaultCurrencyCode] AS [CostCenter_Currency_CurrencyRegion_DefaultCurrencyCode],
    p6.[StatusCode] AS [CostCenter_RecordStatus_StatusCode],
    p6.[StatusName] AS [CostCenter_RecordStatus_StatusName],
    p7.[CostCenterTypeCode] AS [CostCenter_CostCenterType_CostCenterTypeCode],
    p7.[CostCenterTypeName] AS [CostCenter_CostCenterType_CostCenterTypeName],
    p7.[OwnerName] AS [CostCenter_CostCenterType_OwnerName],
    p8.[StatusCode] AS [CostCenter_CostCenterType_RecordStatus_StatusCode],
    p8.[StatusName] AS [CostCenter_CostCenterType_RecordStatus_StatusName],
    p9.[OrgBusinessUnitCode] AS [CostCenter_OrgBusinessUnit_OrgBusinessUnitCode],
    p9.[OrgBusinessUnitName] AS [CostCenter_OrgBusinessUnit_OrgBusinessUnitName],
    p10.[OrgRegionCode] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgRegionCode],
    p10.[OrgRegionName] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgRegionName],
    p11.[OrgDivisionCode] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionCode],
    p11.[OrgDivisionName] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionName],
    p12.[OrgEnterpriseCode] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseCode],
    p12.[OrgEnterpriseName] AS [CostCenter_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseName],
    p13.[PlantCode] AS [Plant_PlantCode],
    p13.[PlantName] AS [Plant_PlantName],
    p13.[LegalEntityCode] AS [Plant_LegalEntityCode],
    p13.[PlantManagerName] AS [Plant_PlantManagerName],
    p13.[DefaultCurrencyCode] AS [Plant_DefaultCurrencyCode],
    p13.[TimeZoneName] AS [Plant_TimeZoneName],
    p14.[CountryCode] AS [Plant_Country_CountryCode],
    p14.[CountryName] AS [Plant_Country_CountryName],
    p15.[RegionCode] AS [Plant_Country_Region_RegionCode],
    p15.[RegionName] AS [Plant_Country_Region_RegionName],
    p16.[ContinentCode] AS [Plant_Country_Region_Continent_ContinentCode],
    p16.[ContinentName] AS [Plant_Country_Region_Continent_ContinentName],
    p17.[CurrencyCode] AS [Plant_Currency_CurrencyCode],
    p17.[CurrencyName] AS [Plant_Currency_CurrencyName],
    p18.[RegionCode] AS [Plant_Currency_CurrencyRegion_RegionCode],
    p18.[RegionName] AS [Plant_Currency_CurrencyRegion_RegionName],
    p18.[DefaultCurrencyCode] AS [Plant_Currency_CurrencyRegion_DefaultCurrencyCode],
    p19.[StatusCode] AS [Plant_RecordStatus_StatusCode],
    p19.[StatusName] AS [Plant_RecordStatus_StatusName],
    p20.[TimeZoneCode] AS [Plant_TimeZone_TimeZoneCode],
    p20.[TimeZoneName] AS [Plant_TimeZone_TimeZoneName],
    p21.[RegionCode] AS [Plant_TimeZone_Region_RegionCode],
    p21.[RegionName] AS [Plant_TimeZone_Region_RegionName],
    p22.[ContinentCode] AS [Plant_TimeZone_Region_Continent_ContinentCode],
    p22.[ContinentName] AS [Plant_TimeZone_Region_Continent_ContinentName],
    p23.[GeoPostalCodeCode] AS [Plant_GeoPostalCode_GeoPostalCodeCode],
    p23.[GeoPostalCodeName] AS [Plant_GeoPostalCode_GeoPostalCodeName],
    p24.[GeoCityCode] AS [Plant_GeoPostalCode_GeoCity_GeoCityCode],
    p24.[GeoCityName] AS [Plant_GeoPostalCode_GeoCity_GeoCityName],
    p25.[GeoStateProvinceCode] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoStateProvinceCode],
    p25.[GeoStateProvinceName] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoStateProvinceName],
    p26.[GeoCountryCode] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoCountryCode],
    p26.[GeoCountryName] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoCountryName],
    p27.[GeoContinentCode] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentCode],
    p27.[GeoContinentName] AS [Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentName],
    p28.[OrgBusinessUnitCode] AS [Plant_OrgBusinessUnit_OrgBusinessUnitCode],
    p28.[OrgBusinessUnitName] AS [Plant_OrgBusinessUnit_OrgBusinessUnitName],
    p29.[OrgRegionCode] AS [Plant_OrgBusinessUnit_OrgRegion_OrgRegionCode],
    p29.[OrgRegionName] AS [Plant_OrgBusinessUnit_OrgRegion_OrgRegionName],
    p30.[OrgDivisionCode] AS [Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionCode],
    p30.[OrgDivisionName] AS [Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionName],
    p31.[OrgEnterpriseCode] AS [Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseCode],
    p31.[OrgEnterpriseName] AS [Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseName],
    p32.[CampusCode] AS [Plant_PlantCampus_CampusCode],
    p32.[CampusName] AS [Plant_PlantCampus_CampusName],
    p32.[OwnerName] AS [Plant_PlantCampus_OwnerName],
    p33.[StatusCode] AS [Plant_PlantCampus_RecordStatus_StatusCode],
    p33.[StatusName] AS [Plant_PlantCampus_RecordStatus_StatusName],
    p34.[GeoCityCode] AS [Plant_PlantCampus_GeoCity_GeoCityCode],
    p34.[GeoCityName] AS [Plant_PlantCampus_GeoCity_GeoCityName],
    p35.[GeoStateProvinceCode] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoStateProvinceCode],
    p35.[GeoStateProvinceName] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoStateProvinceName],
    p36.[GeoCountryCode] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoCountryCode],
    p36.[GeoCountryName] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoCountryName],
    p37.[GeoContinentCode] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentCode],
    p37.[GeoContinentName] AS [Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentName],
    p38.[PlantTypeCode] AS [Plant_PlantType_PlantTypeCode],
    p38.[PlantTypeName] AS [Plant_PlantType_PlantTypeName],
    p38.[OwnerName] AS [Plant_PlantType_OwnerName],
    p39.[StatusCode] AS [Plant_PlantType_RecordStatus_StatusCode],
    p39.[StatusName] AS [Plant_PlantType_RecordStatus_StatusName],
    p40.[UomCode] AS [Plant_PlantType_UnitOfMeasure_UomCode],
    p40.[UomName] AS [Plant_PlantType_UnitOfMeasure_UomName],
    p41.[ClassCode] AS [Plant_PlantType_UnitOfMeasure_UnitOfMeasureClass_ClassCode],
    p41.[ClassName] AS [Plant_PlantType_UnitOfMeasure_UnitOfMeasureClass_ClassName],
    p41.[BaseUnitCode] AS [Plant_PlantType_UnitOfMeasure_UnitOfMeasureClass_BaseUnitCode],
    p42.[ProductNumber] AS [Product_ProductNumber],
    p42.[ProductName] AS [Product_ProductName],
    p42.[RevisionCode] AS [Product_RevisionCode],
    p42.[MakeBuyCode] AS [Product_MakeBuyCode],
    p43.[HazardClassCode] AS [Product_HazardClass_HazardClassCode],
    p43.[HazardClassName] AS [Product_HazardClass_HazardClassName],
    p44.[StandardCode] AS [Product_HazardClass_ComplianceStandard_StandardCode],
    p44.[ComplianceStandardName] AS [Product_HazardClass_ComplianceStandard_ComplianceStandardName],
    p45.[MeasurementSystemCode] AS [Product_MeasurementSystem_MeasurementSystemCode],
    p45.[MeasurementSystemName] AS [Product_MeasurementSystem_MeasurementSystemName],
    p45.[DefaultLengthUomCode] AS [Product_MeasurementSystem_DefaultLengthUomCode],
    p45.[DefaultMassUomCode] AS [Product_MeasurementSystem_DefaultMassUomCode],
    p46.[StatusCode] AS [Product_RecordStatus_StatusCode],
    p46.[StatusName] AS [Product_RecordStatus_StatusName],
    p47.[UomCode] AS [Product_UnitOfMeasure_UomCode],
    p47.[UomName] AS [Product_UnitOfMeasure_UomName],
    p48.[ClassCode] AS [Product_UnitOfMeasure_UnitOfMeasureClass_ClassCode],
    p48.[ClassName] AS [Product_UnitOfMeasure_UnitOfMeasureClass_ClassName],
    p48.[BaseUnitCode] AS [Product_UnitOfMeasure_UnitOfMeasureClass_BaseUnitCode],
    p49.[BrandCode] AS [Product_ProductBrand_BrandCode],
    p49.[BrandName] AS [Product_ProductBrand_BrandName],
    p49.[OwnerName] AS [Product_ProductBrand_OwnerName],
    p50.[StatusCode] AS [Product_ProductBrand_RecordStatus_StatusCode],
    p50.[StatusName] AS [Product_ProductBrand_RecordStatus_StatusName],
    p51.[BrandOwnerCode] AS [Product_ProductBrand_BrandOwner_BrandOwnerCode],
    p51.[BrandOwnerName] AS [Product_ProductBrand_BrandOwner_BrandOwnerName],
    p51.[OwnerName] AS [Product_ProductBrand_BrandOwner_OwnerName],
    p52.[CountryCode] AS [Product_ProductBrand_BrandOwner_Country_CountryCode],
    p52.[CountryName] AS [Product_ProductBrand_BrandOwner_Country_CountryName],
    p53.[RegionCode] AS [Product_ProductBrand_BrandOwner_Country_Region_RegionCode],
    p53.[RegionName] AS [Product_ProductBrand_BrandOwner_Country_Region_RegionName],
    p54.[ContinentCode] AS [Product_ProductBrand_BrandOwner_Country_Region_Continent_ContinentCode],
    p54.[ContinentName] AS [Product_ProductBrand_BrandOwner_Country_Region_Continent_ContinentName],
    p55.[StatusCode] AS [Product_ProductBrand_BrandOwner_RecordStatus_StatusCode],
    p55.[StatusName] AS [Product_ProductBrand_BrandOwner_RecordStatus_StatusName],
    p56.[CertificationCode] AS [Product_ProductCertification_CertificationCode],
    p56.[CertificationName] AS [Product_ProductCertification_CertificationName],
    p56.[OwnerName] AS [Product_ProductCertification_OwnerName],
    p57.[StandardCode] AS [Product_ProductCertification_ComplianceStandard_StandardCode],
    p57.[ComplianceStandardName] AS [Product_ProductCertification_ComplianceStandard_ComplianceStandardName],
    p58.[StatusCode] AS [Product_ProductCertification_RecordStatus_StatusCode],
    p58.[StatusName] AS [Product_ProductCertification_RecordStatus_StatusName],
    p59.[LifecyclePhaseCode] AS [Product_ProductLifecyclePhase_LifecyclePhaseCode],
    p59.[LifecyclePhaseName] AS [Product_ProductLifecyclePhase_LifecyclePhaseName],
    p59.[OwnerName] AS [Product_ProductLifecyclePhase_OwnerName],
    p60.[ApprovalStatusCode] AS [Product_ProductLifecyclePhase_ApprovalStatus_ApprovalStatusCode],
    p60.[ApprovalStatusName] AS [Product_ProductLifecyclePhase_ApprovalStatus_ApprovalStatusName],
    p61.[StatusCode] AS [Product_ProductLifecyclePhase_RecordStatus_StatusCode],
    p61.[StatusName] AS [Product_ProductLifecyclePhase_RecordStatus_StatusName],
    p62.[ProductSubfamilyCode] AS [Product_ProductSubfamily_ProductSubfamilyCode],
    p62.[ProductSubfamilyName] AS [Product_ProductSubfamily_ProductSubfamilyName],
    p63.[ProductFamilyCode] AS [Product_ProductSubfamily_ProductFamily_ProductFamilyCode],
    p63.[ProductFamilyName] AS [Product_ProductSubfamily_ProductFamily_ProductFamilyName],
    p64.[ProductLineCode] AS [Product_ProductSubfamily_ProductFamily_ProductLine_ProductLineCode],
    p64.[ProductLineName] AS [Product_ProductSubfamily_ProductFamily_ProductLine_ProductLineName],
    p65.[ProductDivisionCode] AS [Product_ProductSubfamily_ProductFamily_ProductLine_ProductDivision_ProductDivisionCode],
    p65.[ProductDivisionName] AS [Product_ProductSubfamily_ProductFamily_ProductLine_ProductDivision_ProductDivisionName],
    p66.[WorkCenterCode] AS [WorkCenter_WorkCenterCode],
    p66.[WorkCenterName] AS [WorkCenter_WorkCenterName],
    p67.[StatusCode] AS [WorkCenter_RecordStatus_StatusCode],
    p67.[StatusName] AS [WorkCenter_RecordStatus_StatusName],
    p68.[ShiftCode] AS [WorkCenter_ShiftCode_ShiftCode],
    p68.[ShiftCodeName] AS [WorkCenter_ShiftCode_ShiftCodeName],
    p69.[UomCode] AS [WorkCenter_UnitOfMeasure_UomCode],
    p69.[UomName] AS [WorkCenter_UnitOfMeasure_UomName],
    p70.[ClassCode] AS [WorkCenter_UnitOfMeasure_UnitOfMeasureClass_ClassCode],
    p70.[ClassName] AS [WorkCenter_UnitOfMeasure_UnitOfMeasureClass_ClassName],
    p70.[BaseUnitCode] AS [WorkCenter_UnitOfMeasure_UnitOfMeasureClass_BaseUnitCode],
    p71.[SiteCode] AS [WorkCenter_Site_SiteCode],
    p71.[SiteName] AS [WorkCenter_Site_SiteName],
    p71.[BuildingCode] AS [WorkCenter_Site_BuildingCode],
    p71.[FloorCode] AS [WorkCenter_Site_FloorCode],
    p71.[AreaCode] AS [WorkCenter_Site_AreaCode],
    p72.[HazardClassCode] AS [WorkCenter_Site_HazardClass_HazardClassCode],
    p72.[HazardClassName] AS [WorkCenter_Site_HazardClass_HazardClassName],
    p73.[StandardCode] AS [WorkCenter_Site_HazardClass_ComplianceStandard_StandardCode],
    p73.[ComplianceStandardName] AS [WorkCenter_Site_HazardClass_ComplianceStandard_ComplianceStandardName],
    p74.[StatusCode] AS [WorkCenter_Site_RecordStatus_StatusCode],
    p74.[StatusName] AS [WorkCenter_Site_RecordStatus_StatusName],
    p75.[PlantCode] AS [WorkCenter_Site_Plant_PlantCode],
    p75.[PlantName] AS [WorkCenter_Site_Plant_PlantName],
    p75.[LegalEntityCode] AS [WorkCenter_Site_Plant_LegalEntityCode],
    p75.[PlantManagerName] AS [WorkCenter_Site_Plant_PlantManagerName],
    p75.[DefaultCurrencyCode] AS [WorkCenter_Site_Plant_DefaultCurrencyCode],
    p75.[TimeZoneName] AS [WorkCenter_Site_Plant_TimeZoneName],
    p76.[CountryCode] AS [WorkCenter_Site_Plant_Country_CountryCode],
    p76.[CountryName] AS [WorkCenter_Site_Plant_Country_CountryName],
    p77.[RegionCode] AS [WorkCenter_Site_Plant_Country_Region_RegionCode],
    p77.[RegionName] AS [WorkCenter_Site_Plant_Country_Region_RegionName],
    p78.[ContinentCode] AS [WorkCenter_Site_Plant_Country_Region_Continent_ContinentCode],
    p78.[ContinentName] AS [WorkCenter_Site_Plant_Country_Region_Continent_ContinentName],
    p79.[CurrencyCode] AS [WorkCenter_Site_Plant_Currency_CurrencyCode],
    p79.[CurrencyName] AS [WorkCenter_Site_Plant_Currency_CurrencyName],
    p80.[RegionCode] AS [WorkCenter_Site_Plant_Currency_CurrencyRegion_RegionCode],
    p80.[RegionName] AS [WorkCenter_Site_Plant_Currency_CurrencyRegion_RegionName],
    p80.[DefaultCurrencyCode] AS [WorkCenter_Site_Plant_Currency_CurrencyRegion_DefaultCurrencyCode],
    p81.[StatusCode] AS [WorkCenter_Site_Plant_RecordStatus_StatusCode],
    p81.[StatusName] AS [WorkCenter_Site_Plant_RecordStatus_StatusName],
    p82.[TimeZoneCode] AS [WorkCenter_Site_Plant_TimeZone_TimeZoneCode],
    p82.[TimeZoneName] AS [WorkCenter_Site_Plant_TimeZone_TimeZoneName],
    p83.[RegionCode] AS [WorkCenter_Site_Plant_TimeZone_Region_RegionCode],
    p83.[RegionName] AS [WorkCenter_Site_Plant_TimeZone_Region_RegionName],
    p84.[ContinentCode] AS [WorkCenter_Site_Plant_TimeZone_Region_Continent_ContinentCode],
    p84.[ContinentName] AS [WorkCenter_Site_Plant_TimeZone_Region_Continent_ContinentName],
    p85.[GeoPostalCodeCode] AS [WorkCenter_Site_Plant_GeoPostalCode_GeoPostalCodeCode],
    p85.[GeoPostalCodeName] AS [WorkCenter_Site_Plant_GeoPostalCode_GeoPostalCodeName],
    p86.[GeoCityCode] AS [WorkCenter_Site_Plant_GeoPostalCode_GeoCity_GeoCityCode],
    p86.[GeoCityName] AS [WorkCenter_Site_Plant_GeoPostalCode_GeoCity_GeoCityName],
    p87.[GeoStateProvinceCode] AS [WorkCenter_Site_Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoStateProvinceCode],
    p87.[GeoStateProvinceName] AS [WorkCenter_Site_Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoStateProvinceName],
    p88.[GeoCountryCode] AS [WorkCenter_Site_Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoCountryCode],
    p88.[GeoCountryName] AS [WorkCenter_Site_Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoCountryName],
    p89.[GeoContinentCode] AS [WorkCenter_Site_Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentCode],
    p89.[GeoContinentName] AS [WorkCenter_Site_Plant_GeoPostalCode_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentName],
    p90.[OrgBusinessUnitCode] AS [WorkCenter_Site_Plant_OrgBusinessUnit_OrgBusinessUnitCode],
    p90.[OrgBusinessUnitName] AS [WorkCenter_Site_Plant_OrgBusinessUnit_OrgBusinessUnitName],
    p91.[OrgRegionCode] AS [WorkCenter_Site_Plant_OrgBusinessUnit_OrgRegion_OrgRegionCode],
    p91.[OrgRegionName] AS [WorkCenter_Site_Plant_OrgBusinessUnit_OrgRegion_OrgRegionName],
    p92.[OrgDivisionCode] AS [WorkCenter_Site_Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionCode],
    p92.[OrgDivisionName] AS [WorkCenter_Site_Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgDivisionName],
    p93.[OrgEnterpriseCode] AS [WorkCenter_Site_Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseCode],
    p93.[OrgEnterpriseName] AS [WorkCenter_Site_Plant_OrgBusinessUnit_OrgRegion_OrgDivision_OrgEnterprise_OrgEnterpriseName],
    p94.[CampusCode] AS [WorkCenter_Site_Plant_PlantCampus_CampusCode],
    p94.[CampusName] AS [WorkCenter_Site_Plant_PlantCampus_CampusName],
    p94.[OwnerName] AS [WorkCenter_Site_Plant_PlantCampus_OwnerName],
    p95.[StatusCode] AS [WorkCenter_Site_Plant_PlantCampus_RecordStatus_StatusCode],
    p95.[StatusName] AS [WorkCenter_Site_Plant_PlantCampus_RecordStatus_StatusName],
    p96.[GeoCityCode] AS [WorkCenter_Site_Plant_PlantCampus_GeoCity_GeoCityCode],
    p96.[GeoCityName] AS [WorkCenter_Site_Plant_PlantCampus_GeoCity_GeoCityName],
    p97.[GeoStateProvinceCode] AS [WorkCenter_Site_Plant_PlantCampus_GeoCity_GeoStateProvince_GeoStateProvinceCode],
    p97.[GeoStateProvinceName] AS [WorkCenter_Site_Plant_PlantCampus_GeoCity_GeoStateProvince_GeoStateProvinceName],
    p98.[GeoCountryCode] AS [WorkCenter_Site_Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoCountryCode],
    p98.[GeoCountryName] AS [WorkCenter_Site_Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoCountryName],
    p99.[GeoContinentCode] AS [WorkCenter_Site_Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentCode],
    p99.[GeoContinentName] AS [WorkCenter_Site_Plant_PlantCampus_GeoCity_GeoStateProvince_GeoCountry_GeoContinent_GeoContinentName],
    p100.[PlantTypeCode] AS [WorkCenter_Site_Plant_PlantType_PlantTypeCode],
    p100.[PlantTypeName] AS [WorkCenter_Site_Plant_PlantType_PlantTypeName],
    p100.[OwnerName] AS [WorkCenter_Site_Plant_PlantType_OwnerName],
    p101.[StatusCode] AS [WorkCenter_Site_Plant_PlantType_RecordStatus_StatusCode],
    p101.[StatusName] AS [WorkCenter_Site_Plant_PlantType_RecordStatus_StatusName],
    p102.[UomCode] AS [WorkCenter_Site_Plant_PlantType_UnitOfMeasure_UomCode],
    p102.[UomName] AS [WorkCenter_Site_Plant_PlantType_UnitOfMeasure_UomName],
    p103.[ClassCode] AS [WorkCenter_Site_Plant_PlantType_UnitOfMeasure_UnitOfMeasureClass_ClassCode],
    p103.[ClassName] AS [WorkCenter_Site_Plant_PlantType_UnitOfMeasure_UnitOfMeasureClass_ClassName],
    p103.[BaseUnitCode] AS [WorkCenter_Site_Plant_PlantType_UnitOfMeasure_UnitOfMeasureClass_BaseUnitCode],
    p104.[CapabilityCode] AS [WorkCenter_WorkCenterCapability_CapabilityCode],
    p104.[CapabilityName] AS [WorkCenter_WorkCenterCapability_CapabilityName],
    p104.[OwnerName] AS [WorkCenter_WorkCenterCapability_OwnerName],
    p105.[StatusCode] AS [WorkCenter_WorkCenterCapability_RecordStatus_StatusCode],
    p105.[StatusName] AS [WorkCenter_WorkCenterCapability_RecordStatus_StatusName],
    p106.[WorkCenterTypeCode] AS [WorkCenter_WorkCenterType_WorkCenterTypeCode],
    p106.[WorkCenterTypeName] AS [WorkCenter_WorkCenterType_WorkCenterTypeName],
    p106.[OwnerName] AS [WorkCenter_WorkCenterType_OwnerName],
    p107.[StatusCode] AS [WorkCenter_WorkCenterType_RecordStatus_StatusCode],
    p107.[StatusName] AS [WorkCenter_WorkCenterType_RecordStatus_StatusName]
FROM [dim].[FinanceProductionSettlement] b
LEFT JOIN [ref].[FinancePostingStatus] p1 ON b.[FinancePostingStatusKey] = p1.[FinancePostingStatusKey]
LEFT JOIN [dim].[CostCenter] p2 ON b.[CostCenterKey] = p2.[CostCenterKey]
LEFT JOIN [ref].[BudgetStatus] p3 ON p2.[BudgetStatusKey] = p3.[BudgetStatusKey]
LEFT JOIN [ref].[Currency] p4 ON p2.[CurrencyKey] = p4.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p5 ON p4.[CurrencyRegionKey] = p5.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p6 ON p2.[RecordStatusKey] = p6.[RecordStatusKey]
LEFT JOIN [dim].[CostCenterType] p7 ON p2.[CostCenterTypeKey] = p7.[CostCenterTypeKey]
LEFT JOIN [ref].[RecordStatus] p8 ON p7.[RecordStatusKey] = p8.[RecordStatusKey]
LEFT JOIN [dim].[OrgBusinessUnit] p9 ON p2.[OrgBusinessUnitKey] = p9.[OrgBusinessUnitKey]
LEFT JOIN [dim].[OrgRegion] p10 ON p9.[OrgRegionKey] = p10.[OrgRegionKey]
LEFT JOIN [dim].[OrgDivision] p11 ON p10.[OrgDivisionKey] = p11.[OrgDivisionKey]
LEFT JOIN [dim].[OrgEnterprise] p12 ON p11.[OrgEnterpriseKey] = p12.[OrgEnterpriseKey]
LEFT JOIN [dim].[Plant] p13 ON b.[PlantKey] = p13.[PlantKey]
LEFT JOIN [ref].[Country] p14 ON p13.[CountryKey] = p14.[CountryKey]
LEFT JOIN [ref].[Region] p15 ON p14.[RegionKey] = p15.[RegionKey]
LEFT JOIN [ref].[Continent] p16 ON p15.[ContinentKey] = p16.[ContinentKey]
LEFT JOIN [ref].[Currency] p17 ON p13.[CurrencyKey] = p17.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p18 ON p17.[CurrencyRegionKey] = p18.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p19 ON p13.[RecordStatusKey] = p19.[RecordStatusKey]
LEFT JOIN [ref].[TimeZone] p20 ON p13.[TimeZoneKey] = p20.[TimeZoneKey]
LEFT JOIN [ref].[Region] p21 ON p20.[RegionKey] = p21.[RegionKey]
LEFT JOIN [ref].[Continent] p22 ON p21.[ContinentKey] = p22.[ContinentKey]
LEFT JOIN [dim].[GeoPostalCode] p23 ON p13.[GeoPostalCodeKey] = p23.[GeoPostalCodeKey]
LEFT JOIN [dim].[GeoCity] p24 ON p23.[GeoCityKey] = p24.[GeoCityKey]
LEFT JOIN [dim].[GeoStateProvince] p25 ON p24.[GeoStateProvinceKey] = p25.[GeoStateProvinceKey]
LEFT JOIN [dim].[GeoCountry] p26 ON p25.[GeoCountryKey] = p26.[GeoCountryKey]
LEFT JOIN [dim].[GeoContinent] p27 ON p26.[GeoContinentKey] = p27.[GeoContinentKey]
LEFT JOIN [dim].[OrgBusinessUnit] p28 ON p13.[OrgBusinessUnitKey] = p28.[OrgBusinessUnitKey]
LEFT JOIN [dim].[OrgRegion] p29 ON p28.[OrgRegionKey] = p29.[OrgRegionKey]
LEFT JOIN [dim].[OrgDivision] p30 ON p29.[OrgDivisionKey] = p30.[OrgDivisionKey]
LEFT JOIN [dim].[OrgEnterprise] p31 ON p30.[OrgEnterpriseKey] = p31.[OrgEnterpriseKey]
LEFT JOIN [dim].[PlantCampus] p32 ON p13.[PlantCampusKey] = p32.[PlantCampusKey]
LEFT JOIN [ref].[RecordStatus] p33 ON p32.[RecordStatusKey] = p33.[RecordStatusKey]
LEFT JOIN [dim].[GeoCity] p34 ON p32.[GeoCityKey] = p34.[GeoCityKey]
LEFT JOIN [dim].[GeoStateProvince] p35 ON p34.[GeoStateProvinceKey] = p35.[GeoStateProvinceKey]
LEFT JOIN [dim].[GeoCountry] p36 ON p35.[GeoCountryKey] = p36.[GeoCountryKey]
LEFT JOIN [dim].[GeoContinent] p37 ON p36.[GeoContinentKey] = p37.[GeoContinentKey]
LEFT JOIN [dim].[PlantType] p38 ON p13.[PlantTypeKey] = p38.[PlantTypeKey]
LEFT JOIN [ref].[RecordStatus] p39 ON p38.[RecordStatusKey] = p39.[RecordStatusKey]
LEFT JOIN [ref].[UnitOfMeasure] p40 ON p38.[UnitOfMeasureKey] = p40.[UnitOfMeasureKey]
LEFT JOIN [ref].[UnitOfMeasureClass] p41 ON p40.[UnitOfMeasureClassKey] = p41.[UnitOfMeasureClassKey]
LEFT JOIN [dim].[Product] p42 ON b.[ProductKey] = p42.[ProductKey]
LEFT JOIN [ref].[HazardClass] p43 ON p42.[HazardClassKey] = p43.[HazardClassKey]
LEFT JOIN [ref].[ComplianceStandard] p44 ON p43.[ComplianceStandardKey] = p44.[ComplianceStandardKey]
LEFT JOIN [ref].[MeasurementSystem] p45 ON p42.[MeasurementSystemKey] = p45.[MeasurementSystemKey]
LEFT JOIN [ref].[RecordStatus] p46 ON p42.[RecordStatusKey] = p46.[RecordStatusKey]
LEFT JOIN [ref].[UnitOfMeasure] p47 ON p42.[UnitOfMeasureKey] = p47.[UnitOfMeasureKey]
LEFT JOIN [ref].[UnitOfMeasureClass] p48 ON p47.[UnitOfMeasureClassKey] = p48.[UnitOfMeasureClassKey]
LEFT JOIN [dim].[ProductBrand] p49 ON p42.[ProductBrandKey] = p49.[ProductBrandKey]
LEFT JOIN [ref].[RecordStatus] p50 ON p49.[RecordStatusKey] = p50.[RecordStatusKey]
LEFT JOIN [dim].[BrandOwner] p51 ON p49.[BrandOwnerKey] = p51.[BrandOwnerKey]
LEFT JOIN [ref].[Country] p52 ON p51.[CountryKey] = p52.[CountryKey]
LEFT JOIN [ref].[Region] p53 ON p52.[RegionKey] = p53.[RegionKey]
LEFT JOIN [ref].[Continent] p54 ON p53.[ContinentKey] = p54.[ContinentKey]
LEFT JOIN [ref].[RecordStatus] p55 ON p51.[RecordStatusKey] = p55.[RecordStatusKey]
LEFT JOIN [dim].[ProductCertification] p56 ON p42.[ProductCertificationKey] = p56.[ProductCertificationKey]
LEFT JOIN [ref].[ComplianceStandard] p57 ON p56.[ComplianceStandardKey] = p57.[ComplianceStandardKey]
LEFT JOIN [ref].[RecordStatus] p58 ON p56.[RecordStatusKey] = p58.[RecordStatusKey]
LEFT JOIN [dim].[ProductLifecyclePhase] p59 ON p42.[ProductLifecyclePhaseKey] = p59.[ProductLifecyclePhaseKey]
LEFT JOIN [ref].[ApprovalStatus] p60 ON p59.[ApprovalStatusKey] = p60.[ApprovalStatusKey]
LEFT JOIN [ref].[RecordStatus] p61 ON p59.[RecordStatusKey] = p61.[RecordStatusKey]
LEFT JOIN [dim].[ProductSubfamily] p62 ON p42.[ProductSubfamilyKey] = p62.[ProductSubfamilyKey]
LEFT JOIN [dim].[ProductFamily] p63 ON p62.[ProductFamilyKey] = p63.[ProductFamilyKey]
LEFT JOIN [dim].[ProductLine] p64 ON p63.[ProductLineKey] = p64.[ProductLineKey]
LEFT JOIN [dim].[ProductDivision] p65 ON p64.[ProductDivisionKey] = p65.[ProductDivisionKey]
LEFT JOIN [dim].[WorkCenter] p66 ON b.[WorkCenterKey] = p66.[WorkCenterKey]
LEFT JOIN [ref].[RecordStatus] p67 ON p66.[RecordStatusKey] = p67.[RecordStatusKey]
LEFT JOIN [ref].[ShiftCode] p68 ON p66.[ShiftCodeKey] = p68.[ShiftCodeKey]
LEFT JOIN [ref].[UnitOfMeasure] p69 ON p66.[UnitOfMeasureKey] = p69.[UnitOfMeasureKey]
LEFT JOIN [ref].[UnitOfMeasureClass] p70 ON p69.[UnitOfMeasureClassKey] = p70.[UnitOfMeasureClassKey]
LEFT JOIN [dim].[Site] p71 ON p66.[SiteKey] = p71.[SiteKey]
LEFT JOIN [ref].[HazardClass] p72 ON p71.[HazardClassKey] = p72.[HazardClassKey]
LEFT JOIN [ref].[ComplianceStandard] p73 ON p72.[ComplianceStandardKey] = p73.[ComplianceStandardKey]
LEFT JOIN [ref].[RecordStatus] p74 ON p71.[RecordStatusKey] = p74.[RecordStatusKey]
LEFT JOIN [dim].[Plant] p75 ON p71.[PlantKey] = p75.[PlantKey]
LEFT JOIN [ref].[Country] p76 ON p75.[CountryKey] = p76.[CountryKey]
LEFT JOIN [ref].[Region] p77 ON p76.[RegionKey] = p77.[RegionKey]
LEFT JOIN [ref].[Continent] p78 ON p77.[ContinentKey] = p78.[ContinentKey]
LEFT JOIN [ref].[Currency] p79 ON p75.[CurrencyKey] = p79.[CurrencyKey]
LEFT JOIN [ref].[CurrencyRegion] p80 ON p79.[CurrencyRegionKey] = p80.[CurrencyRegionKey]
LEFT JOIN [ref].[RecordStatus] p81 ON p75.[RecordStatusKey] = p81.[RecordStatusKey]
LEFT JOIN [ref].[TimeZone] p82 ON p75.[TimeZoneKey] = p82.[TimeZoneKey]
LEFT JOIN [ref].[Region] p83 ON p82.[RegionKey] = p83.[RegionKey]
LEFT JOIN [ref].[Continent] p84 ON p83.[ContinentKey] = p84.[ContinentKey]
LEFT JOIN [dim].[GeoPostalCode] p85 ON p75.[GeoPostalCodeKey] = p85.[GeoPostalCodeKey]
LEFT JOIN [dim].[GeoCity] p86 ON p85.[GeoCityKey] = p86.[GeoCityKey]
LEFT JOIN [dim].[GeoStateProvince] p87 ON p86.[GeoStateProvinceKey] = p87.[GeoStateProvinceKey]
LEFT JOIN [dim].[GeoCountry] p88 ON p87.[GeoCountryKey] = p88.[GeoCountryKey]
LEFT JOIN [dim].[GeoContinent] p89 ON p88.[GeoContinentKey] = p89.[GeoContinentKey]
LEFT JOIN [dim].[OrgBusinessUnit] p90 ON p75.[OrgBusinessUnitKey] = p90.[OrgBusinessUnitKey]
LEFT JOIN [dim].[OrgRegion] p91 ON p90.[OrgRegionKey] = p91.[OrgRegionKey]
LEFT JOIN [dim].[OrgDivision] p92 ON p91.[OrgDivisionKey] = p92.[OrgDivisionKey]
LEFT JOIN [dim].[OrgEnterprise] p93 ON p92.[OrgEnterpriseKey] = p93.[OrgEnterpriseKey]
LEFT JOIN [dim].[PlantCampus] p94 ON p75.[PlantCampusKey] = p94.[PlantCampusKey]
LEFT JOIN [ref].[RecordStatus] p95 ON p94.[RecordStatusKey] = p95.[RecordStatusKey]
LEFT JOIN [dim].[GeoCity] p96 ON p94.[GeoCityKey] = p96.[GeoCityKey]
LEFT JOIN [dim].[GeoStateProvince] p97 ON p96.[GeoStateProvinceKey] = p97.[GeoStateProvinceKey]
LEFT JOIN [dim].[GeoCountry] p98 ON p97.[GeoCountryKey] = p98.[GeoCountryKey]
LEFT JOIN [dim].[GeoContinent] p99 ON p98.[GeoContinentKey] = p99.[GeoContinentKey]
LEFT JOIN [dim].[PlantType] p100 ON p75.[PlantTypeKey] = p100.[PlantTypeKey]
LEFT JOIN [ref].[RecordStatus] p101 ON p100.[RecordStatusKey] = p101.[RecordStatusKey]
LEFT JOIN [ref].[UnitOfMeasure] p102 ON p100.[UnitOfMeasureKey] = p102.[UnitOfMeasureKey]
LEFT JOIN [ref].[UnitOfMeasureClass] p103 ON p102.[UnitOfMeasureClassKey] = p103.[UnitOfMeasureClassKey]
LEFT JOIN [dim].[WorkCenterCapability] p104 ON p66.[WorkCenterCapabilityKey] = p104.[WorkCenterCapabilityKey]
LEFT JOIN [ref].[RecordStatus] p105 ON p104.[RecordStatusKey] = p105.[RecordStatusKey]
LEFT JOIN [dim].[WorkCenterType] p106 ON p66.[WorkCenterTypeKey] = p106.[WorkCenterTypeKey]
LEFT JOIN [ref].[RecordStatus] p107 ON p106.[RecordStatusKey] = p107.[RecordStatusKey]
GO
