-- Generated by tools.generator. Do not hand-edit.

-- Subject area: finance_costing

IF OBJECT_ID(N'bridge.FinanceCostComponentAllocation', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[FinanceCostComponentAllocation] (
    [FinanceCostComponentAllocationKey] INT IDENTITY(1,1) NOT NULL,
    [FinanceProductCostVersionKey] INT NOT NULL DEFAULT -1,
    [FinanceCostComponentDetailKey] INT NOT NULL DEFAULT -1,
    [FinanceCostElementDetailKey] INT NOT NULL DEFAULT -1,
    [AllocationRatio] DECIMAL(9,6) NOT NULL,
    [ComponentCostAmount] MONEY NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_FinanceCostComponentAllocation] PRIMARY KEY CLUSTERED ([FinanceCostComponentAllocationKey])
);
END
GO

IF OBJECT_ID(N'bridge.FinanceJournalProfitabilityAssignment', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[FinanceJournalProfitabilityAssignment] (
    [FinanceJournalProfitabilityAssignmentKey] INT IDENTITY(1,1) NOT NULL,
    [FinanceJournalLineKey] INT NOT NULL DEFAULT -1,
    [FinanceProfitObjectKey] INT NOT NULL DEFAULT -1,
    [BusinessUnitKey] INT NOT NULL DEFAULT -1,
    [AllocationRatio] DECIMAL(9,6) NOT NULL,
    [AllocatedAmount] MONEY NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_FinanceJournalProfitabilityAssignment] PRIMARY KEY CLUSTERED ([FinanceJournalProfitabilityAssignmentKey])
);
END
GO
