-- Generated by tools.generator. Do not hand-edit.

-- Subject area: hr_labor

IF OBJECT_ID(N'bridge.LaborEmployeeCertification', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[LaborEmployeeCertification] (
    [LaborEmployeeCertificationKey] INT IDENTITY(1,1) NOT NULL,
    [EmployeeKey] INT NOT NULL DEFAULT -1,
    [LaborCertificationKey] INT NOT NULL DEFAULT -1,
    [RecordStatusKey] INT NOT NULL DEFAULT -1,
    [IssuedDate] DATE NULL,
    [ExpirationDate] DATE NULL,
    [CertificationScore] DECIMAL(9,2) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_LaborEmployeeCertification] PRIMARY KEY CLUSTERED ([LaborEmployeeCertificationKey])
);
END
GO

IF OBJECT_ID(N'bridge.LaborEmployeeCrew', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[LaborEmployeeCrew] (
    [LaborEmployeeCrewKey] INT IDENTITY(1,1) NOT NULL,
    [EmployeeKey] INT NOT NULL DEFAULT -1,
    [LaborCrewKey] INT NOT NULL DEFAULT -1,
    [LaborTeamKey] INT NOT NULL DEFAULT -1,
    [AssignmentStartDate] DATE NOT NULL,
    [AssignmentEndDate] DATE NULL,
    [AllocationRatio] DECIMAL(9,4) NOT NULL DEFAULT 1.0000,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_LaborEmployeeCrew] PRIMARY KEY CLUSTERED ([LaborEmployeeCrewKey])
);
END
GO

IF OBJECT_ID(N'bridge.LaborEmployeeSkill', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[LaborEmployeeSkill] (
    [LaborEmployeeSkillKey] INT IDENTITY(1,1) NOT NULL,
    [EmployeeKey] INT NOT NULL DEFAULT -1,
    [LaborSkillKey] INT NOT NULL DEFAULT -1,
    [ProficiencyRating] DECIMAL(9,2) NULL,
    [VerifiedDate] DATE NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_LaborEmployeeSkill] PRIMARY KEY CLUSTERED ([LaborEmployeeSkillKey])
);
END
GO
