-- Generated by tools.generator. Do not hand-edit.

-- Subject area: procurement

IF OBJECT_ID(N'bridge.PurchaseContractProductAssignment', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[PurchaseContractProductAssignment] (
    [PurchaseContractProductAssignmentKey] INT IDENTITY(1,1) NOT NULL,
    [PurchaseSupplierContractKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NULL,
    [PurchaseCommodityKey] INT NOT NULL DEFAULT -1,
    [ContractUnitPriceAmount] MONEY NULL,
    [ContractQuantity] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_PurchaseContractProductAssignment] PRIMARY KEY CLUSTERED ([PurchaseContractProductAssignmentKey])
);
END
GO

IF OBJECT_ID(N'bridge.PurchaseOrderLineToReceipt', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[PurchaseOrderLineToReceipt] (
    [PurchaseOrderLineToReceiptKey] INT IDENTITY(1,1) NOT NULL,
    [PurchaseOrderLineKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NULL,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [PurchaseReceiptStatusKey] INT NOT NULL DEFAULT -1,
    [ReceivedQuantity] DECIMAL(18,4) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_PurchaseOrderLineToReceipt] PRIMARY KEY CLUSTERED ([PurchaseOrderLineToReceiptKey])
);
END
GO

IF OBJECT_ID(N'bridge.PurchaseRequisitionToOrderLine', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[PurchaseRequisitionToOrderLine] (
    [PurchaseRequisitionToOrderLineKey] INT IDENTITY(1,1) NOT NULL,
    [PurchaseRequisitionKey] INT NOT NULL DEFAULT -1,
    [PurchaseOrderLineKey] INT NOT NULL DEFAULT -1,
    [LinkedQuantity] DECIMAL(18,4) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_PurchaseRequisitionToOrderLine] PRIMARY KEY CLUSTERED ([PurchaseRequisitionToOrderLineKey])
);
END
GO

IF OBJECT_ID(N'bridge.PurchaseRfqSupplierInvitation', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[PurchaseRfqSupplierInvitation] (
    [PurchaseRfqSupplierInvitationKey] INT IDENTITY(1,1) NOT NULL,
    [PurchaseRequestForQuoteKey] INT NOT NULL DEFAULT -1,
    [SupplierKey] INT NOT NULL DEFAULT -1,
    [ApprovalStatusKey] INT NOT NULL DEFAULT -1,
    [QuotedAmount] MONEY NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_PurchaseRfqSupplierInvitation] PRIMARY KEY CLUSTERED ([PurchaseRfqSupplierInvitationKey])
);
END
GO
