-- Generated by tools.generator. Do not hand-edit.

-- Subject area: production_execution

IF OBJECT_ID(N'bridge.ProductionLotGenealogy', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[ProductionLotGenealogy] (
    [ProductionLotGenealogyKey] INT IDENTITY(1,1) NOT NULL,
    [ParentProductionLotKey] INT NOT NULL DEFAULT -1,
    [ChildProductionLotKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [SequenceNumber] INT NULL,
    [QuantityValue] DECIMAL(18,6) NULL,
    [AllocationPercent] DECIMAL(9,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_ProductionLotGenealogy] PRIMARY KEY CLUSTERED ([ProductionLotGenealogyKey])
);
END
GO

IF OBJECT_ID(N'bridge.ProductionOperationWorkCenter', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[ProductionOperationWorkCenter] (
    [ProductionOperationWorkCenterKey] INT IDENTITY(1,1) NOT NULL,
    [ProductionOperationKey] INT NOT NULL DEFAULT -1,
    [WorkCenterKey] INT NOT NULL DEFAULT -1,
    [SequenceNumber] INT NULL,
    [QuantityValue] DECIMAL(18,6) NULL,
    [AllocationPercent] DECIMAL(9,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_ProductionOperationWorkCenter] PRIMARY KEY CLUSTERED ([ProductionOperationWorkCenterKey])
);
END
GO

IF OBJECT_ID(N'bridge.ProductionRunCrewAssignment', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[ProductionRunCrewAssignment] (
    [ProductionRunCrewAssignmentKey] INT IDENTITY(1,1) NOT NULL,
    [ProductionRunKey] INT NOT NULL DEFAULT -1,
    [ProductionCrewKey] INT NOT NULL DEFAULT -1,
    [ProductionShiftKey] INT NOT NULL DEFAULT -1,
    [SequenceNumber] INT NULL,
    [QuantityValue] DECIMAL(18,6) NULL,
    [AllocationPercent] DECIMAL(9,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_ProductionRunCrewAssignment] PRIMARY KEY CLUSTERED ([ProductionRunCrewAssignmentKey])
);
END
GO

IF OBJECT_ID(N'bridge.ProductionWorkOrderEmployee', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[ProductionWorkOrderEmployee] (
    [ProductionWorkOrderEmployeeKey] INT IDENTITY(1,1) NOT NULL,
    [ProductionWorkOrderKey] INT NOT NULL DEFAULT -1,
    [EmployeeKey] INT NOT NULL DEFAULT -1,
    [ProductionCrewRoleKey] INT NOT NULL DEFAULT -1,
    [SequenceNumber] INT NULL,
    [QuantityValue] DECIMAL(18,6) NULL,
    [AllocationPercent] DECIMAL(9,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_ProductionWorkOrderEmployee] PRIMARY KEY CLUSTERED ([ProductionWorkOrderEmployeeKey])
);
END
GO
