-- Generated by tools.generator. Do not hand-edit.

-- Subject area: quality

IF OBJECT_ID(N'bridge.QualityDefectCharacteristic', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[QualityDefectCharacteristic] (
    [QualityDefectCharacteristicKey] INT IDENTITY(1,1) NOT NULL,
    [QualityDefectCodeKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionCharacteristicKey] INT NOT NULL DEFAULT -1,
    [SequenceNumber] INT NULL,
    [QuantityValue] DECIMAL(18,6) NULL,
    [AllocationPercent] DECIMAL(9,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_QualityDefectCharacteristic] PRIMARY KEY CLUSTERED ([QualityDefectCharacteristicKey])
);
END
GO

IF OBJECT_ID(N'bridge.QualityGaugeCharacteristic', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[QualityGaugeCharacteristic] (
    [QualityGaugeCharacteristicKey] INT IDENTITY(1,1) NOT NULL,
    [QualityGaugeKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionCharacteristicKey] INT NOT NULL DEFAULT -1,
    [SequenceNumber] INT NULL,
    [QuantityValue] DECIMAL(18,6) NULL,
    [AllocationPercent] DECIMAL(9,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_QualityGaugeCharacteristic] PRIMARY KEY CLUSTERED ([QualityGaugeCharacteristicKey])
);
END
GO

IF OBJECT_ID(N'bridge.QualityInspectionPlanCharacteristic', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[QualityInspectionPlanCharacteristic] (
    [QualityInspectionPlanCharacteristicKey] INT IDENTITY(1,1) NOT NULL,
    [QualityInspectionPlanKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionCharacteristicKey] INT NOT NULL DEFAULT -1,
    [SequenceNumber] INT NULL,
    [QuantityValue] DECIMAL(18,6) NULL,
    [AllocationPercent] DECIMAL(9,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_QualityInspectionPlanCharacteristic] PRIMARY KEY CLUSTERED ([QualityInspectionPlanCharacteristicKey])
);
END
GO

IF OBJECT_ID(N'bridge.QualitySupplierProductApproval', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[QualitySupplierProductApproval] (
    [QualitySupplierProductApprovalKey] INT IDENTITY(1,1) NOT NULL,
    [SupplierKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionPlanKey] INT NOT NULL DEFAULT -1,
    [ApprovalStatusKey] INT NOT NULL DEFAULT -1,
    [SequenceNumber] INT NULL,
    [QuantityValue] DECIMAL(18,6) NULL,
    [AllocationPercent] DECIMAL(9,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_QualitySupplierProductApproval] PRIMARY KEY CLUSTERED ([QualitySupplierProductApprovalKey])
);
END
GO
