-- Generated by tools.generator. Do not hand-edit.

-- Subject area: warranty_service

IF OBJECT_ID(N'bridge.ServiceContractProduct', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[ServiceContractProduct] (
    [ServiceContractProductKey] INT IDENTITY(1,1) NOT NULL,
    [ServiceContractKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [CoverageStartDate] DATE NOT NULL,
    [CoverageEndDate] DATE NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_ServiceContractProduct] PRIMARY KEY CLUSTERED ([ServiceContractProductKey])
);
END
GO

IF OBJECT_ID(N'bridge.ServiceOrderPart', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[ServiceOrderPart] (
    [ServiceOrderPartKey] INT IDENTITY(1,1) NOT NULL,
    [ServiceRepairCodeKey] INT NOT NULL DEFAULT -1,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [StandardPartQuantity] DECIMAL(18,4) NOT NULL,
    [IsMandatoryPart] BIT NOT NULL DEFAULT 0,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_ServiceOrderPart] PRIMARY KEY CLUSTERED ([ServiceOrderPartKey])
);
END
GO

IF OBJECT_ID(N'bridge.WarrantyClaimRepairCode', N'U') IS NULL
BEGIN
CREATE TABLE [bridge].[WarrantyClaimRepairCode] (
    [WarrantyClaimRepairCodeKey] INT IDENTITY(1,1) NOT NULL,
    [WarrantyFailureModeKey] INT NOT NULL DEFAULT -1,
    [ServiceRepairCodeKey] INT NOT NULL DEFAULT -1,
    [RepairProbabilityRatio] DECIMAL(9,6) NULL,
    [StandardAllowanceAmount] MONEY NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_bridge_WarrantyClaimRepairCode] PRIMARY KEY CLUSTERED ([WarrantyClaimRepairCodeKey])
);
END
GO
