-- Generated by tools.generator. Do not hand-edit.

-- Subject area: procurement

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseApprovalLevel_PurchaseApprovalPolicyKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseApprovalLevel'))
BEGIN
    ALTER TABLE [dim].[PurchaseApprovalLevel] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseApprovalLevel_PurchaseApprovalPolicyKey] FOREIGN KEY ([PurchaseApprovalPolicyKey]) REFERENCES [dim].[PurchaseApprovalPolicy] ([PurchaseApprovalPolicyKey]);
    ALTER TABLE [dim].[PurchaseApprovalLevel] CHECK CONSTRAINT [FK_dim_PurchaseApprovalLevel_PurchaseApprovalPolicyKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseCommodityCategory_PurchaseCommodityDomainKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseCommodityCategory'))
BEGIN
    ALTER TABLE [dim].[PurchaseCommodityCategory] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseCommodityCategory_PurchaseCommodityDomainKey] FOREIGN KEY ([PurchaseCommodityDomainKey]) REFERENCES [dim].[PurchaseCommodityDomain] ([PurchaseCommodityDomainKey]);
    ALTER TABLE [dim].[PurchaseCommodityCategory] CHECK CONSTRAINT [FK_dim_PurchaseCommodityCategory_PurchaseCommodityDomainKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseContractFamily_PurchaseContractProgramKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseContractFamily'))
BEGIN
    ALTER TABLE [dim].[PurchaseContractFamily] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseContractFamily_PurchaseContractProgramKey] FOREIGN KEY ([PurchaseContractProgramKey]) REFERENCES [dim].[PurchaseContractProgram] ([PurchaseContractProgramKey]);
    ALTER TABLE [dim].[PurchaseContractFamily] CHECK CONSTRAINT [FK_dim_PurchaseContractFamily_PurchaseContractProgramKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseSourcingPortfolio_PurchaseSourcingCouncilKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseSourcingPortfolio'))
BEGIN
    ALTER TABLE [dim].[PurchaseSourcingPortfolio] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseSourcingPortfolio_PurchaseSourcingCouncilKey] FOREIGN KEY ([PurchaseSourcingCouncilKey]) REFERENCES [dim].[PurchaseSourcingCouncil] ([PurchaseSourcingCouncilKey]);
    ALTER TABLE [dim].[PurchaseSourcingPortfolio] CHECK CONSTRAINT [FK_dim_PurchaseSourcingPortfolio_PurchaseSourcingCouncilKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseApprovalRoute_PurchaseApprovalLevelKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseApprovalRoute'))
BEGIN
    ALTER TABLE [dim].[PurchaseApprovalRoute] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseApprovalRoute_PurchaseApprovalLevelKey] FOREIGN KEY ([PurchaseApprovalLevelKey]) REFERENCES [dim].[PurchaseApprovalLevel] ([PurchaseApprovalLevelKey]);
    ALTER TABLE [dim].[PurchaseApprovalRoute] CHECK CONSTRAINT [FK_dim_PurchaseApprovalRoute_PurchaseApprovalLevelKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseCommoditySubcategory_PurchaseCommodityCategoryKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseCommoditySubcategory'))
BEGIN
    ALTER TABLE [dim].[PurchaseCommoditySubcategory] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseCommoditySubcategory_PurchaseCommodityCategoryKey] FOREIGN KEY ([PurchaseCommodityCategoryKey]) REFERENCES [dim].[PurchaseCommodityCategory] ([PurchaseCommodityCategoryKey]);
    ALTER TABLE [dim].[PurchaseCommoditySubcategory] CHECK CONSTRAINT [FK_dim_PurchaseCommoditySubcategory_PurchaseCommodityCategoryKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseContractSchedule_PurchaseContractFamilyKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseContractSchedule'))
BEGIN
    ALTER TABLE [dim].[PurchaseContractSchedule] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseContractSchedule_PurchaseContractFamilyKey] FOREIGN KEY ([PurchaseContractFamilyKey]) REFERENCES [dim].[PurchaseContractFamily] ([PurchaseContractFamilyKey]);
    ALTER TABLE [dim].[PurchaseContractSchedule] CHECK CONSTRAINT [FK_dim_PurchaseContractSchedule_PurchaseContractFamilyKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseSourcingDesk_PurchaseSourcingPortfolioKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseSourcingDesk'))
BEGIN
    ALTER TABLE [dim].[PurchaseSourcingDesk] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseSourcingDesk_PurchaseSourcingPortfolioKey] FOREIGN KEY ([PurchaseSourcingPortfolioKey]) REFERENCES [dim].[PurchaseSourcingPortfolio] ([PurchaseSourcingPortfolioKey]);
    ALTER TABLE [dim].[PurchaseSourcingDesk] CHECK CONSTRAINT [FK_dim_PurchaseSourcingDesk_PurchaseSourcingPortfolioKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseApprovalStep_PurchaseApprovalRouteKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseApprovalStep'))
BEGIN
    ALTER TABLE [dim].[PurchaseApprovalStep] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseApprovalStep_PurchaseApprovalRouteKey] FOREIGN KEY ([PurchaseApprovalRouteKey]) REFERENCES [dim].[PurchaseApprovalRoute] ([PurchaseApprovalRouteKey]);
    ALTER TABLE [dim].[PurchaseApprovalStep] CHECK CONSTRAINT [FK_dim_PurchaseApprovalStep_PurchaseApprovalRouteKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseCommodity_PurchaseCommoditySubcategoryKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseCommodity'))
BEGIN
    ALTER TABLE [dim].[PurchaseCommodity] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseCommodity_PurchaseCommoditySubcategoryKey] FOREIGN KEY ([PurchaseCommoditySubcategoryKey]) REFERENCES [dim].[PurchaseCommoditySubcategory] ([PurchaseCommoditySubcategoryKey]);
    ALTER TABLE [dim].[PurchaseCommodity] CHECK CONSTRAINT [FK_dim_PurchaseCommodity_PurchaseCommoditySubcategoryKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseContractLineFamily_PurchaseContractScheduleKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseContractLineFamily'))
BEGIN
    ALTER TABLE [dim].[PurchaseContractLineFamily] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseContractLineFamily_PurchaseContractScheduleKey] FOREIGN KEY ([PurchaseContractScheduleKey]) REFERENCES [dim].[PurchaseContractSchedule] ([PurchaseContractScheduleKey]);
    ALTER TABLE [dim].[PurchaseContractLineFamily] CHECK CONSTRAINT [FK_dim_PurchaseContractLineFamily_PurchaseContractScheduleKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseBuyerAssignment_PurchaseSourcingDeskKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseBuyerAssignment'))
BEGIN
    ALTER TABLE [dim].[PurchaseBuyerAssignment] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseBuyerAssignment_PurchaseSourcingDeskKey] FOREIGN KEY ([PurchaseSourcingDeskKey]) REFERENCES [dim].[PurchaseSourcingDesk] ([PurchaseSourcingDeskKey]);
    ALTER TABLE [dim].[PurchaseBuyerAssignment] CHECK CONSTRAINT [FK_dim_PurchaseBuyerAssignment_PurchaseSourcingDeskKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseRequestForQuote_SourcingOwnerEmployeeKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseRequestForQuote'))
BEGIN
    ALTER TABLE [dim].[PurchaseRequestForQuote] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseRequestForQuote_SourcingOwnerEmployeeKey] FOREIGN KEY ([SourcingOwnerEmployeeKey]) REFERENCES [dim].[Employee] ([EmployeeKey]);
    ALTER TABLE [dim].[PurchaseRequestForQuote] CHECK CONSTRAINT [FK_dim_PurchaseRequestForQuote_SourcingOwnerEmployeeKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseRequestForQuote_PurchaseCommodityKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseRequestForQuote'))
BEGIN
    ALTER TABLE [dim].[PurchaseRequestForQuote] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseRequestForQuote_PurchaseCommodityKey] FOREIGN KEY ([PurchaseCommodityKey]) REFERENCES [dim].[PurchaseCommodity] ([PurchaseCommodityKey]);
    ALTER TABLE [dim].[PurchaseRequestForQuote] CHECK CONSTRAINT [FK_dim_PurchaseRequestForQuote_PurchaseCommodityKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseRequestForQuote_ApprovalStatusKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseRequestForQuote'))
BEGIN
    ALTER TABLE [dim].[PurchaseRequestForQuote] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseRequestForQuote_ApprovalStatusKey] FOREIGN KEY ([ApprovalStatusKey]) REFERENCES [ref].[ApprovalStatus] ([ApprovalStatusKey]);
    ALTER TABLE [dim].[PurchaseRequestForQuote] CHECK CONSTRAINT [FK_dim_PurchaseRequestForQuote_ApprovalStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseRequestForQuote_CurrencyKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseRequestForQuote'))
BEGIN
    ALTER TABLE [dim].[PurchaseRequestForQuote] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseRequestForQuote_CurrencyKey] FOREIGN KEY ([CurrencyKey]) REFERENCES [ref].[Currency] ([CurrencyKey]);
    ALTER TABLE [dim].[PurchaseRequestForQuote] CHECK CONSTRAINT [FK_dim_PurchaseRequestForQuote_CurrencyKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseRfqSupplierInvitation_PurchaseRequestForQuoteKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseRfqSupplierInvitation'))
BEGIN
    ALTER TABLE [bridge].[PurchaseRfqSupplierInvitation] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseRfqSupplierInvitation_PurchaseRequestForQuoteKey] FOREIGN KEY ([PurchaseRequestForQuoteKey]) REFERENCES [dim].[PurchaseRequestForQuote] ([PurchaseRequestForQuoteKey]);
    ALTER TABLE [bridge].[PurchaseRfqSupplierInvitation] CHECK CONSTRAINT [FK_bridge_PurchaseRfqSupplierInvitation_PurchaseRequestForQuoteKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseRfqSupplierInvitation_SupplierKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseRfqSupplierInvitation'))
BEGIN
    ALTER TABLE [bridge].[PurchaseRfqSupplierInvitation] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseRfqSupplierInvitation_SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dim].[Supplier] ([SupplierKey]);
    ALTER TABLE [bridge].[PurchaseRfqSupplierInvitation] CHECK CONSTRAINT [FK_bridge_PurchaseRfqSupplierInvitation_SupplierKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseRfqSupplierInvitation_ApprovalStatusKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseRfqSupplierInvitation'))
BEGIN
    ALTER TABLE [bridge].[PurchaseRfqSupplierInvitation] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseRfqSupplierInvitation_ApprovalStatusKey] FOREIGN KEY ([ApprovalStatusKey]) REFERENCES [ref].[ApprovalStatus] ([ApprovalStatusKey]);
    ALTER TABLE [bridge].[PurchaseRfqSupplierInvitation] CHECK CONSTRAINT [FK_bridge_PurchaseRfqSupplierInvitation_ApprovalStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_AwardDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_AwardDateKey] FOREIGN KEY ([AwardDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_AwardDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_BidDueDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_BidDueDateKey] FOREIGN KEY ([BidDueDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_BidDueDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_ContractDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_ContractDateKey] FOREIGN KEY ([ContractDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_ContractDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_CreateDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_CreateDateKey] FOREIGN KEY ([CreateDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_CreateDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_IssueDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_IssueDateKey] FOREIGN KEY ([IssueDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_IssueDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_SourcingOwnerEmployeeKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_SourcingOwnerEmployeeKey] FOREIGN KEY ([SourcingOwnerEmployeeKey]) REFERENCES [dim].[Employee] ([EmployeeKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_SourcingOwnerEmployeeKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_PurchaseCommodityKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_PurchaseCommodityKey] FOREIGN KEY ([PurchaseCommodityKey]) REFERENCES [dim].[PurchaseCommodity] ([PurchaseCommodityKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_PurchaseCommodityKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_PurchaseRequestForQuoteKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_PurchaseRequestForQuoteKey] FOREIGN KEY ([PurchaseRequestForQuoteKey]) REFERENCES [dim].[PurchaseRequestForQuote] ([PurchaseRequestForQuoteKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_PurchaseRequestForQuoteKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_SupplierKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dim].[Supplier] ([SupplierKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_SupplierKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_ApprovalStatusKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_ApprovalStatusKey] FOREIGN KEY ([ApprovalStatusKey]) REFERENCES [ref].[ApprovalStatus] ([ApprovalStatusKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_ApprovalStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSourcingCycle_CurrencyKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSourcingCycle'))
BEGIN
    ALTER TABLE [fact].[PurchaseSourcingCycle] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSourcingCycle_CurrencyKey] FOREIGN KEY ([CurrencyKey]) REFERENCES [ref].[Currency] ([CurrencyKey]);
    ALTER TABLE [fact].[PurchaseSourcingCycle] CHECK CONSTRAINT [FK_fact_PurchaseSourcingCycle_CurrencyKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseSupplierContract_ContractOwnerEmployeeKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseSupplierContract'))
BEGIN
    ALTER TABLE [dim].[PurchaseSupplierContract] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseSupplierContract_ContractOwnerEmployeeKey] FOREIGN KEY ([ContractOwnerEmployeeKey]) REFERENCES [dim].[Employee] ([EmployeeKey]);
    ALTER TABLE [dim].[PurchaseSupplierContract] CHECK CONSTRAINT [FK_dim_PurchaseSupplierContract_ContractOwnerEmployeeKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseSupplierContract_PurchaseContractLineFamilyKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseSupplierContract'))
BEGIN
    ALTER TABLE [dim].[PurchaseSupplierContract] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseSupplierContract_PurchaseContractLineFamilyKey] FOREIGN KEY ([PurchaseContractLineFamilyKey]) REFERENCES [dim].[PurchaseContractLineFamily] ([PurchaseContractLineFamilyKey]);
    ALTER TABLE [dim].[PurchaseSupplierContract] CHECK CONSTRAINT [FK_dim_PurchaseSupplierContract_PurchaseContractLineFamilyKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseSupplierContract_SupplierKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseSupplierContract'))
BEGIN
    ALTER TABLE [dim].[PurchaseSupplierContract] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseSupplierContract_SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dim].[Supplier] ([SupplierKey]);
    ALTER TABLE [dim].[PurchaseSupplierContract] CHECK CONSTRAINT [FK_dim_PurchaseSupplierContract_SupplierKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseSupplierContract_ApprovalStatusKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseSupplierContract'))
BEGIN
    ALTER TABLE [dim].[PurchaseSupplierContract] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseSupplierContract_ApprovalStatusKey] FOREIGN KEY ([ApprovalStatusKey]) REFERENCES [ref].[ApprovalStatus] ([ApprovalStatusKey]);
    ALTER TABLE [dim].[PurchaseSupplierContract] CHECK CONSTRAINT [FK_dim_PurchaseSupplierContract_ApprovalStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseSupplierContract_CurrencyKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseSupplierContract'))
BEGIN
    ALTER TABLE [dim].[PurchaseSupplierContract] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseSupplierContract_CurrencyKey] FOREIGN KEY ([CurrencyKey]) REFERENCES [ref].[Currency] ([CurrencyKey]);
    ALTER TABLE [dim].[PurchaseSupplierContract] CHECK CONSTRAINT [FK_dim_PurchaseSupplierContract_CurrencyKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseSupplierContract_PurchasePaymentTermKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseSupplierContract'))
BEGIN
    ALTER TABLE [dim].[PurchaseSupplierContract] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseSupplierContract_PurchasePaymentTermKey] FOREIGN KEY ([PurchasePaymentTermKey]) REFERENCES [ref].[PurchasePaymentTerm] ([PurchasePaymentTermKey]);
    ALTER TABLE [dim].[PurchaseSupplierContract] CHECK CONSTRAINT [FK_dim_PurchaseSupplierContract_PurchasePaymentTermKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseSupplierScorecard_PurchaseCommodityKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseSupplierScorecard'))
BEGIN
    ALTER TABLE [dim].[PurchaseSupplierScorecard] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseSupplierScorecard_PurchaseCommodityKey] FOREIGN KEY ([PurchaseCommodityKey]) REFERENCES [dim].[PurchaseCommodity] ([PurchaseCommodityKey]);
    ALTER TABLE [dim].[PurchaseSupplierScorecard] CHECK CONSTRAINT [FK_dim_PurchaseSupplierScorecard_PurchaseCommodityKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseSupplierScorecard_SupplierKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseSupplierScorecard'))
BEGIN
    ALTER TABLE [dim].[PurchaseSupplierScorecard] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseSupplierScorecard_SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dim].[Supplier] ([SupplierKey]);
    ALTER TABLE [dim].[PurchaseSupplierScorecard] CHECK CONSTRAINT [FK_dim_PurchaseSupplierScorecard_SupplierKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderHeader_BuyerEmployeeKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderHeader'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderHeader] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderHeader_BuyerEmployeeKey] FOREIGN KEY ([BuyerEmployeeKey]) REFERENCES [dim].[Employee] ([EmployeeKey]);
    ALTER TABLE [dim].[PurchaseOrderHeader] CHECK CONSTRAINT [FK_dim_PurchaseOrderHeader_BuyerEmployeeKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderHeader_PlantKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderHeader'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderHeader] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderHeader_PlantKey] FOREIGN KEY ([PlantKey]) REFERENCES [dim].[Plant] ([PlantKey]);
    ALTER TABLE [dim].[PurchaseOrderHeader] CHECK CONSTRAINT [FK_dim_PurchaseOrderHeader_PlantKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderHeader_PurchaseBuyerAssignmentKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderHeader'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderHeader] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderHeader_PurchaseBuyerAssignmentKey] FOREIGN KEY ([PurchaseBuyerAssignmentKey]) REFERENCES [dim].[PurchaseBuyerAssignment] ([PurchaseBuyerAssignmentKey]);
    ALTER TABLE [dim].[PurchaseOrderHeader] CHECK CONSTRAINT [FK_dim_PurchaseOrderHeader_PurchaseBuyerAssignmentKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderHeader_SupplierKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderHeader'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderHeader] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderHeader_SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dim].[Supplier] ([SupplierKey]);
    ALTER TABLE [dim].[PurchaseOrderHeader] CHECK CONSTRAINT [FK_dim_PurchaseOrderHeader_SupplierKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderHeader_CurrencyKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderHeader'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderHeader] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderHeader_CurrencyKey] FOREIGN KEY ([CurrencyKey]) REFERENCES [ref].[Currency] ([CurrencyKey]);
    ALTER TABLE [dim].[PurchaseOrderHeader] CHECK CONSTRAINT [FK_dim_PurchaseOrderHeader_CurrencyKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderHeader_PurchaseOrderLifecycleStatusKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderHeader'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderHeader] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderHeader_PurchaseOrderLifecycleStatusKey] FOREIGN KEY ([PurchaseOrderLifecycleStatusKey]) REFERENCES [ref].[PurchaseOrderLifecycleStatus] ([PurchaseOrderLifecycleStatusKey]);
    ALTER TABLE [dim].[PurchaseOrderHeader] CHECK CONSTRAINT [FK_dim_PurchaseOrderHeader_PurchaseOrderLifecycleStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderHeader_PurchasePaymentTermKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderHeader'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderHeader] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderHeader_PurchasePaymentTermKey] FOREIGN KEY ([PurchasePaymentTermKey]) REFERENCES [ref].[PurchasePaymentTerm] ([PurchasePaymentTermKey]);
    ALTER TABLE [dim].[PurchaseOrderHeader] CHECK CONSTRAINT [FK_dim_PurchaseOrderHeader_PurchasePaymentTermKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseRequisition_RequesterEmployeeKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseRequisition'))
BEGIN
    ALTER TABLE [dim].[PurchaseRequisition] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseRequisition_RequesterEmployeeKey] FOREIGN KEY ([RequesterEmployeeKey]) REFERENCES [dim].[Employee] ([EmployeeKey]);
    ALTER TABLE [dim].[PurchaseRequisition] CHECK CONSTRAINT [FK_dim_PurchaseRequisition_RequesterEmployeeKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseRequisition_PlantKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseRequisition'))
BEGIN
    ALTER TABLE [dim].[PurchaseRequisition] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseRequisition_PlantKey] FOREIGN KEY ([PlantKey]) REFERENCES [dim].[Plant] ([PlantKey]);
    ALTER TABLE [dim].[PurchaseRequisition] CHECK CONSTRAINT [FK_dim_PurchaseRequisition_PlantKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseRequisition_PurchaseApprovalStepKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseRequisition'))
BEGIN
    ALTER TABLE [dim].[PurchaseRequisition] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseRequisition_PurchaseApprovalStepKey] FOREIGN KEY ([PurchaseApprovalStepKey]) REFERENCES [dim].[PurchaseApprovalStep] ([PurchaseApprovalStepKey]);
    ALTER TABLE [dim].[PurchaseRequisition] CHECK CONSTRAINT [FK_dim_PurchaseRequisition_PurchaseApprovalStepKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseRequisition_PriorityKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseRequisition'))
BEGIN
    ALTER TABLE [dim].[PurchaseRequisition] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseRequisition_PriorityKey] FOREIGN KEY ([PriorityKey]) REFERENCES [ref].[Priority] ([PriorityKey]);
    ALTER TABLE [dim].[PurchaseRequisition] CHECK CONSTRAINT [FK_dim_PurchaseRequisition_PriorityKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseRequisition_PurchaseRequisitionStatusKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseRequisition'))
BEGIN
    ALTER TABLE [dim].[PurchaseRequisition] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseRequisition_PurchaseRequisitionStatusKey] FOREIGN KEY ([PurchaseRequisitionStatusKey]) REFERENCES [ref].[PurchaseRequisitionStatus] ([PurchaseRequisitionStatusKey]);
    ALTER TABLE [dim].[PurchaseRequisition] CHECK CONSTRAINT [FK_dim_PurchaseRequisition_PurchaseRequisitionStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseContractProductAssignment_ProductKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseContractProductAssignment'))
BEGIN
    ALTER TABLE [bridge].[PurchaseContractProductAssignment] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseContractProductAssignment_ProductKey] FOREIGN KEY ([ProductKey]) REFERENCES [dim].[Product] ([ProductKey]);
    ALTER TABLE [bridge].[PurchaseContractProductAssignment] CHECK CONSTRAINT [FK_bridge_PurchaseContractProductAssignment_ProductKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseContractProductAssignment_PurchaseCommodityKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseContractProductAssignment'))
BEGIN
    ALTER TABLE [bridge].[PurchaseContractProductAssignment] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseContractProductAssignment_PurchaseCommodityKey] FOREIGN KEY ([PurchaseCommodityKey]) REFERENCES [dim].[PurchaseCommodity] ([PurchaseCommodityKey]);
    ALTER TABLE [bridge].[PurchaseContractProductAssignment] CHECK CONSTRAINT [FK_bridge_PurchaseContractProductAssignment_PurchaseCommodityKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseContractProductAssignment_PurchaseSupplierContractKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseContractProductAssignment'))
BEGIN
    ALTER TABLE [bridge].[PurchaseContractProductAssignment] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseContractProductAssignment_PurchaseSupplierContractKey] FOREIGN KEY ([PurchaseSupplierContractKey]) REFERENCES [dim].[PurchaseSupplierContract] ([PurchaseSupplierContractKey]);
    ALTER TABLE [bridge].[PurchaseContractProductAssignment] CHECK CONSTRAINT [FK_bridge_PurchaseContractProductAssignment_PurchaseSupplierContractKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSupplierScoreSnapshot_SnapshotDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSupplierScoreSnapshot'))
BEGIN
    ALTER TABLE [fact].[PurchaseSupplierScoreSnapshot] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSupplierScoreSnapshot_SnapshotDateKey] FOREIGN KEY ([SnapshotDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseSupplierScoreSnapshot] CHECK CONSTRAINT [FK_fact_PurchaseSupplierScoreSnapshot_SnapshotDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSupplierScoreSnapshot_PurchaseCommodityKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSupplierScoreSnapshot'))
BEGIN
    ALTER TABLE [fact].[PurchaseSupplierScoreSnapshot] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSupplierScoreSnapshot_PurchaseCommodityKey] FOREIGN KEY ([PurchaseCommodityKey]) REFERENCES [dim].[PurchaseCommodity] ([PurchaseCommodityKey]);
    ALTER TABLE [fact].[PurchaseSupplierScoreSnapshot] CHECK CONSTRAINT [FK_fact_PurchaseSupplierScoreSnapshot_PurchaseCommodityKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSupplierScoreSnapshot_PurchaseSupplierScorecardKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSupplierScoreSnapshot'))
BEGIN
    ALTER TABLE [fact].[PurchaseSupplierScoreSnapshot] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSupplierScoreSnapshot_PurchaseSupplierScorecardKey] FOREIGN KEY ([PurchaseSupplierScorecardKey]) REFERENCES [dim].[PurchaseSupplierScorecard] ([PurchaseSupplierScorecardKey]);
    ALTER TABLE [fact].[PurchaseSupplierScoreSnapshot] CHECK CONSTRAINT [FK_fact_PurchaseSupplierScoreSnapshot_PurchaseSupplierScorecardKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseSupplierScoreSnapshot_SupplierKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseSupplierScoreSnapshot'))
BEGIN
    ALTER TABLE [fact].[PurchaseSupplierScoreSnapshot] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseSupplierScoreSnapshot_SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dim].[Supplier] ([SupplierKey]);
    ALTER TABLE [fact].[PurchaseSupplierScoreSnapshot] CHECK CONSTRAINT [FK_fact_PurchaseSupplierScoreSnapshot_SupplierKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderLine_ProductKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderLine'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderLine] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderLine_ProductKey] FOREIGN KEY ([ProductKey]) REFERENCES [dim].[Product] ([ProductKey]);
    ALTER TABLE [dim].[PurchaseOrderLine] CHECK CONSTRAINT [FK_dim_PurchaseOrderLine_ProductKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderLine_PurchaseCommodityKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderLine'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderLine] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderLine_PurchaseCommodityKey] FOREIGN KEY ([PurchaseCommodityKey]) REFERENCES [dim].[PurchaseCommodity] ([PurchaseCommodityKey]);
    ALTER TABLE [dim].[PurchaseOrderLine] CHECK CONSTRAINT [FK_dim_PurchaseOrderLine_PurchaseCommodityKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderLine_PurchaseOrderHeaderKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderLine'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderLine] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderLine_PurchaseOrderHeaderKey] FOREIGN KEY ([PurchaseOrderHeaderKey]) REFERENCES [dim].[PurchaseOrderHeader] ([PurchaseOrderHeaderKey]);
    ALTER TABLE [dim].[PurchaseOrderLine] CHECK CONSTRAINT [FK_dim_PurchaseOrderLine_PurchaseOrderHeaderKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderLine_PurchaseOrderLifecycleStatusKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderLine'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderLine] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderLine_PurchaseOrderLifecycleStatusKey] FOREIGN KEY ([PurchaseOrderLifecycleStatusKey]) REFERENCES [ref].[PurchaseOrderLifecycleStatus] ([PurchaseOrderLifecycleStatusKey]);
    ALTER TABLE [dim].[PurchaseOrderLine] CHECK CONSTRAINT [FK_dim_PurchaseOrderLine_PurchaseOrderLifecycleStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_dim_PurchaseOrderLine_UnitOfMeasureKey' AND parent_object_id = OBJECT_ID(N'dim.PurchaseOrderLine'))
BEGIN
    ALTER TABLE [dim].[PurchaseOrderLine] WITH CHECK ADD CONSTRAINT [FK_dim_PurchaseOrderLine_UnitOfMeasureKey] FOREIGN KEY ([UnitOfMeasureKey]) REFERENCES [ref].[UnitOfMeasure] ([UnitOfMeasureKey]);
    ALTER TABLE [dim].[PurchaseOrderLine] CHECK CONSTRAINT [FK_dim_PurchaseOrderLine_UnitOfMeasureKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_DocumentDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_DocumentDateKey] FOREIGN KEY ([DocumentDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_DocumentDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_PostingDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_PostingDateKey] FOREIGN KEY ([PostingDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_PostingDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_ReceiptDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_ReceiptDateKey] FOREIGN KEY ([ReceiptDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_ReceiptDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_ReceiverEmployeeKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_ReceiverEmployeeKey] FOREIGN KEY ([ReceiverEmployeeKey]) REFERENCES [dim].[Employee] ([EmployeeKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_ReceiverEmployeeKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_PlantKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_PlantKey] FOREIGN KEY ([PlantKey]) REFERENCES [dim].[Plant] ([PlantKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_PlantKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_ProductKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_ProductKey] FOREIGN KEY ([ProductKey]) REFERENCES [dim].[Product] ([ProductKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_ProductKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_PurchaseOrderLineKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_PurchaseOrderLineKey] FOREIGN KEY ([PurchaseOrderLineKey]) REFERENCES [dim].[PurchaseOrderLine] ([PurchaseOrderLineKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_PurchaseOrderLineKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_SupplierKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dim].[Supplier] ([SupplierKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_SupplierKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_ReceiptTimeOfDayKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_ReceiptTimeOfDayKey] FOREIGN KEY ([ReceiptTimeOfDayKey]) REFERENCES [dim].[TimeOfDay] ([TimeOfDayKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_ReceiptTimeOfDayKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_CurrencyKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_CurrencyKey] FOREIGN KEY ([CurrencyKey]) REFERENCES [ref].[Currency] ([CurrencyKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_CurrencyKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_PurchaseReceiptStatusKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_PurchaseReceiptStatusKey] FOREIGN KEY ([PurchaseReceiptStatusKey]) REFERENCES [ref].[PurchaseReceiptStatus] ([PurchaseReceiptStatusKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_PurchaseReceiptStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseGoodsReceipt_UnitOfMeasureKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseGoodsReceipt'))
BEGIN
    ALTER TABLE [fact].[PurchaseGoodsReceipt] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseGoodsReceipt_UnitOfMeasureKey] FOREIGN KEY ([UnitOfMeasureKey]) REFERENCES [ref].[UnitOfMeasure] ([UnitOfMeasureKey]);
    ALTER TABLE [fact].[PurchaseGoodsReceipt] CHECK CONSTRAINT [FK_fact_PurchaseGoodsReceipt_UnitOfMeasureKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseInvoiceMatch_CostCenterKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseInvoiceMatch'))
BEGIN
    ALTER TABLE [fact].[PurchaseInvoiceMatch] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseInvoiceMatch_CostCenterKey] FOREIGN KEY ([CostCenterKey]) REFERENCES [dim].[CostCenter] ([CostCenterKey]);
    ALTER TABLE [fact].[PurchaseInvoiceMatch] CHECK CONSTRAINT [FK_fact_PurchaseInvoiceMatch_CostCenterKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseInvoiceMatch_InvoiceDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseInvoiceMatch'))
BEGIN
    ALTER TABLE [fact].[PurchaseInvoiceMatch] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseInvoiceMatch_InvoiceDateKey] FOREIGN KEY ([InvoiceDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseInvoiceMatch] CHECK CONSTRAINT [FK_fact_PurchaseInvoiceMatch_InvoiceDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseInvoiceMatch_MatchDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseInvoiceMatch'))
BEGIN
    ALTER TABLE [fact].[PurchaseInvoiceMatch] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseInvoiceMatch_MatchDateKey] FOREIGN KEY ([MatchDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseInvoiceMatch] CHECK CONSTRAINT [FK_fact_PurchaseInvoiceMatch_MatchDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseInvoiceMatch_PostingDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseInvoiceMatch'))
BEGIN
    ALTER TABLE [fact].[PurchaseInvoiceMatch] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseInvoiceMatch_PostingDateKey] FOREIGN KEY ([PostingDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseInvoiceMatch] CHECK CONSTRAINT [FK_fact_PurchaseInvoiceMatch_PostingDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseInvoiceMatch_ProductKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseInvoiceMatch'))
BEGIN
    ALTER TABLE [fact].[PurchaseInvoiceMatch] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseInvoiceMatch_ProductKey] FOREIGN KEY ([ProductKey]) REFERENCES [dim].[Product] ([ProductKey]);
    ALTER TABLE [fact].[PurchaseInvoiceMatch] CHECK CONSTRAINT [FK_fact_PurchaseInvoiceMatch_ProductKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseInvoiceMatch_PurchaseOrderLineKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseInvoiceMatch'))
BEGIN
    ALTER TABLE [fact].[PurchaseInvoiceMatch] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseInvoiceMatch_PurchaseOrderLineKey] FOREIGN KEY ([PurchaseOrderLineKey]) REFERENCES [dim].[PurchaseOrderLine] ([PurchaseOrderLineKey]);
    ALTER TABLE [fact].[PurchaseInvoiceMatch] CHECK CONSTRAINT [FK_fact_PurchaseInvoiceMatch_PurchaseOrderLineKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseInvoiceMatch_SupplierKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseInvoiceMatch'))
BEGIN
    ALTER TABLE [fact].[PurchaseInvoiceMatch] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseInvoiceMatch_SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dim].[Supplier] ([SupplierKey]);
    ALTER TABLE [fact].[PurchaseInvoiceMatch] CHECK CONSTRAINT [FK_fact_PurchaseInvoiceMatch_SupplierKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseInvoiceMatch_CurrencyKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseInvoiceMatch'))
BEGIN
    ALTER TABLE [fact].[PurchaseInvoiceMatch] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseInvoiceMatch_CurrencyKey] FOREIGN KEY ([CurrencyKey]) REFERENCES [ref].[Currency] ([CurrencyKey]);
    ALTER TABLE [fact].[PurchaseInvoiceMatch] CHECK CONSTRAINT [FK_fact_PurchaseInvoiceMatch_CurrencyKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseInvoiceMatch_PurchaseInvoiceMatchStatusKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseInvoiceMatch'))
BEGIN
    ALTER TABLE [fact].[PurchaseInvoiceMatch] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseInvoiceMatch_PurchaseInvoiceMatchStatusKey] FOREIGN KEY ([PurchaseInvoiceMatchStatusKey]) REFERENCES [ref].[PurchaseInvoiceMatchStatus] ([PurchaseInvoiceMatchStatusKey]);
    ALTER TABLE [fact].[PurchaseInvoiceMatch] CHECK CONSTRAINT [FK_fact_PurchaseInvoiceMatch_PurchaseInvoiceMatchStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseOrderLineToReceipt_PlantKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseOrderLineToReceipt'))
BEGIN
    ALTER TABLE [bridge].[PurchaseOrderLineToReceipt] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseOrderLineToReceipt_PlantKey] FOREIGN KEY ([PlantKey]) REFERENCES [dim].[Plant] ([PlantKey]);
    ALTER TABLE [bridge].[PurchaseOrderLineToReceipt] CHECK CONSTRAINT [FK_bridge_PurchaseOrderLineToReceipt_PlantKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseOrderLineToReceipt_ProductKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseOrderLineToReceipt'))
BEGIN
    ALTER TABLE [bridge].[PurchaseOrderLineToReceipt] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseOrderLineToReceipt_ProductKey] FOREIGN KEY ([ProductKey]) REFERENCES [dim].[Product] ([ProductKey]);
    ALTER TABLE [bridge].[PurchaseOrderLineToReceipt] CHECK CONSTRAINT [FK_bridge_PurchaseOrderLineToReceipt_ProductKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseOrderLineToReceipt_PurchaseOrderLineKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseOrderLineToReceipt'))
BEGIN
    ALTER TABLE [bridge].[PurchaseOrderLineToReceipt] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseOrderLineToReceipt_PurchaseOrderLineKey] FOREIGN KEY ([PurchaseOrderLineKey]) REFERENCES [dim].[PurchaseOrderLine] ([PurchaseOrderLineKey]);
    ALTER TABLE [bridge].[PurchaseOrderLineToReceipt] CHECK CONSTRAINT [FK_bridge_PurchaseOrderLineToReceipt_PurchaseOrderLineKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseOrderLineToReceipt_PurchaseReceiptStatusKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseOrderLineToReceipt'))
BEGIN
    ALTER TABLE [bridge].[PurchaseOrderLineToReceipt] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseOrderLineToReceipt_PurchaseReceiptStatusKey] FOREIGN KEY ([PurchaseReceiptStatusKey]) REFERENCES [ref].[PurchaseReceiptStatus] ([PurchaseReceiptStatusKey]);
    ALTER TABLE [bridge].[PurchaseOrderLineToReceipt] CHECK CONSTRAINT [FK_bridge_PurchaseOrderLineToReceipt_PurchaseReceiptStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_CostCenterKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_CostCenterKey] FOREIGN KEY ([CostCenterKey]) REFERENCES [dim].[CostCenter] ([CostCenterKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_CostCenterKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_OrderDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_OrderDateKey] FOREIGN KEY ([OrderDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_OrderDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_PromisedDeliveryDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_PromisedDeliveryDateKey] FOREIGN KEY ([PromisedDeliveryDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_PromisedDeliveryDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_RequestedDeliveryDateKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_RequestedDeliveryDateKey] FOREIGN KEY ([RequestedDeliveryDateKey]) REFERENCES [dim].[Date] ([DateKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_RequestedDeliveryDateKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_PlantKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_PlantKey] FOREIGN KEY ([PlantKey]) REFERENCES [dim].[Plant] ([PlantKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_PlantKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_ProductKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_ProductKey] FOREIGN KEY ([ProductKey]) REFERENCES [dim].[Product] ([ProductKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_ProductKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_PurchaseOrderHeaderKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_PurchaseOrderHeaderKey] FOREIGN KEY ([PurchaseOrderHeaderKey]) REFERENCES [dim].[PurchaseOrderHeader] ([PurchaseOrderHeaderKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_PurchaseOrderHeaderKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_PurchaseOrderLineKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_PurchaseOrderLineKey] FOREIGN KEY ([PurchaseOrderLineKey]) REFERENCES [dim].[PurchaseOrderLine] ([PurchaseOrderLineKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_PurchaseOrderLineKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_SupplierKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dim].[Supplier] ([SupplierKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_SupplierKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_CurrencyKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_CurrencyKey] FOREIGN KEY ([CurrencyKey]) REFERENCES [ref].[Currency] ([CurrencyKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_CurrencyKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_PurchaseOrderLifecycleStatusKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_PurchaseOrderLifecycleStatusKey] FOREIGN KEY ([PurchaseOrderLifecycleStatusKey]) REFERENCES [ref].[PurchaseOrderLifecycleStatus] ([PurchaseOrderLifecycleStatusKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_PurchaseOrderLifecycleStatusKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_fact_PurchaseOrderSpend_UnitOfMeasureKey' AND parent_object_id = OBJECT_ID(N'fact.PurchaseOrderSpend'))
BEGIN
    ALTER TABLE [fact].[PurchaseOrderSpend] WITH CHECK ADD CONSTRAINT [FK_fact_PurchaseOrderSpend_UnitOfMeasureKey] FOREIGN KEY ([UnitOfMeasureKey]) REFERENCES [ref].[UnitOfMeasure] ([UnitOfMeasureKey]);
    ALTER TABLE [fact].[PurchaseOrderSpend] CHECK CONSTRAINT [FK_fact_PurchaseOrderSpend_UnitOfMeasureKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseRequisitionToOrderLine_PurchaseOrderLineKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseRequisitionToOrderLine'))
BEGIN
    ALTER TABLE [bridge].[PurchaseRequisitionToOrderLine] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseRequisitionToOrderLine_PurchaseOrderLineKey] FOREIGN KEY ([PurchaseOrderLineKey]) REFERENCES [dim].[PurchaseOrderLine] ([PurchaseOrderLineKey]);
    ALTER TABLE [bridge].[PurchaseRequisitionToOrderLine] CHECK CONSTRAINT [FK_bridge_PurchaseRequisitionToOrderLine_PurchaseOrderLineKey];
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_bridge_PurchaseRequisitionToOrderLine_PurchaseRequisitionKey' AND parent_object_id = OBJECT_ID(N'bridge.PurchaseRequisitionToOrderLine'))
BEGIN
    ALTER TABLE [bridge].[PurchaseRequisitionToOrderLine] WITH CHECK ADD CONSTRAINT [FK_bridge_PurchaseRequisitionToOrderLine_PurchaseRequisitionKey] FOREIGN KEY ([PurchaseRequisitionKey]) REFERENCES [dim].[PurchaseRequisition] ([PurchaseRequisitionKey]);
    ALTER TABLE [bridge].[PurchaseRequisitionToOrderLine] CHECK CONSTRAINT [FK_bridge_PurchaseRequisitionToOrderLine_PurchaseRequisitionKey];
END
GO
