-- Generated by tools.generator. Do not hand-edit.

-- Subject area: etl

IF OBJECT_ID(N'etl.AlertLog', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[AlertLog] (
    [AlertLogId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [AlertCode] NVARCHAR(60) NOT NULL,
    [AlertSeverityCode] NVARCHAR(30) NOT NULL,
    [AlertMessage] NVARCHAR(max) NOT NULL,
    [RaisedAtUtc] DATETIME2(3) NOT NULL,
    [AcknowledgedAtUtc] DATETIME2(3) NULL,
    CONSTRAINT [PK_etl_AlertLog] PRIMARY KEY CLUSTERED ([AlertLogId])
);
END
GO

IF OBJECT_ID(N'etl.BatchRun', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[BatchRun] (
    [BatchId] BIGINT IDENTITY(1,1) NOT NULL,
    [SourceSystemCode] NVARCHAR(30) NOT NULL,
    [BatchStatusCode] NVARCHAR(30) NOT NULL,
    [StartedAtUtc] DATETIME2(3) NOT NULL,
    [EndedAtUtc] DATETIME2(3) NULL,
    [RequestedByName] NVARCHAR(120) NULL,
    [CorrelationId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_etl_BatchRun] PRIMARY KEY CLUSTERED ([BatchId])
);
END
GO

IF OBJECT_ID(N'etl.BatchRunStep', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[BatchRunStep] (
    [BatchStepId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [StepName] NVARCHAR(120) NOT NULL,
    [StepStatusCode] NVARCHAR(30) NOT NULL,
    [StartedAtUtc] DATETIME2(3) NOT NULL,
    [EndedAtUtc] DATETIME2(3) NULL,
    [ErrorMessage] NVARCHAR(max) NULL,
    CONSTRAINT [PK_etl_BatchRunStep] PRIMARY KEY CLUSTERED ([BatchStepId])
);
END
GO

IF OBJECT_ID(N'etl.ColumnLineage', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[ColumnLineage] (
    [ColumnLineageId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [SourceColumnName] NVARCHAR(256) NOT NULL,
    [TargetColumnName] NVARCHAR(256) NOT NULL,
    [TransformExpression] NVARCHAR(max) NULL,
    [LineageCapturedAtUtc] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_etl_ColumnLineage] PRIMARY KEY CLUSTERED ([ColumnLineageId])
);
END
GO

IF OBJECT_ID(N'etl.DeploymentLog', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[DeploymentLog] (
    [DeploymentLogId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [DeploymentName] NVARCHAR(160) NOT NULL,
    [EnvironmentName] NVARCHAR(60) NOT NULL,
    [DeploymentStatusCode] NVARCHAR(30) NOT NULL,
    [StartedAtUtc] DATETIME2(3) NOT NULL,
    [EndedAtUtc] DATETIME2(3) NULL,
    CONSTRAINT [PK_etl_DeploymentLog] PRIMARY KEY CLUSTERED ([DeploymentLogId])
);
END
GO

IF OBJECT_ID(N'etl.DqResult', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[DqResult] (
    [DqResultId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [DqRuleId] INT NOT NULL,
    [CheckedRowCount] BIGINT NOT NULL,
    [FailedRowCount] BIGINT NOT NULL,
    [ResultStatusCode] NVARCHAR(30) NOT NULL,
    [CheckedAtUtc] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_etl_DqResult] PRIMARY KEY CLUSTERED ([DqResultId])
);
END
GO

IF OBJECT_ID(N'etl.DqRule', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[DqRule] (
    [DqRuleId] BIGINT IDENTITY(1,1) NOT NULL,
    [RuleCode] NVARCHAR(60) NOT NULL,
    [RuleName] NVARCHAR(160) NOT NULL,
    [TargetTableName] NVARCHAR(128) NOT NULL,
    [RuleExpression] NVARCHAR(max) NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [PK_etl_DqRule] PRIMARY KEY CLUSTERED ([DqRuleId])
);
END
GO

IF OBJECT_ID(N'etl.DqRuleSeverity', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[DqRuleSeverity] (
    [DqRuleSeverityId] BIGINT IDENTITY(1,1) NOT NULL,
    [SeverityCode] NVARCHAR(30) NOT NULL,
    [SeverityName] NVARCHAR(80) NOT NULL,
    [FailureThresholdPercent] DECIMAL(9,4) NULL,
    [BlocksLoadFlag] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [PK_etl_DqRuleSeverity] PRIMARY KEY CLUSTERED ([DqRuleSeverityId])
);
END
GO

IF OBJECT_ID(N'etl.EtlSourceSystem', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[EtlSourceSystem] (
    [SourceSystemId] BIGINT IDENTITY(1,1) NOT NULL,
    [SourceSystemCode] NVARCHAR(30) NOT NULL,
    [SourceSystemName] NVARCHAR(100) NOT NULL,
    [ConnectionName] NVARCHAR(120) NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
    [CreatedAtUtc] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_etl_EtlSourceSystem] PRIMARY KEY CLUSTERED ([SourceSystemId])
);
END
GO

IF OBJECT_ID(N'etl.FileIngestLog', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[FileIngestLog] (
    [FileIngestLogId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [LandingFileId] BIGINT NOT NULL,
    [IngestStatusCode] NVARCHAR(30) NOT NULL,
    [RowsReadCount] BIGINT NOT NULL,
    [RowsLoadedCount] BIGINT NOT NULL,
    [IngestedAtUtc] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_etl_FileIngestLog] PRIMARY KEY CLUSTERED ([FileIngestLogId])
);
END
GO

IF OBJECT_ID(N'etl.IndexMaintenanceLog', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[IndexMaintenanceLog] (
    [IndexMaintenanceLogId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [SchemaName] NVARCHAR(128) NOT NULL,
    [TableName] NVARCHAR(128) NOT NULL,
    [IndexName] NVARCHAR(128) NOT NULL,
    [MaintenanceActionName] NVARCHAR(60) NOT NULL,
    [FragmentationPercent] DECIMAL(9,4) NULL,
    CONSTRAINT [PK_etl_IndexMaintenanceLog] PRIMARY KEY CLUSTERED ([IndexMaintenanceLogId])
);
END
GO

IF OBJECT_ID(N'etl.JobDefinition', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[JobDefinition] (
    [JobDefinitionId] BIGINT IDENTITY(1,1) NOT NULL,
    [JobCode] NVARCHAR(60) NOT NULL,
    [JobName] NVARCHAR(160) NOT NULL,
    [OwnerTeamName] NVARCHAR(120) NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [PK_etl_JobDefinition] PRIMARY KEY CLUSTERED ([JobDefinitionId])
);
END
GO

IF OBJECT_ID(N'etl.JobRunHistory', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[JobRunHistory] (
    [JobRunHistoryId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [JobDefinitionId] INT NOT NULL,
    [RunStatusCode] NVARCHAR(30) NOT NULL,
    [StartedAtUtc] DATETIME2(3) NOT NULL,
    [EndedAtUtc] DATETIME2(3) NULL,
    [AttemptNumber] INT NOT NULL,
    CONSTRAINT [PK_etl_JobRunHistory] PRIMARY KEY CLUSTERED ([JobRunHistoryId])
);
END
GO

IF OBJECT_ID(N'etl.JobSchedule', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[JobSchedule] (
    [JobScheduleId] BIGINT IDENTITY(1,1) NOT NULL,
    [JobDefinitionId] INT NOT NULL,
    [ScheduleName] NVARCHAR(120) NOT NULL,
    [CronExpression] NVARCHAR(120) NULL,
    [TimeZoneCode] NVARCHAR(60) NOT NULL,
    [NextRunAtUtc] DATETIME2(3) NULL,
    CONSTRAINT [PK_etl_JobSchedule] PRIMARY KEY CLUSTERED ([JobScheduleId])
);
END
GO

IF OBJECT_ID(N'etl.LandingFile', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[LandingFile] (
    [LandingFileId] BIGINT IDENTITY(1,1) NOT NULL,
    [SourceSystemCode] NVARCHAR(30) NOT NULL,
    [FilePathText] NVARCHAR(500) NOT NULL,
    [FileName] NVARCHAR(260) NOT NULL,
    [FileSizeBytes] BIGINT NULL,
    [ReceivedAtUtc] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_etl_LandingFile] PRIMARY KEY CLUSTERED ([LandingFileId])
);
END
GO

IF OBJECT_ID(N'etl.LoadError', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[LoadError] (
    [LoadErrorId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [SchemaName] NVARCHAR(128) NOT NULL,
    [TableName] NVARCHAR(128) NOT NULL,
    [ErrorCode] NVARCHAR(60) NULL,
    [ErrorMessage] NVARCHAR(max) NOT NULL,
    [OccurredAtUtc] DATETIME2(3) NOT NULL,
    CONSTRAINT [PK_etl_LoadError] PRIMARY KEY CLUSTERED ([LoadErrorId])
);
END
GO

IF OBJECT_ID(N'etl.LoadWatermark', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[LoadWatermark] (
    [WatermarkId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [SourceSystemCode] NVARCHAR(30) NOT NULL,
    [SchemaName] NVARCHAR(128) NOT NULL,
    [TableName] NVARCHAR(128) NOT NULL,
    [WatermarkColumnName] NVARCHAR(128) NOT NULL,
    [WatermarkValue] NVARCHAR(200) NULL,
    CONSTRAINT [PK_etl_LoadWatermark] PRIMARY KEY CLUSTERED ([WatermarkId])
);
END
GO

IF OBJECT_ID(N'etl.MergeStatistic', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[MergeStatistic] (
    [MergeStatisticId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [TargetSchemaName] NVARCHAR(128) NOT NULL,
    [TargetTableName] NVARCHAR(128) NOT NULL,
    [MatchedRowCount] BIGINT NOT NULL,
    [InsertedRowCount] BIGINT NOT NULL,
    [UpdatedRowCount] BIGINT NOT NULL,
    CONSTRAINT [PK_etl_MergeStatistic] PRIMARY KEY CLUSTERED ([MergeStatisticId])
);
END
GO

IF OBJECT_ID(N'etl.ProcessLock', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[ProcessLock] (
    [ProcessLockId] BIGINT IDENTITY(1,1) NOT NULL,
    [LockName] NVARCHAR(120) NOT NULL,
    [AcquiredByName] NVARCHAR(120) NOT NULL,
    [AcquiredAtUtc] DATETIME2(3) NOT NULL,
    [ExpiresAtUtc] DATETIME2(3) NOT NULL,
    [LockToken] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_etl_ProcessLock] PRIMARY KEY CLUSTERED ([ProcessLockId])
);
END
GO

IF OBJECT_ID(N'etl.RejectedRow', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[RejectedRow] (
    [RejectedRowId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [TargetSchemaName] NVARCHAR(128) NOT NULL,
    [TargetTableName] NVARCHAR(128) NOT NULL,
    [SourceRowNumber] BIGINT NULL,
    [RejectReasonText] NVARCHAR(max) NOT NULL,
    [RejectedPayload] NVARCHAR(max) NULL,
    CONSTRAINT [PK_etl_RejectedRow] PRIMARY KEY CLUSTERED ([RejectedRowId])
);
END
GO

IF OBJECT_ID(N'etl.RetentionPolicy', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[RetentionPolicy] (
    [RetentionPolicyId] BIGINT IDENTITY(1,1) NOT NULL,
    [TargetSchemaName] NVARCHAR(128) NOT NULL,
    [TargetTableName] NVARCHAR(128) NOT NULL,
    [RetentionDays] INT NOT NULL,
    [ArchiveBeforeDeleteFlag] BIT NOT NULL DEFAULT 0,
    [IsEnabled] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [PK_etl_RetentionPolicy] PRIMARY KEY CLUSTERED ([RetentionPolicyId])
);
END
GO

IF OBJECT_ID(N'etl.RowCountAudit', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[RowCountAudit] (
    [RowCountAuditId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [SchemaName] NVARCHAR(128) NOT NULL,
    [TableName] NVARCHAR(128) NOT NULL,
    [SourceRowCount] BIGINT NOT NULL,
    [InsertedRowCount] BIGINT NOT NULL,
    [UpdatedRowCount] BIGINT NOT NULL,
    [RejectedRowCount] BIGINT NOT NULL,
    CONSTRAINT [PK_etl_RowCountAudit] PRIMARY KEY CLUSTERED ([RowCountAuditId])
);
END
GO

IF OBJECT_ID(N'etl.ScdChangeLog', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[ScdChangeLog] (
    [ScdChangeLogId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [DimensionName] NVARCHAR(128) NOT NULL,
    [BusinessKeyValue] NVARCHAR(200) NOT NULL,
    [ChangeTypeCode] NVARCHAR(30) NOT NULL,
    [PreviousRowHash] VARBINARY(32) NULL,
    [NewRowHash] VARBINARY(32) NULL,
    CONSTRAINT [PK_etl_ScdChangeLog] PRIMARY KEY CLUSTERED ([ScdChangeLogId])
);
END
GO

IF OBJECT_ID(N'etl.SchemaVersion', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[SchemaVersion] (
    [SchemaVersionId] BIGINT IDENTITY(1,1) NOT NULL,
    [VersionNumber] NVARCHAR(40) NOT NULL,
    [AppliedAtUtc] DATETIME2(3) NOT NULL,
    [AppliedByName] NVARCHAR(120) NULL,
    [ScriptName] NVARCHAR(260) NOT NULL,
    [ChecksumValue] VARBINARY(32) NULL,
    CONSTRAINT [PK_etl_SchemaVersion] PRIMARY KEY CLUSTERED ([SchemaVersionId])
);
END
GO

IF OBJECT_ID(N'etl.TableLineage', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[TableLineage] (
    [TableLineageId] BIGINT IDENTITY(1,1) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [SourceObjectName] NVARCHAR(256) NOT NULL,
    [TargetSchemaName] NVARCHAR(128) NOT NULL,
    [TargetTableName] NVARCHAR(128) NOT NULL,
    [DependencyTypeName] NVARCHAR(60) NOT NULL,
    CONSTRAINT [PK_etl_TableLineage] PRIMARY KEY CLUSTERED ([TableLineageId])
);
END
GO

IF OBJECT_ID(N'etl.TableLoadConfig', N'U') IS NULL
BEGIN
CREATE TABLE [etl].[TableLoadConfig] (
    [TableLoadConfigId] BIGINT IDENTITY(1,1) NOT NULL,
    [SourceObjectName] NVARCHAR(256) NOT NULL,
    [TargetSchemaName] NVARCHAR(128) NOT NULL,
    [TargetTableName] NVARCHAR(128) NOT NULL,
    [LoadPatternName] NVARCHAR(60) NOT NULL,
    [IsEnabled] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [PK_etl_TableLoadConfig] PRIMARY KEY CLUSTERED ([TableLoadConfigId])
);
END
GO
