-- Generated by tools.generator. Do not hand-edit.

-- Subject area: finance_costing

IF OBJECT_ID(N'stg.FinanceCostComponentAllocation', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceCostComponentAllocation] (
    [AllocationRatio] DECIMAL(9,6) NOT NULL,
    [ComponentCostAmount] MONEY NULL,
    [FinanceProductCostVersionProductCostVersionCode] NVARCHAR(60) NOT NULL,
    [FinanceCostComponentDetailFinanceCostComponentDetailCode] NVARCHAR(30) NOT NULL,
    [FinanceCostElementDetailFinanceCostElementDetailCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinanceJournalProfitabilityAssignment', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceJournalProfitabilityAssignment] (
    [AllocationRatio] DECIMAL(9,6) NOT NULL,
    [AllocatedAmount] MONEY NULL,
    [FinanceJournalLineJournalLineCode] NVARCHAR(70) NOT NULL,
    [FinanceProfitObjectFinanceProfitObjectCode] NVARCHAR(30) NOT NULL,
    [BusinessUnitBusinessUnitCode] NVARCHAR(40) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinanceJournalHeader', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceJournalHeader] (
    [JournalEntryNumber] NVARCHAR(50) NOT NULL,
    [JournalEntryName] NVARCHAR(160) NULL,
    [FiscalDocumentNumber] NVARCHAR(60) NULL,
    [ReversalJournalEntryNumber] NVARCHAR(50) NULL,
    [BusinessUnitBusinessUnitCode] NVARCHAR(40) NOT NULL,
    [PreparerEmployeeEmployeeNumber] NVARCHAR(40) NULL,
    [ApproverEmployeeEmployeeNumber] NVARCHAR(40) NULL,
    [FinancePostingStatusPostingStatusCode] NVARCHAR(20) NOT NULL,
    [FinanceJournalSourceJournalSourceCode] NVARCHAR(30) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinanceJournalLine', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceJournalLine] (
    [JournalLineCode] NVARCHAR(70) NOT NULL,
    [JournalLineSequenceNumber] INT NOT NULL,
    [LineMemo] NVARCHAR(200) NULL,
    [IsReversalLine] BIT NOT NULL DEFAULT 0,
    [FinanceJournalHeaderJournalEntryNumber] NVARCHAR(50) NOT NULL,
    [GlAccountGlAccountNumber] NVARCHAR(40) NOT NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NULL,
    [FinancePostingBucketFinancePostingBucketCode] NVARCHAR(30) NOT NULL,
    [FinancePostingStatusPostingStatusCode] NVARCHAR(20) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinancePlanningVersion', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinancePlanningVersion] (
    [PlanningVersionCode] NVARCHAR(40) NOT NULL,
    [PlanningVersionName] NVARCHAR(160) NOT NULL,
    [VersionStartDate] DATE NOT NULL,
    [VersionEndDate] DATE NOT NULL,
    [BusinessUnitBusinessUnitCode] NVARCHAR(40) NOT NULL,
    [FinanceScenarioTypeScenarioTypeCode] NVARCHAR(20) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinanceProductCostVersion', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceProductCostVersion] (
    [ProductCostVersionCode] NVARCHAR(60) NOT NULL,
    [CostVersionName] NVARCHAR(160) NOT NULL,
    [EffectiveDate] DATE NOT NULL,
    [ExpirationDate] DATE NULL,
    [ProductProductNumber] NVARCHAR(40) NOT NULL,
    [PlantPlantCode] NVARCHAR(40) NOT NULL,
    [FinanceCostComponentDetailFinanceCostComponentDetailCode] NVARCHAR(30) NOT NULL,
    [FinanceCostingMethodCostingMethodCode] NVARCHAR(20) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinanceProductionSettlement', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceProductionSettlement] (
    [ProductionSettlementNumber] NVARCHAR(50) NOT NULL,
    [SettlementName] NVARCHAR(160) NULL,
    [SettlementPeriodCode] NVARCHAR(20) NULL,
    [IsFinalSettlement] BIT NOT NULL DEFAULT 0,
    [ProductProductNumber] NVARCHAR(40) NOT NULL,
    [PlantPlantCode] NVARCHAR(40) NOT NULL,
    [WorkCenterWorkCenterCode] NVARCHAR(40) NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NULL,
    [FinancePostingStatusPostingStatusCode] NVARCHAR(20) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinanceBudgetForecast', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceBudgetForecast] (
    [BudgetAmount] MONEY NOT NULL,
    [ForecastAmount] MONEY NOT NULL,
    [BudgetQuantity] DECIMAL(18,4) NULL,
    [ForecastQuantity] DECIMAL(18,4) NULL,
    [SnapshotDateKey] INT NOT NULL,
    [FiscalPeriodDateKey] INT NOT NULL,
    [FinancePlanningVersionPlanningVersionCode] NVARCHAR(40) NOT NULL,
    [GlAccountGlAccountNumber] NVARCHAR(40) NOT NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NULL,
    [BusinessUnitBusinessUnitCode] NVARCHAR(40) NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NULL,
    [FinanceProfitObjectFinanceProfitObjectCode] NVARCHAR(30) NULL,
    [FinanceScenarioTypeScenarioTypeCode] NVARCHAR(20) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinanceGlPosting', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceGlPosting] (
    [AccountingDocumentNumber] NVARCHAR(50) NOT NULL,
    [AccountingDocumentLineNumber] INT NOT NULL,
    [DebitAmount] MONEY NOT NULL,
    [CreditAmount] MONEY NOT NULL,
    [NetPostingAmount] MONEY NOT NULL,
    [Quantity] DECIMAL(18,4) NULL,
    [PostingDateKey] INT NOT NULL,
    [DocumentDateKey] INT NOT NULL,
    [EntryDateKey] INT NOT NULL,
    [EntryTimeOfDayKey] INT NOT NULL,
    [FinanceJournalHeaderJournalEntryNumber] NVARCHAR(50) NOT NULL,
    [FinanceJournalLineJournalLineCode] NVARCHAR(70) NOT NULL,
    [GlAccountGlAccountNumber] NVARCHAR(40) NOT NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NULL,
    [BusinessUnitBusinessUnitCode] NVARCHAR(40) NOT NULL,
    [FinancePostingBucketFinancePostingBucketCode] NVARCHAR(30) NOT NULL,
    [FinancePostingStatusPostingStatusCode] NVARCHAR(20) NOT NULL,
    [FinanceJournalSourceJournalSourceCode] NVARCHAR(30) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinanceManufacturingVariance', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceManufacturingVariance] (
    [ProductionOrderNumber] NVARCHAR(50) NOT NULL,
    [OperationSequenceNumber] INT NOT NULL,
    [StandardAmount] MONEY NOT NULL,
    [ActualAmount] MONEY NOT NULL,
    [VarianceAmount] MONEY NOT NULL,
    [VarianceQuantity] DECIMAL(18,4) NULL,
    [PostingDateKey] INT NOT NULL,
    [ProductionDateKey] INT NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NOT NULL,
    [PlantPlantCode] NVARCHAR(40) NOT NULL,
    [WorkCenterWorkCenterCode] NVARCHAR(40) NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NULL,
    [FinanceCostElementDetailFinanceCostElementDetailCode] NVARCHAR(30) NOT NULL,
    [FinanceVarianceTypeVarianceTypeCode] NVARCHAR(30) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinanceProductCostSnapshot', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceProductCostSnapshot] (
    [StandardCostAmount] MONEY NOT NULL,
    [ActualCostAmount] MONEY NOT NULL,
    [CostVarianceAmount] MONEY NOT NULL,
    [CostQuantity] DECIMAL(18,4) NOT NULL,
    [SnapshotDateKey] INT NOT NULL,
    [EffectiveDateKey] INT NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NOT NULL,
    [PlantPlantCode] NVARCHAR(40) NOT NULL,
    [FinanceProductCostVersionProductCostVersionCode] NVARCHAR(60) NOT NULL,
    [FinanceCostComponentDetailFinanceCostComponentDetailCode] NVARCHAR(30) NOT NULL,
    [FinanceCostElementDetailFinanceCostElementDetailCode] NVARCHAR(30) NOT NULL,
    [FinanceCostingMethodCostingMethodCode] NVARCHAR(20) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinanceProductionOrderSettlement', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinanceProductionOrderSettlement] (
    [ProductionOrderNumber] NVARCHAR(50) NOT NULL,
    [SettledQuantity] DECIMAL(18,4) NOT NULL,
    [SettledAmount] MONEY NOT NULL,
    [WipReliefAmount] MONEY NOT NULL,
    [SettlementDateKey] INT NOT NULL,
    [PostingDateKey] INT NOT NULL,
    [FinanceProductionSettlementProductionSettlementNumber] NVARCHAR(50) NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NOT NULL,
    [PlantPlantCode] NVARCHAR(40) NOT NULL,
    [WorkCenterWorkCenterCode] NVARCHAR(40) NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NULL,
    [FinanceCostElementDetailFinanceCostElementDetailCode] NVARCHAR(30) NOT NULL,
    [FinancePostingStatusPostingStatusCode] NVARCHAR(20) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FinancePurchasePriceVariance', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FinancePurchasePriceVariance] (
    [SupplierInvoiceNumber] NVARCHAR(50) NOT NULL,
    [PurchaseOrderNumber] NVARCHAR(40) NOT NULL,
    [InvoiceQuantity] DECIMAL(18,4) NOT NULL,
    [StandardCostAmount] MONEY NOT NULL,
    [ActualPriceAmount] MONEY NOT NULL,
    [PurchasePriceVarianceAmount] MONEY NOT NULL,
    [PostingDateKey] INT NOT NULL,
    [InvoiceDateKey] INT NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NOT NULL,
    [PlantPlantCode] NVARCHAR(40) NOT NULL,
    [SupplierSupplierNumber] NVARCHAR(40) NOT NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NULL,
    [FinanceCostElementDetailFinanceCostElementDetailCode] NVARCHAR(30) NOT NULL,
    [FinanceVarianceTypeVarianceTypeCode] NVARCHAR(30) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO
