-- Generated by tools.generator. Do not hand-edit.

-- Subject area: hr_labor

IF OBJECT_ID(N'stg.LaborEmployeeCertification', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborEmployeeCertification] (
    [IssuedDate] DATE NULL,
    [ExpirationDate] DATE NULL,
    [CertificationScore] DECIMAL(9,2) NULL,
    [EmployeeEmployeeNumber] NVARCHAR(40) NOT NULL,
    [LaborCertificationLaborCertificationCode] NVARCHAR(30) NOT NULL,
    [RecordStatusStatusCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborEmployeeCrew', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborEmployeeCrew] (
    [AssignmentStartDate] DATE NOT NULL,
    [AssignmentEndDate] DATE NULL,
    [AllocationRatio] DECIMAL(9,4) NOT NULL DEFAULT 1.0000,
    [EmployeeEmployeeNumber] NVARCHAR(40) NOT NULL,
    [LaborCrewLaborCrewCode] NVARCHAR(30) NOT NULL,
    [LaborTeamLaborTeamCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborEmployeeSkill', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborEmployeeSkill] (
    [ProficiencyRating] DECIMAL(9,2) NULL,
    [VerifiedDate] DATE NULL,
    [EmployeeEmployeeNumber] NVARCHAR(40) NOT NULL,
    [LaborSkillLaborSkillCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborAssignment', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborAssignment] (
    [LaborAssignmentNumber] NVARCHAR(40) NOT NULL,
    [AssignmentName] NVARCHAR(160) NOT NULL,
    [StandardWeeklyHours] DECIMAL(9,2) NOT NULL,
    [IsPrimaryAssignment] BIT NOT NULL DEFAULT 1,
    [EmployeeEmployeeNumber] NVARCHAR(40) NOT NULL,
    [PlantPlantCode] NVARCHAR(40) NOT NULL,
    [BusinessUnitBusinessUnitCode] NVARCHAR(40) NOT NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NOT NULL,
    [LaborJobGradeLaborJobGradeCode] NVARCHAR(30) NOT NULL,
    [LaborEmploymentStatusEmploymentStatusCode] NVARCHAR(20) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborCostRate', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborCostRate] (
    [LaborCostRateCode] NVARCHAR(50) NOT NULL,
    [HourlyCostAmount] MONEY NOT NULL,
    [OverheadCostAmount] MONEY NULL,
    [PremiumMultiplier] DECIMAL(9,4) NOT NULL DEFAULT 1.0000,
    [LaborJobGradeLaborJobGradeCode] NVARCHAR(30) NOT NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [LaborPayTypePayTypeCode] NVARCHAR(20) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborLeaveEntitlement', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborLeaveEntitlement] (
    [LeaveEntitlementCode] NVARCHAR(40) NOT NULL,
    [LeaveEntitlementName] NVARCHAR(140) NOT NULL,
    [AnnualHours] DECIMAL(9,2) NOT NULL,
    [CarryoverHours] DECIMAL(9,2) NULL,
    [LaborJobGradeLaborJobGradeCode] NVARCHAR(30) NOT NULL,
    [LaborAbsenceReasonAbsenceReasonCode] NVARCHAR(20) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborPosition', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborPosition] (
    [PositionNumber] NVARCHAR(40) NOT NULL,
    [PositionTitle] NVARCHAR(160) NOT NULL,
    [AuthorizedHeadcount] DECIMAL(12,2) NOT NULL,
    [IsUnionEligible] BIT NOT NULL DEFAULT 0,
    [LaborJobGradeLaborJobGradeCode] NVARCHAR(30) NOT NULL,
    [PlantPlantCode] NVARCHAR(40) NOT NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborTrainingCourse', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborTrainingCourse] (
    [TrainingCourseCode] NVARCHAR(40) NOT NULL,
    [TrainingCourseName] NVARCHAR(200) NOT NULL,
    [DurationHours] DECIMAL(9,2) NULL,
    [RenewalMonths] SMALLINT NULL,
    [LaborSkillCategoryLaborSkillCategoryCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborAbsence', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborAbsence] (
    [AbsenceRequestNumber] NVARCHAR(40) NOT NULL,
    [AbsenceHours] DECIMAL(18,4) NOT NULL,
    [PaidAbsenceHours] DECIMAL(18,4) NOT NULL,
    [AbsenceDateKey] INT NOT NULL,
    [SubmittedDateKey] INT NOT NULL,
    [ApprovedDateKey] INT NOT NULL,
    [StartTimeOfDayKey] INT NOT NULL,
    [EndTimeOfDayKey] INT NOT NULL,
    [EmployeeEmployeeNumber] NVARCHAR(40) NOT NULL,
    [LaborAssignmentLaborAssignmentNumber] NVARCHAR(40) NOT NULL,
    [LaborLeaveEntitlementLeaveEntitlementCode] NVARCHAR(40) NULL,
    [LaborAbsenceReasonAbsenceReasonCode] NVARCHAR(20) NOT NULL,
    [ApprovalStatusApprovalStatusCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborHeadcountSnapshot', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborHeadcountSnapshot] (
    [HeadcountQuantity] DECIMAL(18,4) NOT NULL,
    [FullTimeEquivalentQuantity] DECIMAL(18,4) NOT NULL,
    [OpenPositionQuantity] DECIMAL(18,4) NOT NULL,
    [SnapshotDateKey] INT NOT NULL,
    [PlantPlantCode] NVARCHAR(40) NOT NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NOT NULL,
    [BusinessUnitBusinessUnitCode] NVARCHAR(40) NOT NULL,
    [LaborJobGradeLaborJobGradeCode] NVARCHAR(30) NOT NULL,
    [LaborEmploymentStatusEmploymentStatusCode] NVARCHAR(20) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborTimesheet', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborTimesheet] (
    [TimesheetNumber] NVARCHAR(40) NOT NULL,
    [LaborClaimLineNumber] INT NOT NULL,
    [RegularHours] DECIMAL(18,4) NOT NULL,
    [OvertimeHours] DECIMAL(18,4) NOT NULL,
    [LaborCostAmount] MONEY NOT NULL,
    [ClaimDateKey] INT NOT NULL,
    [LaborDateKey] INT NOT NULL,
    [StartTimeOfDayKey] INT NOT NULL,
    [EndTimeOfDayKey] INT NOT NULL,
    [EmployeeEmployeeNumber] NVARCHAR(40) NOT NULL,
    [LaborAssignmentLaborAssignmentNumber] NVARCHAR(40) NOT NULL,
    [LaborRosterSlotLaborRosterSlotCode] NVARCHAR(30) NULL,
    [WorkCenterWorkCenterCode] NVARCHAR(40) NULL,
    [CostCenterCostCenterCode] NVARCHAR(40) NOT NULL,
    [LaborPayTypePayTypeCode] NVARCHAR(20) NOT NULL,
    [LaborClaimStatusLaborClaimStatusCode] NVARCHAR(20) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.LaborTrainingCompletion', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[LaborTrainingCompletion] (
    [TrainingAssignmentNumber] NVARCHAR(40) NOT NULL,
    [TrainingHours] DECIMAL(18,4) NOT NULL,
    [CompletionScore] DECIMAL(9,2) NULL,
    [AssignedDateKey] INT NOT NULL,
    [DueDateKey] INT NOT NULL,
    [CompletedDateKey] INT NOT NULL,
    [ExpiredDateKey] INT NOT NULL,
    [EmployeeEmployeeNumber] NVARCHAR(40) NOT NULL,
    [LaborTrainingCourseTrainingCourseCode] NVARCHAR(40) NOT NULL,
    [LaborCertificationLaborCertificationCode] NVARCHAR(30) NULL,
    [PlantPlantCode] NVARCHAR(40) NOT NULL,
    [LaborTrainingCompletionStatusTrainingCompletionStatusCode] NVARCHAR(20) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO
