-- Generated by tools.generator. Do not hand-edit.

-- Subject area: warranty_service

IF OBJECT_ID(N'stg.ServiceContractProduct', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[ServiceContractProduct] (
    [CoverageStartDate] DATE NOT NULL,
    [CoverageEndDate] DATE NULL,
    [ServiceContractServiceContractNumber] NVARCHAR(50) NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.ServiceOrderPart', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[ServiceOrderPart] (
    [StandardPartQuantity] DECIMAL(18,4) NOT NULL,
    [IsMandatoryPart] BIT NOT NULL DEFAULT 0,
    [ServiceRepairCodeServiceRepairCodeCode] NVARCHAR(30) NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NOT NULL,
    [UnitOfMeasureUomCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.WarrantyClaimRepairCode', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[WarrantyClaimRepairCode] (
    [RepairProbabilityRatio] DECIMAL(9,6) NULL,
    [StandardAllowanceAmount] MONEY NULL,
    [WarrantyFailureModeFailureModeCode] NVARCHAR(40) NOT NULL,
    [ServiceRepairCodeServiceRepairCodeCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.ServiceContract', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[ServiceContract] (
    [ServiceContractNumber] NVARCHAR(50) NOT NULL,
    [ServiceContractName] NVARCHAR(180) NOT NULL,
    [ContractValueAmount] MONEY NULL,
    [ResponseTimeHours] DECIMAL(9,2) NULL,
    [CustomerCustomerNumber] NVARCHAR(40) NOT NULL,
    [WarrantyTermWarrantyTermCode] NVARCHAR(30) NOT NULL,
    [ServiceTerritoryServiceTerritoryCode] NVARCHAR(30) NOT NULL,
    [ServiceContractStatusServiceContractStatusCode] NVARCHAR(20) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.ServiceTechnicianProfile', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[ServiceTechnicianProfile] (
    [TechnicianProfileNumber] NVARCHAR(50) NOT NULL,
    [TechnicianDisplayName] NVARCHAR(160) NOT NULL,
    [DispatchRadiusKm] DECIMAL(9,2) NULL,
    [RemoteSupportEligible] BIT NOT NULL DEFAULT 0,
    [EmployeeEmployeeNumber] NVARCHAR(40) NOT NULL,
    [ServiceTerritoryServiceTerritoryCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.FieldServiceOrderTransaction', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[FieldServiceOrderTransaction] (
    [ServiceOrderNumber] NVARCHAR(50) NOT NULL,
    [ProductSerialNumber] NVARCHAR(80) NOT NULL,
    [LaborHours] DECIMAL(18,4) NOT NULL,
    [TravelHours] DECIMAL(18,4) NULL,
    [ServiceCostAmount] MONEY NOT NULL,
    [FirstVisitResolutionCount] INT NOT NULL,
    [OpenedDateKey] INT NOT NULL,
    [ScheduledDateKey] INT NOT NULL,
    [DispatchedDateKey] INT NOT NULL,
    [CompletedDateKey] INT NOT NULL,
    [ClosedDateKey] INT NOT NULL,
    [ScheduledTimeOfDayKey] INT NOT NULL,
    [DispatchedTimeOfDayKey] INT NOT NULL,
    [CompletedTimeOfDayKey] INT NOT NULL,
    [CustomerCustomerNumber] NVARCHAR(40) NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NULL,
    [ServiceTechnicianProfileTechnicianProfileNumber] NVARCHAR(50) NULL,
    [ServiceContractServiceContractNumber] NVARCHAR(50) NULL,
    [ServiceRepairCodeServiceRepairCodeCode] NVARCHAR(30) NULL,
    [ServiceTerritoryServiceTerritoryCode] NVARCHAR(30) NOT NULL,
    [ServiceOrderStatusServiceOrderStatusCode] NVARCHAR(20) NOT NULL,
    [PriorityPriorityCode] NVARCHAR(30) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.WarrantyClaimLifecycle', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[WarrantyClaimLifecycle] (
    [WarrantyClaimNumber] NVARCHAR(50) NOT NULL,
    [ProductSerialNumber] NVARCHAR(80) NOT NULL,
    [ClaimedAmount] MONEY NOT NULL,
    [ApprovedAmount] MONEY NULL,
    [PaidAmount] MONEY NULL,
    [ClaimQuantity] DECIMAL(18,4) NOT NULL,
    [ClaimDateKey] INT NOT NULL,
    [FailureDateKey] INT NOT NULL,
    [ApprovedDateKey] INT NOT NULL,
    [PaidDateKey] INT NOT NULL,
    [ClosedDateKey] INT NOT NULL,
    [CustomerCustomerNumber] NVARCHAR(40) NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NOT NULL,
    [PlantPlantCode] NVARCHAR(40) NULL,
    [WarrantyTermWarrantyTermCode] NVARCHAR(30) NOT NULL,
    [WarrantyFailureModeFailureModeCode] NVARCHAR(40) NULL,
    [WarrantyClaimChannelClaimChannelCode] NVARCHAR(30) NOT NULL,
    [ServiceTerritoryServiceTerritoryCode] NVARCHAR(30) NULL,
    [WarrantyClaimStatusWarrantyClaimStatusCode] NVARCHAR(20) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [SeveritySeverityCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.WarrantyCustomerComplaint', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[WarrantyCustomerComplaint] (
    [ComplaintNumber] NVARCHAR(50) NOT NULL,
    [ComplaintCount] INT NOT NULL,
    [ResponseHours] DECIMAL(18,4) NULL,
    [ResolutionHours] DECIMAL(18,4) NULL,
    [ComplaintDateKey] INT NOT NULL,
    [ResponseDueDateKey] INT NOT NULL,
    [ResolvedDateKey] INT NOT NULL,
    [ComplaintTimeOfDayKey] INT NOT NULL,
    [CustomerCustomerNumber] NVARCHAR(40) NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NULL,
    [WarrantyComplaintTypeComplaintTypeCode] NVARCHAR(40) NOT NULL,
    [WarrantyClaimChannelClaimChannelCode] NVARCHAR(30) NOT NULL,
    [ServiceTerritoryServiceTerritoryCode] NVARCHAR(30) NULL,
    [PriorityPriorityCode] NVARCHAR(30) NOT NULL,
    [SeveritySeverityCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO

IF OBJECT_ID(N'stg.WarrantyRmaTransaction', N'U') IS NULL
BEGIN
CREATE TABLE [stg].[WarrantyRmaTransaction] (
    [RmaNumber] NVARCHAR(50) NOT NULL,
    [RmaLineNumber] INT NOT NULL,
    [ReturnedQuantity] DECIMAL(18,4) NOT NULL,
    [CreditAmount] MONEY NULL,
    [ScrapAmount] MONEY NULL,
    [AuthorizedDateKey] INT NOT NULL,
    [ShippedDateKey] INT NOT NULL,
    [ReceivedDateKey] INT NOT NULL,
    [DispositionDateKey] INT NOT NULL,
    [CustomerCustomerNumber] NVARCHAR(40) NOT NULL,
    [ProductProductNumber] NVARCHAR(40) NOT NULL,
    [ReceivingPlantPlantCode] NVARCHAR(40) NULL,
    [ServicePartDispositionServicePartDispositionCode] NVARCHAR(30) NOT NULL,
    [WarrantyFailureModeFailureModeCode] NVARCHAR(40) NULL,
    [WarrantyRmaStatusWarrantyRmaStatusCode] NVARCHAR(20) NOT NULL,
    [UnitOfMeasureUomCode] NVARCHAR(30) NOT NULL,
    [CurrencyCurrencyCode] NVARCHAR(30) NOT NULL,
    [BatchId] BIGINT NOT NULL,
    [RowNumber] BIGINT NOT NULL
);
END
GO
