-- Generated by tools.generator. Do not hand-edit.

-- Subject area: engineering_plm

IF OBJECT_ID(N'dim.BomClass', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[BomClass] (
    [BomClassKey] INT IDENTITY(1,1) NOT NULL,
    [BomClassCode] NVARCHAR(30) NOT NULL,
    [BomFamilyKey] INT NOT NULL DEFAULT -1,
    [BomClassName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_BomClass] PRIMARY KEY CLUSTERED ([BomClassKey])
);
END
GO

IF OBJECT_ID(N'dim.BomFamily', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[BomFamily] (
    [BomFamilyKey] INT IDENTITY(1,1) NOT NULL,
    [BomFamilyCode] NVARCHAR(30) NOT NULL,
    [BomFamilyName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_BomFamily] PRIMARY KEY CLUSTERED ([BomFamilyKey])
);
END
GO

IF OBJECT_ID(N'dim.BomHeader', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[BomHeader] (
    [BomHeaderKey] INT IDENTITY(1,1) NOT NULL,
    [BomNumber] NVARCHAR(40) NOT NULL,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [BomUsageCategoryKey] INT NOT NULL DEFAULT -1,
    [EngineeringLifecycleStatusKey] INT NOT NULL DEFAULT -1,
    [BomHeaderName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_BomHeader] PRIMARY KEY CLUSTERED ([BomHeaderKey])
);
END
GO

IF OBJECT_ID(N'dim.BomSubClass', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[BomSubClass] (
    [BomSubClassKey] INT IDENTITY(1,1) NOT NULL,
    [BomSubClassCode] NVARCHAR(30) NOT NULL,
    [BomClassKey] INT NOT NULL DEFAULT -1,
    [BomSubClassName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_BomSubClass] PRIMARY KEY CLUSTERED ([BomSubClassKey])
);
END
GO

IF OBJECT_ID(N'dim.BomUsageCategory', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[BomUsageCategory] (
    [BomUsageCategoryKey] INT IDENTITY(1,1) NOT NULL,
    [BomUsageCategoryCode] NVARCHAR(30) NOT NULL,
    [BomSubClassKey] INT NOT NULL DEFAULT -1,
    [BomUsageCategoryName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_BomUsageCategory] PRIMARY KEY CLUSTERED ([BomUsageCategoryKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringCadDocument', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringCadDocument] (
    [EngineeringCadDocumentKey] INT IDENTITY(1,1) NOT NULL,
    [CadDocumentNumber] NVARCHAR(40) NOT NULL,
    [EngineeringDocumentCategoryKey] INT NOT NULL DEFAULT -1,
    [DesignerEmployeeKey] INT NULL,
    [EngineeringDocumentTypeKey] INT NOT NULL DEFAULT -1,
    [EngineeringLifecycleStatusKey] INT NOT NULL DEFAULT -1,
    [EngineeringCadDocumentName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_EngineeringCadDocument] PRIMARY KEY CLUSTERED ([EngineeringCadDocumentKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringChangeOrder', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringChangeOrder] (
    [EngineeringChangeOrderKey] INT IDENTITY(1,1) NOT NULL,
    [EngineeringChangeOrderNumber] NVARCHAR(40) NOT NULL,
    [EngineeringTeamKey] INT NOT NULL DEFAULT -1,
    [OwnerEmployeeKey] INT NULL,
    [EngineeringChangeTypeKey] INT NOT NULL DEFAULT -1,
    [ApprovalStatusKey] INT NOT NULL DEFAULT -1,
    [PriorityKey] INT NOT NULL DEFAULT -1,
    [EngineeringChangeOrderName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_EngineeringChangeOrder] PRIMARY KEY CLUSTERED ([EngineeringChangeOrderKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringDiscipline', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringDiscipline] (
    [EngineeringDisciplineKey] INT IDENTITY(1,1) NOT NULL,
    [EngineeringDisciplineCode] NVARCHAR(30) NOT NULL,
    [EngineeringDomainKey] INT NOT NULL DEFAULT -1,
    [EngineeringDisciplineName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_EngineeringDiscipline] PRIMARY KEY CLUSTERED ([EngineeringDisciplineKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringDocumentCategory', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringDocumentCategory] (
    [EngineeringDocumentCategoryKey] INT IDENTITY(1,1) NOT NULL,
    [EngineeringDocumentCategoryCode] NVARCHAR(30) NOT NULL,
    [EngineeringDocumentSubClassKey] INT NOT NULL DEFAULT -1,
    [EngineeringDocumentCategoryName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_EngineeringDocumentCategory] PRIMARY KEY CLUSTERED ([EngineeringDocumentCategoryKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringDocumentClass', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringDocumentClass] (
    [EngineeringDocumentClassKey] INT IDENTITY(1,1) NOT NULL,
    [EngineeringDocumentClassCode] NVARCHAR(30) NOT NULL,
    [EngineeringDocumentDomainKey] INT NOT NULL DEFAULT -1,
    [EngineeringDocumentClassName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_EngineeringDocumentClass] PRIMARY KEY CLUSTERED ([EngineeringDocumentClassKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringDocumentDomain', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringDocumentDomain] (
    [EngineeringDocumentDomainKey] INT IDENTITY(1,1) NOT NULL,
    [EngineeringDocumentDomainCode] NVARCHAR(30) NOT NULL,
    [EngineeringDocumentDomainName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_EngineeringDocumentDomain] PRIMARY KEY CLUSTERED ([EngineeringDocumentDomainKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringDocumentSubClass', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringDocumentSubClass] (
    [EngineeringDocumentSubClassKey] INT IDENTITY(1,1) NOT NULL,
    [EngineeringDocumentSubClassCode] NVARCHAR(30) NOT NULL,
    [EngineeringDocumentClassKey] INT NOT NULL DEFAULT -1,
    [EngineeringDocumentSubClassName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_EngineeringDocumentSubClass] PRIMARY KEY CLUSTERED ([EngineeringDocumentSubClassKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringDomain', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringDomain] (
    [EngineeringDomainKey] INT IDENTITY(1,1) NOT NULL,
    [EngineeringDomainCode] NVARCHAR(30) NOT NULL,
    [EngineeringDomainName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_EngineeringDomain] PRIMARY KEY CLUSTERED ([EngineeringDomainKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringGroup', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringGroup] (
    [EngineeringGroupKey] INT IDENTITY(1,1) NOT NULL,
    [EngineeringGroupCode] NVARCHAR(30) NOT NULL,
    [EngineeringDisciplineKey] INT NOT NULL DEFAULT -1,
    [EngineeringGroupName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_EngineeringGroup] PRIMARY KEY CLUSTERED ([EngineeringGroupKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringMaterialSpecification', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringMaterialSpecification] (
    [EngineeringMaterialSpecificationKey] INT IDENTITY(1,1) NOT NULL,
    [MaterialSpecificationCode] NVARCHAR(40) NOT NULL,
    [EngineeringDisciplineKey] INT NOT NULL DEFAULT -1,
    [MeasurementSystemKey] INT NOT NULL DEFAULT -1,
    [ComplianceStandardKey] INT NOT NULL DEFAULT -1,
    [EngineeringMaterialSpecificationName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_EngineeringMaterialSpecification] PRIMARY KEY CLUSTERED ([EngineeringMaterialSpecificationKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringPartRevision', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringPartRevision] (
    [EngineeringPartRevisionKey] INT IDENTITY(1,1) NOT NULL,
    [PartRevisionNumber] NVARCHAR(40) NOT NULL,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [EngineeringTeamKey] INT NOT NULL DEFAULT -1,
    [EngineeringLifecycleStatusKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [EngineeringPartRevisionName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_EngineeringPartRevision] PRIMARY KEY CLUSTERED ([EngineeringPartRevisionKey])
);
END
GO

IF OBJECT_ID(N'dim.EngineeringTeam', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[EngineeringTeam] (
    [EngineeringTeamKey] INT IDENTITY(1,1) NOT NULL,
    [EngineeringTeamCode] NVARCHAR(30) NOT NULL,
    [EngineeringGroupKey] INT NOT NULL DEFAULT -1,
    [EngineeringTeamName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_EngineeringTeam] PRIMARY KEY CLUSTERED ([EngineeringTeamKey])
);
END
GO

IF OBJECT_ID(N'dim.RoutingHeader', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[RoutingHeader] (
    [RoutingHeaderKey] INT IDENTITY(1,1) NOT NULL,
    [RoutingNumber] NVARCHAR(40) NOT NULL,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [RoutingOperationTypeKey] INT NOT NULL DEFAULT -1,
    [EngineeringLifecycleStatusKey] INT NOT NULL DEFAULT -1,
    [RoutingHeaderName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_RoutingHeader] PRIMARY KEY CLUSTERED ([RoutingHeaderKey])
);
END
GO

IF OBJECT_ID(N'dim.RoutingOperationClass', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[RoutingOperationClass] (
    [RoutingOperationClassKey] INT IDENTITY(1,1) NOT NULL,
    [RoutingOperationClassCode] NVARCHAR(30) NOT NULL,
    [RoutingProcessGroupKey] INT NOT NULL DEFAULT -1,
    [RoutingOperationClassName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_RoutingOperationClass] PRIMARY KEY CLUSTERED ([RoutingOperationClassKey])
);
END
GO

IF OBJECT_ID(N'dim.RoutingOperationType', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[RoutingOperationType] (
    [RoutingOperationTypeKey] INT IDENTITY(1,1) NOT NULL,
    [RoutingOperationTypeCode] NVARCHAR(30) NOT NULL,
    [RoutingOperationClassKey] INT NOT NULL DEFAULT -1,
    [RoutingOperationTypeName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_RoutingOperationType] PRIMARY KEY CLUSTERED ([RoutingOperationTypeKey])
);
END
GO

IF OBJECT_ID(N'dim.RoutingProcessFamily', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[RoutingProcessFamily] (
    [RoutingProcessFamilyKey] INT IDENTITY(1,1) NOT NULL,
    [RoutingProcessFamilyCode] NVARCHAR(30) NOT NULL,
    [RoutingProcessFamilyName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_RoutingProcessFamily] PRIMARY KEY CLUSTERED ([RoutingProcessFamilyKey])
);
END
GO

IF OBJECT_ID(N'dim.RoutingProcessGroup', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[RoutingProcessGroup] (
    [RoutingProcessGroupKey] INT IDENTITY(1,1) NOT NULL,
    [RoutingProcessGroupCode] NVARCHAR(30) NOT NULL,
    [RoutingProcessFamilyKey] INT NOT NULL DEFAULT -1,
    [RoutingProcessGroupName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_RoutingProcessGroup] PRIMARY KEY CLUSTERED ([RoutingProcessGroupKey])
);
END
GO
