-- Generated by tools.generator. Do not hand-edit.

-- Subject area: quality

IF OBJECT_ID(N'dim.QualityCertificateAnalysis', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityCertificateAnalysis] (
    [QualityCertificateAnalysisKey] INT IDENTITY(1,1) NOT NULL,
    [CertificateAnalysisNumber] NVARCHAR(40) NOT NULL,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [SupplierKey] INT NULL,
    [QualityMethodProcedureKey] INT NOT NULL DEFAULT -1,
    [ComplianceStandardKey] INT NOT NULL DEFAULT -1,
    [ApprovalStatusKey] INT NOT NULL DEFAULT -1,
    [QualityCertificateAnalysisName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_QualityCertificateAnalysis] PRIMARY KEY CLUSTERED ([QualityCertificateAnalysisKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityCharacteristicClass', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityCharacteristicClass] (
    [QualityCharacteristicClassKey] INT IDENTITY(1,1) NOT NULL,
    [QualityCharacteristicClassCode] NVARCHAR(30) NOT NULL,
    [QualityCharacteristicDomainKey] INT NOT NULL DEFAULT -1,
    [QualityCharacteristicClassName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityCharacteristicClass] PRIMARY KEY CLUSTERED ([QualityCharacteristicClassKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityCharacteristicDomain', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityCharacteristicDomain] (
    [QualityCharacteristicDomainKey] INT IDENTITY(1,1) NOT NULL,
    [QualityCharacteristicDomainCode] NVARCHAR(30) NOT NULL,
    [QualityCharacteristicDomainName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityCharacteristicDomain] PRIMARY KEY CLUSTERED ([QualityCharacteristicDomainKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityCharacteristicGroup', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityCharacteristicGroup] (
    [QualityCharacteristicGroupKey] INT IDENTITY(1,1) NOT NULL,
    [QualityCharacteristicGroupCode] NVARCHAR(30) NOT NULL,
    [QualityCharacteristicClassKey] INT NOT NULL DEFAULT -1,
    [QualityCharacteristicGroupName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityCharacteristicGroup] PRIMARY KEY CLUSTERED ([QualityCharacteristicGroupKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityCharacteristicType', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityCharacteristicType] (
    [QualityCharacteristicTypeKey] INT IDENTITY(1,1) NOT NULL,
    [QualityCharacteristicTypeCode] NVARCHAR(30) NOT NULL,
    [QualityCharacteristicGroupKey] INT NOT NULL DEFAULT -1,
    [QualityCharacteristicTypeName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityCharacteristicType] PRIMARY KEY CLUSTERED ([QualityCharacteristicTypeKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityDefectCategory', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityDefectCategory] (
    [QualityDefectCategoryKey] INT IDENTITY(1,1) NOT NULL,
    [QualityDefectCategoryCode] NVARCHAR(30) NOT NULL,
    [QualityDefectFamilyKey] INT NOT NULL DEFAULT -1,
    [QualityDefectCategoryName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityDefectCategory] PRIMARY KEY CLUSTERED ([QualityDefectCategoryKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityDefectCode', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityDefectCode] (
    [QualityDefectCodeKey] INT IDENTITY(1,1) NOT NULL,
    [QualityDefectCodeCode] NVARCHAR(30) NOT NULL,
    [QualityDefectSubCategoryKey] INT NOT NULL DEFAULT -1,
    [QualityDefectCodeName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityDefectCode] PRIMARY KEY CLUSTERED ([QualityDefectCodeKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityDefectFamily', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityDefectFamily] (
    [QualityDefectFamilyKey] INT IDENTITY(1,1) NOT NULL,
    [QualityDefectFamilyCode] NVARCHAR(30) NOT NULL,
    [QualityDefectFamilyName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityDefectFamily] PRIMARY KEY CLUSTERED ([QualityDefectFamilyKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityDefectSubCategory', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityDefectSubCategory] (
    [QualityDefectSubCategoryKey] INT IDENTITY(1,1) NOT NULL,
    [QualityDefectSubCategoryCode] NVARCHAR(30) NOT NULL,
    [QualityDefectCategoryKey] INT NOT NULL DEFAULT -1,
    [QualityDefectSubCategoryName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityDefectSubCategory] PRIMARY KEY CLUSTERED ([QualityDefectSubCategoryKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityGauge', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityGauge] (
    [QualityGaugeKey] INT IDENTITY(1,1) NOT NULL,
    [GaugeNumber] NVARCHAR(40) NOT NULL,
    [AssetKey] INT NULL,
    [QualityLabCellKey] INT NOT NULL DEFAULT -1,
    [QualityCalibrationStatusKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [QualityGaugeName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_QualityGauge] PRIMARY KEY CLUSTERED ([QualityGaugeKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityInspectionCharacteristic', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityInspectionCharacteristic] (
    [QualityInspectionCharacteristicKey] INT IDENTITY(1,1) NOT NULL,
    [InspectionCharacteristicCode] NVARCHAR(40) NOT NULL,
    [QualityCharacteristicTypeKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [QualityResultStatusKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionCharacteristicName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_QualityInspectionCharacteristic] PRIMARY KEY CLUSTERED ([QualityInspectionCharacteristicKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityInspectionLot', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityInspectionLot] (
    [QualityInspectionLotKey] INT IDENTITY(1,1) NOT NULL,
    [InspectionLotNumber] NVARCHAR(40) NOT NULL,
    [ProductKey] INT NOT NULL DEFAULT -1,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [SupplierKey] INT NULL,
    [ProductionLotKey] INT NULL,
    [QualityInspectionTypeKey] INT NOT NULL DEFAULT -1,
    [QualityResultStatusKey] INT NOT NULL DEFAULT -1,
    [UnitOfMeasureKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionLotName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_QualityInspectionLot] PRIMARY KEY CLUSTERED ([QualityInspectionLotKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityInspectionPlan', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityInspectionPlan] (
    [QualityInspectionPlanKey] INT IDENTITY(1,1) NOT NULL,
    [InspectionPlanNumber] NVARCHAR(40) NOT NULL,
    [ProductKey] INT NULL,
    [SupplierKey] INT NULL,
    [QualityMethodProcedureKey] INT NOT NULL DEFAULT -1,
    [QualityInspectionTypeKey] INT NOT NULL DEFAULT -1,
    [EngineeringLifecycleStatusKey] INT NULL,
    [QualityInspectionPlanName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_QualityInspectionPlan] PRIMARY KEY CLUSTERED ([QualityInspectionPlanKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityLabCell', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityLabCell] (
    [QualityLabCellKey] INT IDENTITY(1,1) NOT NULL,
    [QualityLabCellCode] NVARCHAR(30) NOT NULL,
    [QualityLabGroupKey] INT NOT NULL DEFAULT -1,
    [QualityLabCellName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityLabCell] PRIMARY KEY CLUSTERED ([QualityLabCellKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityLabGroup', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityLabGroup] (
    [QualityLabGroupKey] INT IDENTITY(1,1) NOT NULL,
    [QualityLabGroupCode] NVARCHAR(30) NOT NULL,
    [QualityOrganizationSiteKey] INT NOT NULL DEFAULT -1,
    [QualityLabGroupName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityLabGroup] PRIMARY KEY CLUSTERED ([QualityLabGroupKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityMethodClass', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityMethodClass] (
    [QualityMethodClassKey] INT IDENTITY(1,1) NOT NULL,
    [QualityMethodClassCode] NVARCHAR(30) NOT NULL,
    [QualityMethodFamilyKey] INT NOT NULL DEFAULT -1,
    [QualityMethodClassName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityMethodClass] PRIMARY KEY CLUSTERED ([QualityMethodClassKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityMethodFamily', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityMethodFamily] (
    [QualityMethodFamilyKey] INT IDENTITY(1,1) NOT NULL,
    [QualityMethodFamilyCode] NVARCHAR(30) NOT NULL,
    [QualityMethodFamilyName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityMethodFamily] PRIMARY KEY CLUSTERED ([QualityMethodFamilyKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityMethodProcedure', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityMethodProcedure] (
    [QualityMethodProcedureKey] INT IDENTITY(1,1) NOT NULL,
    [QualityMethodProcedureCode] NVARCHAR(30) NOT NULL,
    [QualityMethodClassKey] INT NOT NULL DEFAULT -1,
    [QualityMethodProcedureName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityMethodProcedure] PRIMARY KEY CLUSTERED ([QualityMethodProcedureKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityMethodStep', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityMethodStep] (
    [QualityMethodStepKey] INT IDENTITY(1,1) NOT NULL,
    [QualityMethodStepCode] NVARCHAR(30) NOT NULL,
    [QualityMethodProcedureKey] INT NOT NULL DEFAULT -1,
    [QualityMethodStepName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityMethodStep] PRIMARY KEY CLUSTERED ([QualityMethodStepKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityNonConformance', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityNonConformance] (
    [QualityNonConformanceKey] INT IDENTITY(1,1) NOT NULL,
    [NonConformanceNumber] NVARCHAR(40) NOT NULL,
    [ProductKey] INT NULL,
    [PlantKey] INT NOT NULL DEFAULT -1,
    [QualityDefectCodeKey] INT NOT NULL DEFAULT -1,
    [QualityDefectSeverityKey] INT NOT NULL DEFAULT -1,
    [SeverityKey] INT NOT NULL DEFAULT -1,
    [QualityResultStatusKey] INT NOT NULL DEFAULT -1,
    [QualityNonConformanceName] NVARCHAR(200) NOT NULL,
    [RevisionCode] NVARCHAR(20) NULL,
    [ActiveFlag] BIT NOT NULL DEFAULT 1,
    [StandardValue] DECIMAL(18,4) NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [EffectiveFromUtc] DATETIME2(3) NOT NULL,
    [EffectiveToUtc] DATETIME2(3) NOT NULL DEFAULT '9999-12-31',
    [IsCurrent] BIT NOT NULL DEFAULT 1,
    [RowHash] BINARY(32) NOT NULL,
    CONSTRAINT [PK_dim_QualityNonConformance] PRIMARY KEY CLUSTERED ([QualityNonConformanceKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityOrganizationRegion', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityOrganizationRegion] (
    [QualityOrganizationRegionKey] INT IDENTITY(1,1) NOT NULL,
    [QualityOrganizationRegionCode] NVARCHAR(30) NOT NULL,
    [QualityOrganizationRegionName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityOrganizationRegion] PRIMARY KEY CLUSTERED ([QualityOrganizationRegionKey])
);
END
GO

IF OBJECT_ID(N'dim.QualityOrganizationSite', N'U') IS NULL
BEGIN
CREATE TABLE [dim].[QualityOrganizationSite] (
    [QualityOrganizationSiteKey] INT IDENTITY(1,1) NOT NULL,
    [QualityOrganizationSiteCode] NVARCHAR(30) NOT NULL,
    [QualityOrganizationRegionKey] INT NOT NULL DEFAULT -1,
    [QualityOrganizationSiteName] NVARCHAR(120) NOT NULL,
    [SourceSystemKey] INT NOT NULL DEFAULT -1,
    [BatchId] BIGINT NOT NULL DEFAULT 0,
    [LoadedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_dim_QualityOrganizationSite] PRIMARY KEY CLUSTERED ([QualityOrganizationSiteKey])
);
END
GO
